### ISSUE TITLE
Bug report - [Short description]

### ISSUE THREAD

**Issue by D180271** [JohanBendz/com.tuya.zigbee#1001]
Na de laatste update zijn heel veel zigbee producten verdwenen uit de app.

Ik heb een perfect werkende 4 channel relais board gehad, na de update was hij niet meer aanwezig.
Ook de slimme motion sensors werkten niet meer, de lucht conditie sensoren waren ook plotseling verdwenen.
De lichtschakelaars deden het ook niet meer, maar die zijn hersteld en werken weer naar behoren.
 De lijst die jullie ondersteunden was plotseling ook veel kleiner geworden..
Zouden jullie dit alsjeblieft kunnen herstellen..

**Comment by JohanBendz** [comment]
Hi @D180271, You must accidentally have installled the Live version of the app. Reinstall the Test version.
