### ISSUE TITLE
Device Request - [_TZE200_vvmbj46n] - [Tuya] / [TS0601]

### ISSUE THREAD

**Issue by JCHRA007** [JohanBendz/com.tuya.zigbee#1003]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

### Device Information

- Device Name: `_TZE200_vvmbj46n`
- Device Model: `TS0601`
- Device Description: `Temperature & Humidity Sensor`
- Link to device image: https://fr.aliexpress.com/item/1005005923865974.html?gatewayAdapt=glo2fra

### Device Interview

{
"id":67,"type":"EndDevice","ieeeAddr":"0xa4c138a978038dbe","nwkAddr":21189,"manufId":4417,"manufName":"_TZE200_vvmbj46n","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"l ,\u0011","65506":56,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_vvmbj46n","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1700109974399,"defaultSendRequestWhen":"immediate"
}

I´ve tryed everthing to inerview the device ... but found the device in a other forum.
This information was found on this link:
https://github.com/Koenkk/zigbee2mqtt/issues/19731

### Additional Comments:

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by JohanBendz** [comment]
Hi @JCHRA007, this device is already supported by the test version of the app: https://homey.app/en-us/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by Qpadder** [comment]
I own this device and even with the test version of Tuya Zigbee it does not find the correct device.
