### ISSUE TITLE
Bug report - Temp & Humidity sensor adds as unknown device - TZ3000_fllyghyj

### ISSUE THREAD

**Issue by 09sws** [JohanBendz/com.tuya.zigbee#1004]
### Describe the bug 

When adding the Temperature & Humidity sensor it gets added as an unknown zigbee device with only on/off capabilites

### To Reproduce

1. Add Device
2. Select the Tuya Zigbee app
3. Put the sensor in the add mode
4. Device is added as unknown device

### Expected behavior
The device should be added as a sensor with temperature and humidity capabilites.

**### App and Homey version**
> * Homey Pro 2023
> * Version 12.1.2
> * v0.1.45

### Additional context
![IMG_6417](https://github.com/user-attachments/assets/886743eb-2038-4490-a34d-4f288c0a8442)
![IMG_6419](https://github.com/user-attachments/assets/ac99d190-d9ac-4537-9f5c-d0b43094baf2)

**Comment by Peter-Celica** [comment]
Hi 09sws,
You are using the wrong Tuya app, you should use the experimental version 0.2.73 (https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/) 
The regular ZigBee app doesn't support all the devices yet.

Best regards Peter.

**Comment by 09sws** [comment]
@Peter-Celica thanks for your quick reply, it works with the other app :) I'm completely new to Homey and zigbee devices so thanks for your support

**Comment by Peter-Celica** [comment]
> @Peter-Celica thanks for your quick reply, it works with the other app :) I'm completely new to Homey and zigbee devices so thanks for your support

No problem we are here to help each other, good luck and enjoy your Homey.

**Comment by lokrheim** [comment]
How did you get it to work @09sws ? I'm now running the Tuya Zigbee v0.2.73 Test version but I still only see this device with on/off capabilites.
