### ISSUE TITLE
Bug report - Temp & Humidity sensor adds as unknown device - TZ3000_bjawzodf

### ISSUE THREAD

**Issue by 09sws** [JohanBendz/com.tuya.zigbee#1005]
### Describe the bug

When adding the Temperature & Humidity sensor it gets added as an unknown zigbee device with only on/off capabilites

### To Reproduce

Add Device
Select the Tuya Zigbee app
Put the sensor in the add mode
Device is added as unknown device

### Expected behavior

The device should be added as a sensor with temperature and humidity capabilites.

### App and Homey version

> * Homey Pro 2023
> * Version 12.1.2
> * v0.1.45

### Screenshots
![IMG_6420](https://github.com/user-attachments/assets/6c379d09-da47-42b0-a6cb-558e1430a19d)

**Comment by Peter-Celica** [comment]
Hi 09sws,
You are using the wrong Tuya app, you should use the experimental version 0.2.73 (https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/) 
The regular ZigBee app doesn't support all the devices yet.

Best regards Peter.

**Comment by 09sws** [comment]
@Peter-Celica thanks for your quick reply, it works with the other app :) I'm completely new to Homey and zigbee devices so thanks for your support

**Comment by Peter-Celica** [comment]
> @Peter-Celica thanks for your quick reply, it works with the other app :) I'm completely new to Homey and zigbee devices so thanks for your support

No problem we are here to help each other, good luck and enjoy your Homey.

**Comment by Godart-gouda** [comment]
Hello, I bought 2 of these sensors and had the same issue with unknown zigbee device. I then installed the 0.2.73 version but then they come up with a something went wrong error or device has stopped responding error. I somehow got 1 installed after many tries but the second does not connect. 
Any ideas on this
