### ISSUE TITLE
Tuya smartplug 20A with powermonitor shenzhen 

### ISSUE THREAD

**Issue by Jano1960** [JohanBendz/com.tuya.zigbee#1006]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.
![20241019_121718](https://github.com/user-attachments/assets/63766fb8-47be-48de-ba8b-a4cbf275e220)
![20241019_121745](https://github.com/user-attachments/assets/6d13a516-9a76-4ab6-83f1-c044d9d3d856)

### Device Information

- Device Name: `Provide the name of the device`
- Device Model: `Provide the model number or identifier`
- Device Description: `Describe in short the functionality of the device`
- Link to device image: [Provide the URL to an image/photo of the device](https://www.url-to-images.com)
![Screenshot_20241020-171820_Homey](https://github.com/user-attachments/assets/a4303051-4672-492a-8eae-b029a1bd7c1e)
![Screenshot_20241020-171828_Homey](https://github.com/user-attachments/assets/b3ad1028-8091-4471-90b9-d979472cc542)
![Screenshot_20241020-171846_Homey](https://github.com/user-attachments/assets/24e6430a-f779-42a9-b815-f99981b1d5c2)

### Device Interview

"ids": { "modelId": "TS011F", "manufacturerName": "_TZ3000_wzmuk9ai" }, "endpoints": { "ieeeAddress": "70:b3:d5:2b:60:0f:ce:e4", "networkAddress": 52409, "modelId": "TS011F", "manufacturerName": "_TZ3000_wzmuk9ai", "endpointDescriptors": [ { "status": "SUCCESS", "nwkAddrOfInterest": 52409, "_reserved": 26, "endpointId": 1, "applicationProfileId": 260, "applicationDeviceId": 81, "applicationDeviceVersion": 0, "_reserved1": 1, "inputClusters": [ 0, 6, 3, 4, 5, 57345, 2820, 1794 ], "outputClusters": [] } ], "deviceType": "router", "receiveWhenIdle": true, "swBuildId": "500+TZSKT21AD101", "capabilities": { "alternatePANCoordinator": false, "deviceType": true, "powerSourceMains": true, "receiveWhenIdle": true, "security": false, "allocateAddress": true }, "extendedEndpointDescriptors": { "1": { "clusters": { "basic": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" }, "onOff": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" }, "identify": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" }, "groups": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" }, "scenes": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" }, "electricalMeasurement": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" }, "metering": { "attributes": "UNSUP_GENERAL_COMMAND", "commandsGenerated": "UNSUP_GENERAL_COMMAND", "commandsReceived": "UNSUP_GENERAL_COMMAND" } }, "bindings": {} } } }70:b3:d5:2b:60:0f:ce:e4
{
    ["Paste the device interview information here"]
}
```

### Additional Comments:

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by JohanBendz** [comment]
Added to next release.
