### ISSUE TITLE
Bug report - [Short description]

### ISSUE THREAD

**Issue by gupper** [JohanBendz/com.tuya.zigbee#1010]
### Describe the bug

Added a motion sensor to Homey with the Zigbee test app.  All went smooth but the device is not reporting any motion or lux info to Homey.

Detalis of the device:

Property	Value
ID	d6e03864-b7fb-4e8f-800a-9ce4417f3f55
Name	Motion Sensor
Class	sensor
Driver	homey:app:com.tuya.zigbee:motion_sensor_2
Ready	Yes
Available	Yes
Warning	No
Custom icon	No

Data
Key	Value
token	"92569851-fdba-4058-8b27-ba0767ae4155"

Settings
Key	Value
zb_product_id	"TS0601"
zb_manufacturer_name	"_TZE200_3towulqd"
zb_receive_when_idle	"⨯"
zb_device_type	"enddevice"
zb_ieee_address	"a4:c1:38:ab:bf:ae:20:3d"
zb_sw_build_id	"0122052017"
zb_touchlink_group_ids	""
batteryThreshold	20
zone_activity_disabled	false

Capabilities
ID	Title	Type	Value	Set Value	Last Changed
measure_battery	Accuniveau	number	null		
measure_luminance	Helderheid	number	null		
alarm_motion	Bewegingsalarm	boolean	null		
alarm_battery	Batterij alarm	boolean	null

### Expected behavior

> A clear and concise description of what you expected to happen.

### App and Homey version

> * What Homey version are you running? 2023 
> * What version of Homey firmware do you use? 12.1.2
> * What version of the Tuya Zigbee App are you using? zigbee test version (live version does not regonize the sensor) 

### Additional context

No movement or lux info comes available in homey. 

Red light is blinking by movemebt on the sensor.

**Comment by JohanBendz** [comment]
Fixed in the next release.

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
