### ISSUE TITLE
1 gang Zigbee dimmer module

### ISSUE THREAD

**Issue by eeckelaertyannick** [JohanBendz/com.tuya.zigbee#108]

**Comment by eeckelaertyannick** [comment]
Hi Johan,

I got a problem whit me 1 gang Zigbee dimmer module.
It works fine with Homey. But when I use the manual rocker switch it dims I whant it to turn of en on. When I flip the switch it dims out en when i flip it again the module flips on but lights stay of because of the dimm level. I ame on the experimental software. Can u solve this? Ore is this a hardware error? It's my first time that I use the dimmer module every were in home I have the switch module's ![image](https://user-images.githubusercontent.com/82699595/134802375-cdf1cab5-5b83-41d7-8a9a-595bdfa5c9d5.jpeg)

**Comment by gotthD** [comment]
> Hi Johan,
> 
> I got a problem whit me 1 gang Zigbee dimmer module.
> It works fine with Homey. But when I use the manual rocker switch it dims I whant it to turn of en on. When I flip the switch it dims out en when i flip it again the module flips on but lights stay of because of the dimm level. I ame on the experimental software. Can u solve this? Ore is this a hardware error? It's my first time that I use the dimmer module every were in home I have the switch module's ![image](https://user-images.githubusercontent.com/82699595/134802375-cdf1cab5-5b83-41d7-8a9a-595bdfa5c9d5.jpeg)

Sounds like the switch you are using is a normal rocker switch, could it be that you need a “reset light switch” (retractive switch).

**Comment by danielgajdos** [comment]
Hi,
I was playing with a similar dimmer from Moes and it looks like there is exactly the same issue. When the dimmer is On and you set dim to 0, the light is on minimum but still on, so it’s but in this state if you turn dimmer Off and On again the light stays off until dim is greater than 0. So it looks like we need to automatically set dim to non zero value if it equals to zero when turning to On state.

**Comment by eeckelaertyannick** [comment]
> > Hi Johan,
> 
> > 
> 
> > I got a problem whit me 1 gang Zigbee dimmer module.
> 
> > It works fine with Homey. But when I use the manual rocker switch it dims I whant it to turn of en on. When I flip the switch it dims out en when i flip it again the module flips on but lights stay of because of the dimm level. I ame on the experimental software. Can u solve this? Ore is this a hardware error? It's my first time that I use the dimmer module every were in home I have the switch module's ![image](https://user-images.githubusercontent.com/82699595/134802375-cdf1cab5-5b83-41d7-8a9a-595bdfa5c9d5.jpeg)
> 
> 
> 
> Sounds like the switch you are using is a normal rocker switch, could it be that you need a “reset light switch” (retractive switch). 

No, the module is for a normall rocker switch.

**Comment by eeckelaertyannick** [comment]
@danielgajdos, I hope there comes a new update for this driver. The problem is in the software of the device. It's my first dimmer module whit neutral. I don't know if je turn it in of position that it schould dom out or just go's out like te relais module. The normal on/of.

**Comment by eeckelaertyannick** [comment]
> Hi,
> 
> I was playing with a similar dimmer from Moes and it looks like there is exactly the same issue. When the dimmer is On and you set dim to 0, the light is on minimum but still on, so it’s but in this state if you turn dimmer Off and On again the light stays off until dim is greater than 0. So it looks like we need to automatically set dim to non zero value if it equals to zero when turning to On state.

Already did this. It works now but I ThinQ should be updated because it's for normal rocker switch use, hope the update comes soon

**Comment by eeckelaertyannick** [comment]
@JohanBendz do you have some info about this problem? Thx Johan
