### ISSUE TITLE
Tuya Zigbee 2 gang switch with neutral

### ISSUE THREAD

**Issue by eeckelaertyannick** [JohanBendz/com.tuya.zigbee#122]
Hey Johan,

I just added a new Zigbee switch module. But when i add it it show as a unknown Zigbee device. Can you please help with this. I can now only use 1 gang instat of 2.

Thx! 

![image](https://user-images.githubusercontent.com/82699595/138302795-0ed685b5-58b4-4cae-b589-241f98a717ba.jpeg)

![image](https://user-images.githubusercontent.com/82699595/138302824-8ee27717-6909-4907-814e-b031b5b45c27.jpeg)

  "ids": {
    "modelId": "TS0002",
    "manufacturerName": "_TZ3000_fisb3ajo"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 256,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          5,
          4,
          6,
          57345,
          57344,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      },
      {
        "endpointId": 2,
        "applicationProfileId": 260,
        "applicationDeviceId": 256,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          5,
          4,
          6,
          57345
        ],
        "outputClusters": []
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": true,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16385,
                "name": "onTime",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16386,
                "name": "offWaitTime",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32769,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32770,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 20480,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 65
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_fisb3ajo"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0002"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 8
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 9
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      },
      "2": {
        "clusters": {
          "scenes": {
            "attributes": [
              {
                "acl": [],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [],
                "id": 25
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [],
                "id": 10
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": false,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16385,
                "name": "onTime",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16386,
                "name": "offWaitTime",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32769,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32770,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 20480,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          }
        },
        "bindings": {}
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

**Comment by JohanBendz** [comment]
Added to next release.

**Comment by dlnraja** [comment]
@elgato7

**v5.5.998 Fix Applied** for Longsam Mini M3 curtain motor (`_TZE204_xu4a5rhj`):

✅ Position is now **INVERTED** correctly (DP2: 100-value)

**Please test:**
- [ ] Does 0% = fully closed and 100% = fully open?
- [ ] Does the position slider work correctly?
- [ ] Any issues with open/close commands?

If position is still inverted, let me know the exact behavior you observe.

**Comment by elgato7** [comment]
@dlnraja 

i'm now on version 5.7.15 with the same issue


i can make and see all the changes happens in the homey app on the phone and dev tool but the curtain motor device doesn't spin when i makes the changes.

the only time i worked as suppose on the homey device was with update v5.5.937.
is there a remarkeble change after this update?
is it possible to make a rollback to v5.5.937 to see if it will work again?
 
the curtain motor works well when i use the remote controle it came with or when i install it on the smartlife app.

**Comment by dlnraja** [comment]
I will investigate


There is a link to download the file 5.5.937
8f97f941-14cb-49e1-8d73-a41904ebf787.tar.gz
<https://drive.google.com/file/d/1qQqiuHqn_6TJAT33RovNUt65KsQZUMYV/view?usp=drivesdk>

**Comment by dlnraja** [comment]
Link accès unlocked :)

**Comment by elgato7** [comment]
thanks, 

do you have a "how to" to install it?

**Comment by dlnraja** [comment]
Installing an app from a source file (like your .tar.gz) is known as CLI
Sideloading. Since you are using a Homey Pro, this is a standard developer
procedure.
Here is your English tutorial to get that specific version running.
🛠 Prerequisites
Before starting, ensure you have the following installed on your computer:
 * Node.js: Download and install from nodejs.org.
 * Homey CLI: Once Node.js is installed, open your terminal (Command Prompt
or PowerShell) and run:
   npm install -g homey
📂 Step 1: Prepare the Source Code
 * Extract the file: Unzip your .tar.gz file into a folder on your computer.
 * Locate app.json: Open the extracted folder. You should see a file named
app.json and a package.json. This is the root of your app.
 * Open Terminal: Open your terminal and navigate to this folder.
   * Tip: Type cd followed by a space, then drag the folder into the
terminal window.
🔑 Step 2: Login to Homey
In your terminal, you need to link your computer to your Homey account:
 * Run the command: homey login
 * A browser window will open. Log in with your Athom account and authorize
the CLI.
 * Back in the terminal, verify your box is visible by running: homey list
🚀 Step 3: Install the App
Now, you will push the code from your computer directly to your Homey Pro.
 * Clean the environment (Optional but recommended):
   npm install
   (This ensures all dependencies mentioned in the code are downloaded
locally).
 * Run the install command:
   homey app install
> [!IMPORTANT]
> If you already have a version of this app installed from the official App
Store, sideloading this version will overwrite it. Your existing devices
and flows should remain, but the app will no longer receive official
updates until you reinstall from the Store.
>
🔍 Troubleshooting
 * "Homey not found": Ensure your computer and your Homey Pro are on the
same Wi-Fi network.
 * Version Mismatch: If the app is very old, the CLI might complain about
sdk versions. If it says "Invalid SDK version," the code might need manual
updating to be compatible with Homey Pro 2023.
 * Stay Running: If you want to see live logs to make sure the app isn't
crashing, use homey app run instead of install.
Would you like me to check the app.json file inside your archive to see
which Homey SDK version it's using?

**Comment by elgato7** [comment]
thanks

**Comment by dlnraja** [comment]
Good night I'm felling tired right now it's 5.35 in GMT+1 here .

**Comment by elgato7** [comment]
hi @dlnraja,

yes... it work again with update v5.5.937, but only with the first DP.
the motor doesn't react on the other ones 

<img width="589" height="259" alt="Image" src="https://github.com/user-attachments/assets/e3382f2c-198b-4107-9cc7-5dcddaddc163" />

i can controle the motor from the mobile app and the dev tool with the first DP

![Image](https://github.com/user-attachments/assets/2c44c921-cb4f-411f-8eb1-078ab3e606d9)


with this version i dont have to option to make a diagnostic report
