### ISSUE TITLE
Tuya TS0121 (or TS011F?)  Zigbee smart plug with metering not recognised

### ISSUE THREAD

**Issue by autohans** [JohanBendz/com.tuya.zigbee#123]
Hello,
Ik bought some white label Tuya TS0121 Zigbee smart plugs with metering.

_TZ3000_cphmq0q7 | TS011F

[https://nl.aliexpress.com/item/1005002346520837.html?spm=a2g0s.9042311.0.0.43c64c4dFZrTEV
![2021-10-24 16_20_25-Window](https://user-images.githubusercontent.com/91913466/138598297-9a600b46-e895-454e-9f36-c3ab8753ae9a.png)
](https://nl.aliexpress.com/item/1005002346520837.html?spm=a2g0s.9042311.0.0.43c64c4dFZrTEV)
The Tuya zigbee app does not recognise en now it is set as "unknown zigbee device" without metering. 
homey vserion 7.1.5  Tuya zigbee app v0.1.45

How can this be solved?

regards,
Hans

**Comment by martijnpieters** [comment]
@autohans I think we have bought the same device. I’ve added all details over here: https://community.athom.com/t/app-pro-tuya-zigbee-app/26439/1718?u=martijnpieters

**Comment by martijnpieters** [comment]
#89 is about the same device

**Comment by JohanBendz** [comment]
Added to next release.
