### ISSUE TITLE
Tuya App for Homey Bridge

### ISSUE THREAD

**Issue by janv01** [JohanBendz/com.tuya.zigbee#124]
Will the Tuya App be compatible with Homey Bridge?

**Comment by JohanBendz** [comment]
Hi @janv01, sorry for the late answer.
I have an update coming that supports the Bridge, but Athom have to approve it first. When this is done (given they will approve it) the app will support the bridge too.

**Comment by erbrauti** [comment]
Hi, got any feedback from Athom regarding approval for Homey Bridge?
