### ISSUE TITLE
problems with extension and fan addition

### ISSUE THREAD

**Issue by tobi8868** [JohanBendz/com.tuya.zigbee#126]
Hello.
I would have liked to have added a Wifi fan, and an extension, but I have not figured out how to do this.
My extension has 4 connectors, and 3 USB connectors. When I look in Tuya's own app, it says it's a Smart Power Strip.Is it possible that I can add those devices to Homey in the future? Then I will be very happy as I can delete Tuya's own app.Thanks in advance.
Sincerely.
Tobias.

**Comment by JohanBendz** [comment]
Hi @tobi8868. The Zigbee power strip is already supported by the app, try the test version of the app if it's not in the live version. If your device have a new "id" I might have to add some new data to the app. Best way to know is that you add your device as a generic Zigbee unit and have a look at the settings, it should tell you manufacturerName etc. Get back with this info and I can tell if it's supported or else I can add it.

Wifi devices are supported in the Tuya Cloud app by Jürgen.
