### ISSUE TITLE
Powerstrip socket 3 ports not switching individually 

### ISSUE THREAD

**Issue by jellelambers** [JohanBendz/com.tuya.zigbee#127]
The Lidl Powerstrip socket 3 ports not switching individually. When connected to the Lidl Zigbee hub all three ports can be switched individually. 

But when connected to Homey, when you press one of the three added buttons, all power ports switch.

Tested with the Lidl and Tuya zigbee Homey app. But same results. 

Does anyone have a suggestion?

**Comment by kb-net** [comment]
Hi,

is your Homey and the app up to date?

Mine is and I have 3 independent switches to control.

I had a problem earlier with a 4 relais card with Tuya Zigbee 3.0 and when contacted Homey with this problem they told me to Re-Upgrade the Homey by a special proces.
I can explain it here, but the best way is to contact them, i had a responce within 4 hours.
I had some problem doing the upgrade with Chrome, but with their support it went super...

Succes and please let us know how it went

**Comment by jellelambers** [comment]
Yes, homey and apps are up to date.I will contact homey !Thank you!Op 27 nov. 2021 13:03 schreef Paul ***@***.***>:
Hi,
is your Homey and the app up to date?
Mine is and I have 3 independent switches to control.
I had a problem earlier with a 4 relais card with Tuya Zigbee 3.0 and when contacted Homey with this problem they told me to Re-Upgrade the Homey by a special proces.
I can explain it here, but the best way is to contact them, i had a responce within 4 hours.
I had some problem doing the upgrade with Chrome, but with their support it went super...
Succes and please let us know how it went

**Comment by JohanBendz** [comment]
Hi @jellelambers, do you still have the problem?

**Comment by JohanBendz** [comment]
@jellelambers, if this still is a problem please ask to reopen this issue.

**Comment by martijnpieters** [comment]
@JohanBendz To me this is still a problem. The problem is described very well over here: https://github.com/Koenkk/zigbee2mqtt/issues/9564, and the PR with a similar fix is over here: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3967
