### ISSUE TITLE
4CH Zigbee Smart Lichtschakelaar Module Dc 5/12/32V RF433 Ontvangen 10A Relais Werken Met Alexa google Assistent Mqtt Tuya Smartthings: 1 relais only...

### ISSUE THREAD

**Issue by kb-net** [JohanBendz/com.tuya.zigbee#130]
Hi,

I'm new here and I have bought online the "4CH Zigbee Smart Lichtschakelaar Module Dc 5/12/32V RF433 Ontvangen 10A Relais Werken Met Alexa google Assistent Mqtt Tuya Smartthings" and now it only connects 1 relais to the Homey.

It should be compatible with Zigbee, Tuya, Tuya Smart, Tuya Smart Life, Zigbee2mqtt, zigbee 3.0.

I also see 2 switches that look the same: "Power Strip Socket 1/4" and they also only connect 1 relais.

How can help me or knows who can?

Paul,
Eindhoven,
The Netherlands

**Comment by kb-net** [comment]
Hi Johan,

i don't know if it is the same kind of product. I've bought it on AliExpress.
https://nl.aliexpress.com/item/1005003165707937.html?spm=a2g0s.12269583.0.0.4f6b52e9RAucNP
https://ae01.alicdn.com/kf/H9b4c546cba1c48f1ba9fcda979cf707aa/4CH-Zigbee-Smart-Lichtschakelaar-Module-Dc-5-12-32V-RF433-Ontvangen-10A-Relais-Werken-Met-Alexa.jpg

It's about the "4CH Zigbee Smart Lichtschakelaar Module Dc 5/12/32V RF433 Ontvangen 10A Relais Werken Met Alexa google Assistent Mqtt Tuya Smartthings" and now it only connects 1 relais to the Homey.

It should be compatible with Zigbee, Tuya, Tuya Smart, Tuya Smart Life, Zigbee2mqtt, zigbee 3.0.

I also see 2 switches that look the same: "Power Strip Socket 1/4" and they also only connect 1 relais.

Thanks,
Paul

**Comment by kb-net** [comment]
Hi Johan,

i've learnt more about the 4 relay PCB from AliExpress:


Onbekend Zigbee Apparaat (=Unknown Zigbee Device)

Property				Value
ID					411504a6-7fbf-471c-9342-f78762b1742d
Class				socket
Driver				homey:manager:vdevice — zigbeebasic
Ready				Yes
Available				Yes
Warning				No
Custom icon			No
			
Data			
Key					Value
token				"683a0128-f0e8-4419-950c-bbf2d45effb6"
			
Settings		
Key					Value
zb_product_id			"TS0004"
zb_manufacturer_name	"_TZ3000_excgg5kb"
energy_alwayson		false
energy_value_off		null
energy_value_on		null
			
Capabilities		
Capability			Type		Value		Edit value				Last Updated
onoff				boolean		null			[true/false] (=selection)		(none)



I hope U can use my info to make this PCB working with the Tuya Zigbee App for Homey, or contact me: nieuwsbrief@kb-net.nl

Thanks,
Paul

**Comment by kb-net** [comment]
Sorry,

i don't know how I closed it. Was not my intension...

So I hope U can help me with this problem, and maybe many more...

Thanks, 
Paul

**Comment by JohanBendz** [comment]
Added to next release.
