### ISSUE TITLE
1 Gang Gimmer  - TS110E / _TZ3210_ngqk6jia not working

### ISSUE THREAD

**Issue by JohanBendz** [JohanBendz/com.tuya.zigbee#144]
https://community.homey.app/t/app-pro-tuya-zigbee-app/26439/1897

**Comment by JohanBendz** [comment]
And here is driver I created that works at least for on/off (not dimming) - Google Drive: Sign-in

Not sure how to get diagnostic report? Can you point me in right direction?

BTW, here is a discussion about the same device for another platform: Zigbee Model TS110E Zigbee Manufacturer _TZ3210_ngqk6jia · Issue #9878 · Koenkk/zigbee2mqtt · GitHub

**Comment by PiTRiS87** [comment]
Updated to latest version, on/off works, same as with the change I did, but not dimming

**Comment by PiTRiS87** [comment]
@JohanBendz is it possible to reopen, as it's still not working fully? Do you need some more info about the device?

**Comment by PiTRiS87** [comment]
@JohanBendz reminder, please :D
