### ISSUE TITLE
Woox R7060 Smart Garden Irrigation Control / Woox _TZ3210_eymunffl TS0101 - battery level missing

### ISSUE THREAD

**Issue by shaarkys** [JohanBendz/com.tuya.zigbee#147]
Hi Johan,
I commented in closed thread but not sure if you get notified... can you please also add batteryPercentageRemaining to the device ?
Fully charged battery showed value 198 (200?), now after year it shows 170 - it's clearly not percentage but maybe there is some simple way ?

https://github.com/JohanBendz/com.tuya.zigbee/issues/86#issuecomment-1008359654

Thank you.

**Comment by JohanBendz** [comment]
Hi there @shaarkys, is this still an issue?

**Comment by shaarkys** [comment]
Hi @JohanBendz , it's OKay, I'm using my own fork - https://github.com/JohanBendz/com.tuya.zigbee/pull/744#issuecomment-1944490121 - but you would need to cherry pick what you require, not so experienced in GitHUB.
But all those implementation in that pull requests are working fine for me so far.
