### ISSUE TITLE
TZ3000_w0qqde0g	TS011F Recognised like generic zigbee device

### ISSUE THREAD

**Issue by sinnamoragtb** [JohanBendz/com.tuya.zigbee#148]
When I add TZ3000_w0qqde0g | TS011F Smart plug with energy meter it is added like a generic zigbee device in homey. I have got the v. 0.1.45 on homey repository. How can I install the ultimate version? Will you update also the homey repository sooner or later?

**Comment by JohanBendz** [comment]
Added to test version
