### ISSUE TITLE
Tuya Powerplug TS011F with metering not recognized

### ISSUE THREAD

**Issue by erwinjong** [JohanBendz/com.tuya.zigbee#154]
hello,
It looks like the TS0011F is supported according to changelog 0.2.2 but mine does not get recognized.

Producent ID:_TZ3000_gjnozsaz
Product ID: TS011F

Is it not supported (yet) or is there is difference so it is not recognized ?

Thanks in advance.

0.2.2
Added metering capability to _TZ3000_mraovvmm / TS011F (Blitzwolf)

**Comment by erwinjong** [comment]
[TS011F _TZ3000_gjnozsaz interview.txt](https://github.com/JohanBendz/com.tuya.zigbee/files/7918449/TS011F._TZ3000_gjnozsaz.interview.txt)

added interview of device as mentioned on https://community.homey.app/t/app-pro-tuya-zigbee-app/26439

**Comment by erwinjong** [comment]
bought on Aliexpress

https://nl.aliexpress.com/item/1005003446740203.html?gatewayAdapt=glo2nld&spm=a2g0o.9042311.0.0.4f1d4c4dhAMBcZ

**Comment by JohanBendz** [comment]
Added to next test release

**Comment by kb-net** [comment]
Johan,

i now see it's the samen as I have posted

**Comment by kb-net** [comment]
Hi Johan,

when is the next (test) release ?
Because I installed the Experimental app again and still no power meter on it...

Thanks,
Paul
