### ISSUE TITLE
_TZ3000_fccpjz5z / TS130F does not get paired

### ISSUE THREAD

**Issue by ruben375** [JohanBendz/com.tuya.zigbee#169]
I try to add this curtain module which is supposed to be supported by the tuya app. It gets paired only as simple device.

Does anyone have an idea to get this paired and working with Homey pro?

Thx!

**Comment by JohanBendz** [comment]
Hi @ruben375, it's added to the test version of the app. Will be in next version of the live.
https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by ruben375** [comment]
@JohanBendz 
Will you add the end point setting feature as well? Actually in the test app it works only for up/down switching.
