### ISSUE TITLE
3 gang wall switch errors

### ISSUE THREAD

**Issue by ghost** [JohanBendz/com.tuya.zigbee#172]
Hi @JohanBendz - great work you have done with Tuya integration!

I wanted to help you with another device and I added new device to the drivers code for wall_switch_3_gang like below. The app was compiled properly, wall switch was discovered in homey app and new icon was created for each button. Unfortunately, few second later I received many error messages and non of the buttons worked. I'm attaching below the logs from this testing and I would appreciate if you could advise or investigate the issue.

driver.compose.json file
`...
      "zigbee": {
      "manufacturerName": [
        "_TYZB01_xiuox57i",
        "_TYZB01_b8cr31hp",
        "_TZ3000_wyhuocal",
        "_TZ3000_cdamjqm9",
        "_TYZB01_mqel1whf",
        "_TZ3000_hlwm8e96",
        "_TZ3000_odzoiovu",
        "_TZE200_tz32mtza"
      ],
      "productId": [
        "TS0003",
        "TS0013",
        "TS0043",
        "TS0601"
      ],
...`

Logs below:
`─────────────── Logging stdout & stderr ───────────────
[log] 2022-03-14 18:29:03 [tuyazigbee] Tuya Zigbee app is running...
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] ZigBeeDevice has been initialized { firstInit: true, isSubDevice: false }
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] ------------------------------------------
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] Node: 9b335f43-a9ee-4b8e-b418-3d3bbe25bc4e
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] - Receive when idle: false
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] - Endpoints: 1
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] --- basic
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] - Endpoints: 2
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] - Endpoints: 3
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] ------------------------------------------
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] Device data:  undefined
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 1)
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 1)
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] ZigBeeDevice has been initialized { firstInit: true, isSubDevice: true }
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] ------------------------------------------
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] Node: 9b335f43-a9ee-4b8e-b418-3d3bbe25bc4e
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] - Receive when idle: false
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] - Endpoints: 1
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] --- basic
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] - Endpoints: 2
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] - Endpoints: 3
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] ------------------------------------------
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] Device data:  secondSwitch
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 2)
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 2)
2022-03-14T18:29:32.411Z zigbee-clusters:cluster ep: 1, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:32.423Z zigbee-clusters:cluster ep: 1, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 1
}
2022-03-14T18:29:32.439Z zigbee-clusters:cluster ep: 1, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:32.441Z zigbee-clusters:cluster ep: 1, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 2
}
2022-03-14T18:29:32.483Z zigbee-clusters:cluster ep: 2, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:32.484Z zigbee-clusters:cluster ep: 2, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 1
}
2022-03-14T18:29:32.488Z zigbee-clusters:cluster ep: 2, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:32.489Z zigbee-clusters:cluster ep: 2, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 2
}
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] ZigBeeDevice has been initialized { firstInit: true, isSubDevice: true }
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] ------------------------------------------
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] Node: 9b335f43-a9ee-4b8e-b418-3d3bbe25bc4e
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] - Receive when idle: false
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] - Endpoints: 1
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] --- basic
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] - Endpoints: 2
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] - Endpoints: 3
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] -- Clusters:
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] --- onOff
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] ------------------------------------------
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] Device data:  thirdSwitch
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 3)
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:194ff893-2eef-4f35-8f68-a69e7e40ae30] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 3)
2022-03-14T18:29:32.788Z zigbee-clusters:cluster ep: 3, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:32.790Z zigbee-clusters:cluster ep: 3, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 1
}
2022-03-14T18:29:32.794Z zigbee-clusters:cluster ep: 3, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:32.795Z zigbee-clusters:cluster ep: 3, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 2
}
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 1) → parsed result null
2022-03-14T18:29:32.846Z zigbee-clusters:cluster ep: 1, cl: onOff (6) received frame readAttributesStructured.response onOff.readAttributesStructured.response {
  attributes: <Buffer 00 00 86>
}
2022-03-14T18:29:32.853Z zigbee-clusters:cluster ep: 1, cl: onOff (6) read attributes result { attributes: <Buffer 00 00 86> }
2022-03-14T18:29:32.967Z zigbee-clusters:cluster ep: 1, cl: onOff (6) received frame readAttributesStructured.response onOff.readAttributesStructured.response {
  attributes: <Buffer 00 00 86>
}
2022-03-14T18:29:32.971Z zigbee-clusters:cluster ep: 1, cl: onOff (6) read attributes result { attributes: <Buffer 00 00 86> }
[log] 2022-03-14 18:29:32 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:7a8d30ff-4247-46c6-935a-7913e2bb46e2] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 1) → parsed result null
2022-03-14T18:29:34.956Z zigbee-clusters:cluster ep: 1, cl: basic (0) received frame reportAttributes basic.reportAttributes {
  attributes: <Buffer 01 00 20 44 e2 ff 20 1f e4 ff 20 00>
}
2022-03-14T18:29:35.510Z zigbee-clusters:cluster ep: 1, cl: basic (0) received frame reportAttributes basic.reportAttributes {
  attributes: <Buffer df ff 42 0f 00 00 00 00 13 00 00 00 00 12 00 00 00 00 12>
}
2022-03-14T18:29:35.633Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 57, dstEndpoint: 1, timestamp: 4569483 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 20,
    cmdId: 1,
    data: <Buffer 01 96 01 01 00 01 01>
  }
}
2022-03-14T18:29:35.760Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4569878 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 21,
    cmdId: 1,
    data: <Buffer 01 97 02 01 00 01 00>
  }
}
2022-03-14T18:29:35.876Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4570248 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 22,
    cmdId: 1,
    data: <Buffer 01 98 03 01 00 01 00>
  }
}
2022-03-14T18:29:36.008Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4570643 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 23,
    cmdId: 1,
    data: <Buffer 01 99 0e 04 00 01 00>
  }
}
2022-03-14T18:29:36.123Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4571016 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 24,
    cmdId: 1,
    data: <Buffer 01 9a 0f 04 00 01 02>
  }
}
2022-03-14T18:29:36.253Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 57, dstEndpoint: 1, timestamp: 4571426 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 25,
    cmdId: 1,
    data: <Buffer 01 9b 01 01 00 01 01>
  }
}
2022-03-14T18:29:36.375Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 57, dstEndpoint: 1, timestamp: 4571807 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 26,
    cmdId: 1,
    data: <Buffer 01 9c 02 01 00 01 00>
  }
}
2022-03-14T18:29:36.500Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4572197 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 27,
    cmdId: 1,
    data: <Buffer 01 9d 03 01 00 01 00>
  }
}
2022-03-14T18:29:36.629Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 57, dstEndpoint: 1, timestamp: 4572600 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 28,
    cmdId: 1,
    data: <Buffer 01 9e 0e 04 00 01 00>
  }
}
2022-03-14T18:29:36.744Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 57, dstEndpoint: 1, timestamp: 4572962 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 29,
    cmdId: 1,
    data: <Buffer 01 9f 0f 04 00 01 02>
  }
}
2022-03-14T18:29:36.865Z zigbee-clusters:endpoint ep: 1, cl: time (10), error while handling frame binding_unavailable {
  meta: { transId: 0, linkQuality: 57, dstEndpoint: 1, timestamp: 4573343 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [  ],
    trxSequenceNumber: 30,
    cmdId: 0,
    data: <Buffer 07 00>
  }
}
2022-03-14T18:29:39.911Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4582858 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient, disableDefaultResponse ],
    trxSequenceNumber: 31,
    cmdId: 36,
    data: <Buffer 01 96>
  }
}
[log] 2022-03-14 18:29:46 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] set onoff → false (cluster: onOff, endpoint: 2)
2022-03-14T18:29:46.713Z zigbee-clusters:cluster ep: 2, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [ 'clusterSpecific' ],
  data: <Buffer >,
  cmdId: 0,
  trxSequenceNumber: 3
}
[log] 2022-03-14 18:29:52 [ManagerDrivers] [Driver:wall_switch_3_gang] [Device:d95ea3bc-02ff-4acc-94ad-1c35b4a0f0d6] set onoff → true (cluster: onOff, endpoint: 2)
2022-03-14T18:29:52.679Z zigbee-clusters:cluster ep: 2, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [ 'clusterSpecific' ],
  data: <Buffer >,
  cmdId: 1,
  trxSequenceNumber: 4
}
2022-03-14T18:29:57.491Z zigbee-clusters:cluster ep: 2, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:57.495Z zigbee-clusters:cluster ep: 2, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 5
}
2022-03-14T18:29:57.505Z zigbee-clusters:cluster ep: 2, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:57.511Z zigbee-clusters:cluster ep: 2, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 6
}
2022-03-14T18:29:57.792Z zigbee-clusters:cluster ep: 3, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:57.794Z zigbee-clusters:cluster ep: 3, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 3
}
2022-03-14T18:29:57.800Z zigbee-clusters:cluster ep: 3, cl: onOff (6) read attributes [ 0 ]
2022-03-14T18:29:57.804Z zigbee-clusters:cluster ep: 3, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [],
  data: onOff.readAttributes { attributes: [ 0 ] },
  cmdId: 0,
  trxSequenceNumber: 4
}
2022-03-14T18:29:59.838Z zigbee-clusters:endpoint ep: 1, cl: undefined (61184), error while handling frame cluster_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 4645134 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 32,
    cmdId: 17,
    data: <Buffer 01 97 40>
  }
}
───────────────────────────────────────────────────────
✓ Uninstalling `com.tuya.zigbee`...
✓ Homey App `com.tuya.zigbee` successfully uninstalled`

**Comment by JohanBendz** [comment]
Hi @Pablo8NL, sorry for the late answer.
The device you try to add use the Tuya unique cluster 61184, devices that use this cluster can be a bitch to add as they need some special treatment. To have this unit work you will have to create a separate driver, you will not be able to just add the codes to any of the drivers already in place. I am working on adding support for this and many other devices like it.
