### ISSUE TITLE
SHP15 Blitzwolf

### ISSUE THREAD

**Issue by Chopper8** [JohanBendz/com.tuya.zigbee#174]
Could you add the SHP15 Blitzwolf? 

Let me know if you need the interview code. 

This one is half the price as the Blitzwolf, could you add this one as well? With metering. https://a.aliexpress.com/_vPmrPn

If yes, happy to make donation. Now I only can turn them on/off as an unknown zigbee device

**Comment by hannesmehr** [comment]
Same here, would be great if you add the SHP15.
