### ISSUE TITLE
Zemismart 6 Scene Switch

### ISSUE THREAD

**Issue by christhedj** [JohanBendz/com.tuya.zigbee#186]
Hi -
Please add support for the Zemismart 6 Scene Switch ZM-S06-ZM. Any info you need from me, let me know. Thanks.

**Comment by JohanBendz** [comment]
Hi @christhedj, please add it as a generic device and interview it using developer tools, then post the interview here. Thanks! :)

https://tools.developer.homey.app/tools/zigbee

**Comment by christhedj** [comment]
First time I've done this - hope I've done it right



  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_zqtiam4u"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          4,
          5,
          61184
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {},
          "groups": {},
          "scenes": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }

**Comment by christhedj** [comment]
Was this what you needed? Not rushing you, just making sure I'm not the one holding you up!
