### ISSUE TITLE
WOOX Smart Door/Window sensor

### ISSUE THREAD

**Issue by annekurver** [JohanBendz/com.tuya.zigbee#192]
I try to install the WOOX Smart Door/Window sensor. I have installed with the tuya zigbee app on my homey, but after installation I am not able to use it. I am not able to use the flow as described. And when I look in the tuya zigbee app there are no linked devices. 

The sensor is installed as unknown device. 

Can you help me?

**Comment by JohanBendz** [comment]
Hi @annekurver, I need to know the zigbee data for the device, you find it in the device settings.

**Comment by annekurver** [comment]
Hi,

I see

Producent ID: _TZ3000_cea5xugq
Product ID: TS0203

Hope this helps

Op 11 jul. 2022 om 20:03 heeft Johan Bendz ***@***.***> het volgende geschreven:

﻿

Hi @annekurver<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fannekurver&data=05%7C01%7C%7C7beb3a89458143053aa108da6367b43b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637931594297077450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LJy8LjGHYOGyE4ETisG%2Fl2c2pGrf0uAf0Y8kmugnlik%3D&reserved=0>, I need to know the zigbee data for the device, you find it in the device settings.
