### ISSUE TITLE
Temperatuur sensor is not working

### ISSUE THREAD

**Issue by bvdp02** [JohanBendz/com.tuya.zigbee#200]
€ 1,83  53％ Off | Tuya ZigBee Smart Temperature And Humidity Sensor Battery Powered ZigBee Smart Home Security Work With Alexa Google Home 2021
https://a.aliexpress.com/_veavW1

Can you make this for me?

**Comment by JohanBendz** [comment]
Hi @bvdp02, I need an interview of the device to be able to add it: https://community.homey.app/t/app-pro-tuya-zigbee-app/26439

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
