### ISSUE TITLE
ZigBee smoke alarm devices

### ISSUE THREAD

**Issue by dyandh** [JohanBendz/com.tuya.zigbee#201]
Hi Johan,
I am using Homey and several Zigbee devices to automate my home. I am using your Zigbee cloud interface and this is working great, thx for your work in this.

My question/request: as in Holland smoke alarms are getting obligated to be used in all houses, are you able to add them in your supported items?  I purchase the following device, which I was not able to configure in Homey:

https://a.aliexpress.com/_mskZZcq

Thanks for you help,
Dyan

**Comment by JohanBendz** [comment]
Hi @dyandh, I have not checked the forum (https://community.homey.app/t/app-pro-tuya-zigbee-app/26439) but unless you have already I will need an interview of the device to be able to add support for it.

**Comment by dyandh** [comment]
Hi Johan,
As I am not an IT developer or a Homey/Tuya expert, I am not sure how certain steps needs to be done. Let me give you the picture of my environment and what I want to accomplish:
- my Homey (Early2019 model) is now running v8.0.2. The Tuya Zigbee app I installed is v0.1.45
- I am using the Tuya cloud app v1.0.8 from Jurgen Heine to link the Tuya SmartLife environment to the Homey. The app is configured using the "Legacy and Official" mode. For this I created in the Tuya development environment a project and was able to add all devices in Tuya including aquiring the API access id an secret string
- I purchased and successfully added in Smartlife a ZigBee gateway. Using this gateway I am able to add several Zigbee switch devices and sensors in SmartLife. My preference is to define all ZigBee devices through this gateway so they are able to support each other in a mesh network.

My issues:
- I purchased LIDL door sensors. The detail for the door sensors are:
     - manufacturing: _TZ1800_ejwkn2h2
     - product ID: TY0203
I am able to setup the sensor on both directly in Homey or using the gateway in Smartlife. But if I define them on the gateway, I am not able to add then in Homey. In your list the item is included.
- I have the same issue with a Lidl motion sensor (_TZ1800_fcdjzz3s, TY0202), also on your list: can be both setup in either the gateway or Homey, but I am not able to sync from the gateway to Homey
- I purchased 2 smoke detectors:
     - manufacturing: _TZE200_ntcy3xu1
     - product ID: TS0601
Homey is not able to support this (Unknown Zigbee Device), in Smartlife the item is recognized correctly, but again I am not able to sync this to Homey. This model is not on your list, will you be able to add it?

Sorry for the long mail, I hope you will get a better understanding of my environment en issues. Let me know if you need more info to provide me some advice to solve them.

Thanks,
Dyan

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by xristiaan** [comment]
Hi Johan,

If you could add Tuya smoke sensors, that would be great; I think many people would really appreciate that. I can order a device from AliExpress and send you the interview protocol. I can do that through the interview button in the Zigbee tab at https://tools.developer.homey.app/tools/zigbee, right?

Chris

**Comment by WJGvdVelden** [comment]
The interview result on a 
- manufacturing: _TZE200_ntcy3xu1
- product ID: TS0601
is attached
[SmokeDetector.txt](https://github.com/JohanBendz/com.tuya.zigbee/files/10394023/SmokeDetector.txt)

**Comment by WJGvdVelden** [comment]
@JohanBendz 
As the _TZE200_ntcy3xu1 uses the Tuya specific cluster 61184, adding this specific smoke detector is quite a bit more complicated and requires a different driver. I've dived into some of your other drivers with this specific cluster, but the fine details on how to map the 61184 codes to the smoke_alarm capabilities is currently beyond me. 

The relevant dp-code for this specific device are (according to other sources in GitHub):
alarm : 1 (values: 0=detected, 1=clear, 2=tested)
tamper : 4 (values: 0/1)
battery state : 14 (values 0=25%, 1=50%, 2=90%)

If tried (by trial and error) to come up with a working device.js, but simply assiging the values of alarm (even as a boolean) and battery alert (<1) to alarm_smoke and alarm_battery doesn't work.

Some hints (maybe on how to assign the proper values to IASZone?) would be appreciated and I'll continue my trial and error...

Wim
