### ISSUE TITLE
LCD Temperatur and Humidity Sensor Tuya

### ISSUE THREAD

**Issue by AlRei263** [JohanBendz/com.tuya.zigbee#204]
I bought the LCD Temperatur and Humidity Sensor _TZ2000_a476raq2 TS0201 you mentioned in your list of the compatible products. Over all, the inclusion in the Homey-world fits very well. Only showing the Battery-status is not able. Would be very helpful for me, can you fix it? Many thanks in advance.

**Comment by JohanBendz** [comment]
Hi @AlRei263, can you please send a diagnostic report from the app. Mark it with your name (AIRei263)

**Comment by AlRei263** [comment]
Dear JohanBendz,

I think, this is the code you need?

7bd8de98-f69c-4e78-9d13-bfa56f1e547d

Thanks in advance, 
AlRei263




-------- Ursprüngliche Nachricht --------
Von: Johan Bendz ***@***.***>
Gesendet: 11. Juli 2022 19:33:33 MESZ
An: "JohanBendz/com.tuya.zigbee" ***@***.***>
CC: Albert Reicherzer ***@***.***>, Mention ***@***.***>
Betreff: Re: [JohanBendz/com.tuya.zigbee] LCD Temperatur and Humidity Sensor Tuya (Issue #204)

Hi @AlRei263, can you please send a diagnostic report from the app. Mark it with your name (AIRei263)
