### ISSUE TITLE
App Crashes, Routers are not working well in Zigbee mesh network

### ISSUE THREAD

**Issue by sossienl** [JohanBendz/com.tuya.zigbee#219]
I'm working with 0.2.3
Homey Pro on 8.0.3

My routers (6) that are Tuya devices (_TZ3000_gjnozsaz | TS011F) do not work properly.
sensors connected to them are 40-50% ok, but many times the trigger is not received by Homey.

Also the app, on Homey crashes every x hours. Not sure if the app is required to run actively to ensure the router functionality works, but just as an FYI

**Comment by JohanBendz** [comment]
Hi @sossienl, can you please send a crash report from the app when this happens next time. If it's you that have sent crash reports already they show nothing.. eg they are blank.. no errors for me to troubleshoot. Please do write your name (sossienl) in next report so I know it's your report.

The few crash reports (from other users) that have data in them all show connection errors, eg the devices are not online. Hard for me to know if this is an error.. if your report will show the same I would appreciate your help resolving this issue.

Regarding Zigbee network issues, those are almost always related to an faulty or weak power adapter, consider changing the one you use to one that can provide min 2.1A stable current.

**Comment by sossienl** [comment]
I've been out for a while. I'll check and report back. The app has NOT crashed anymore. But my network is still giving me issues. I'll FIRST see if a new power adapter with 2.1A solves the problem, but I do feel that ever since I've included TUYA routers, it's unstable

**Comment by sossienl** [comment]
I have replaced the power adapter and need to re-add several battery end devices that lost their connection in the last 14 days. I don't have yet a final response as I did this not even 24h ago. The app still is NOT crashing.
