### ISSUE TITLE
could you add the smartsocket BW-SHP13 Blitzwolf with product id “TS011F”

### ISSUE THREAD

**Issue by Derffie** [JohanBendz/com.tuya.zigbee#221]
Very happy user off tuya app in Homey but 2 devices are not recognized although I have some older ones working.
could you add the BW-SHP13 Zigbee 3.0 Blitzwolf with product id “TS011F”
I have 2 working with product id “TS0121”
Let me know if you need the interview code (and how to get that)
Now I only can turn them on/off as an unknown zigbee device

**Comment by brembootje** [comment]
Same issue here

**Comment by gebah** [comment]
Still no solution for the TS011F? It can only be switched on/off but it doesn't show power consumption. I use the Tuya Zigbee app.

**Comment by brembootje** [comment]
No solution yet. I'm wondering if Johan Bendz read this topic.

**Comment by miszterx** [comment]
Same for me. Tuya Zigbee app add my BW-SHP13 as general device, but power consumption was not recognized.

**Comment by JohanBendz** [comment]
If you still have issues with this device please create a new issue and add all the needed info as this one lacks the data I need to fix it.
