### ISSUE TITLE
Tuya smart plug energy monitoring not working

### ISSUE THREAD

**Issue by NevetsRek** [JohanBendz/com.tuya.zigbee#226]
Hey, got some Tuya smart plugs with energy monitoring, but Homey dont recognize them and add it as a generic device. Can you please add it in the app? 🙏🏻 

Model: Tuya BSD033

Producer ID: _TZ3000_kx0pris5
Product ID: TS011F

Thanks! 😁

**Comment by JohanBendz** [comment]
Added to next test release.
