### ISSUE TITLE
Are you planning on adding WIFI to this app aswell?

### ISSUE THREAD

**Issue by Norinvstor** [JohanBendz/com.tuya.zigbee#230]

**Comment by JohanBendz** [comment]
Hi @Norinvstor.
No, I will not add WiFi devices to this app. There is already an app for the WiFi units: https://homey.app/en-us/app/com.tuya.cloud/Tuya-cloud/

**Comment by Norinvstor** [comment]
Hi,

Thank you for the answer.

I have a Nedis Zigbee device that I can't connect with Homey. Will it help to buy the Tuya or Nedis Zigbee hub and connect that to Homey?
