### ISSUE TITLE
Nedis PIR Zigbee not working

### ISSUE THREAD

**Issue by Norinvstor** [JohanBendz/com.tuya.zigbee#232]
Hi,

Can you please look into post:
https://community.homey.app/t/app-pro-tuya-zigbee-app/26439/2791?u=tirrazo

This is unfortunately not working:
![image](https://user-images.githubusercontent.com/50654830/192094275-cceabd75-fa98-48bf-88f6-6793fc23570d.png)
![image](https://user-images.githubusercontent.com/50654830/192094280-70ebc3dc-c96f-4e59-93ed-4dab9a52ec79.png)

Regards

**Comment by Norinvstor** [comment]
I saw it was possible to add Zigbee devices through Homey itself.

Doing this with the sensor in the same room at the Homey makes no difference. So the distance is not a problem.
Also, it recognizes the device as soon as I put it in pairing mode, but it still says it is unsupported.

Interview result:

  "ids": {
    "modelId": "RH3040",
    "manufacturerName": "TUYATEC-bd5faf9p"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [
          0,
          1,
          3,
          1280
        ],
        "outputClusters": []
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 72
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "TUYATEC-bd5faf9p"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "RH3040"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": "20180512"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": [],
            "commandsReceived": [
              "factoryReset"
            ]
          },
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": [],
            "commandsReceived": []
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": [
              0
            ],
            "commandsReceived": [
              0,
              1
            ]
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "motionSensor"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 2,
                "name": "zoneStatus"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "00:00:00:00:00:00:00:00"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 255
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": [
              "zoneStatusChangeNotification",
              1
            ],
            "commandsReceived": [
              "zoneStatusChangeNotification"
            ]
          }
        },
        "bindings": {}
      }
    }
  }

**Comment by JohanBendz** [comment]
Hi, sorry for the late answer.
Please send a diagnostic report from the app after restarting Homey and then adding the device.

**Comment by Norinvstor** [comment]
Hi,

Thank you!

I have restarted Homey, reinstalled the app and added the sensor again through the test version of the app.

Here is the report number:
736e377f-f6dd-4966-92b7-56da0d868933

I can restart the app and for 1 minute it looks like it's working. Then, I get the picture below:

![image](https://user-images.githubusercontent.com/50654830/206114357-3a6b20de-9cbf-4a9a-93d0-0b958b854a90.png)

**Comment by glysnes** [comment]
Any news regarding this? This is still happening on the TEST version. Anything I can add here that will make it easier for you to look into?

**Comment by Norinvstor** [comment]
This is still not fixed. Haven't tried actually.

**Comment by JohanBendz** [comment]
(Hopefully) fixed in next release thanks to https://github.com/JohanBendz/com.tuya.zigbee/pull/627
