### ISSUE TITLE
0.2.4 release 3 hours ago

### ISSUE THREAD

**Issue by Tonlaar** [JohanBendz/com.tuya.zigbee#246]
Maybe not related but this morning all Zigbee devices connected via this app are  no longer accessible.

<img width="341" alt="1E26F459-FF96-47EE-BF4D-7C5B82D61B38" src="https://user-images.githubusercontent.com/17337146/205035954-5abe8e48-0ead-4d88-9f77-2c0f998a47b2.png">

**Comment by Hellosmarthome** [comment]
Same problem here. Using de test APP 0.2.4.

**Comment by JohanBendz** [comment]
@Tonlaar @DomoticaBlog, all? What kind of devices? Can you guys please send crash reports.

**Comment by JohanBendz** [comment]
Fixed in 0.2.5
