### ISSUE TITLE
Right app version?

### ISSUE THREAD

**Issue by AlRei263** [JohanBendz/com.tuya.zigbee#247]
Dear Johan,
Thank you so much for developing such a flexible and helpful app.
On my Homey there is installed the version 0.1.45. In the changelog I can read that there must be issued a version 0.2.4. 
I enabled the automatic Update but nothing happens to get the 0.2.4-version. What do I have to do to fix that?
Thank you in advance
Greetings, Albert

**Comment by JohanBendz** [comment]
Hi. You add /test behind the url to see the test version of an app, if there is one.
https://homey.app/en-us/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by AlRei263** [comment]
Dear Johan,
maybe I wrote it wrong. But it was not my problem to find the test-version. I did not find the latest NORMAL version, because under 
https://homey.app/de-de/app/com.tuya.zigbee/Tuya-Zigbee/
there is displayed the 0.1.45-Version. I think it is not so meant by you...
Best Regards,
Albert
