### ISSUE TITLE
Curtain module

### ISSUE THREAD

**Issue by CGEUREVIA** [JohanBendz/com.tuya.zigbee#248]
Hello,

I connected a ZIGBEE curtain modul (tuya QS-Zigbee-C01) to homey.
It is well recognized but when I ask to open or close the curtain,I get the message : could not get devise by id.
I remove and reinstall twice the modul, I stiill have the same results.
Is there something I can do to solve this issue ?

Thanks per advance for your advice

**Comment by JohanBendz** [comment]
Is this still an issue?

**Comment by CGEUREVIA** [comment]
Hello,
It's still an issue, but for our concern we are usinganother gateway to mange the curtain.
