### ISSUE TITLE
Temperature and humidity sensor

### ISSUE THREAD

**Issue by Harmbe** [JohanBendz/com.tuya.zigbee#251]
Hi Johan,

I bought the Tuya temperature sensor but after adding add in homey to the Tuya Zigbee app, it is installed as simple switch and I get the message “no homey device found, it has been added as unknown zigbee device. Any suggestions?

Harm

**Comment by JurgenJacobs76** [comment]
It seems almost every batch has another hardware ID.  If your specific ID isn't already supported in the test version you can interview the sensor using the developer mode you to get all the specific details and you can request that specific version to be added through https://community.homey.app/t/app-pro-tuya-zigbee-app.
