### ISSUE TITLE
Socket stripes

### ISSUE THREAD

**Issue by marko0703** [JohanBendz/com.tuya.zigbee#252]
Can you please help me in finding compatible 4 Socket stripes which will work with your App. There are multiple manufacturers but I don‘t know which ones would work with the Tuya Zigbee App. Thank you so much!

**Comment by JohanBendz** [comment]
Hi @marko0703, sorry for the late answer.
The ones you find at Lidl should be safe to buy. Else just tell med the zigbee info of the device, or better yet make an interview (Homey Developer Tools) and send me that info. and I will add support for it.
