### ISSUE TITLE
How to calibrate the curtain module?

### ISSUE THREAD

**Issue by Majebo** [JohanBendz/com.tuya.zigbee#253]
Hello community,

I recently got the tuya zigbee curtain module installed. But it is set on a percentage open and closed which does not match the curtain I have. Is there a way to calibrate the curtain module and how? 

Ps. I’m at beginner level in homey.

**Comment by JohanBendz** [comment]
Hi @Majebo, currently there is not. Working on it.

**Comment by Majebo** [comment]
Hi Johan, thx for your reply. Any idea when u think it will be ready?
Couple weeks or months? Then I don’t buy other modules.

Op za 4 mrt. 2023 om 00:30 schreef Johan Bendz ***@***.***>
