### ISSUE TITLE
Support for Nous

### ISSUE THREAD

**Issue by lmunck** [JohanBendz/com.tuya.zigbee#255]
I can’t get Nous, another rebranded version of Tuya Zigbee Power Plug with metering, to work with this app, so I’m assuming it needs to be added somewhere.

Let me know if I can help with that in any way:
https://www.amazon.de/dp/B0054PSH6K/ref=pe_27091401_487027711_TE_SCE_dp_1

**Comment by JohanBendz** [comment]
Hi there.
I need the manufacturerName (showing under the device settings) to be able to add it.

**Comment by lmunck** [comment]
Thank you, for taking the time. Here's the manufacturerID:

_TZ3000_2putqrmw

Will that work?

**Comment by JohanBendz** [comment]
I'll add it to the current driver in the new update of the test version, please let me know if it works.

**Comment by jvdmeulen** [comment]
It works
<img width="379" alt="Capture 2023-03-14 at 19 47 21@2x" src="https://user-images.githubusercontent.com/129403/225107018-5a08ca2b-466f-4514-80bf-3b8b75b5148d.png">

**Comment by lmunck** [comment]
How did you install it? I tried adding "/test" and press install, but nothing got installed. I seem to be able to only get the stable version :-(

**Comment by jvdmeulen** [comment]
i installed the app ( on my homey pro 2023 ) and when it didnt see my nous, i went on a search. Finally seeing that you can add /test/ after soms app-urls. Then i went to https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/  and installed the app  (try to be logged in and hit the 'install app' button.
Then i removed the zigbee device, and let it find/search gain. It then recorgnized the new device and i got the options in the screenshot.

**Comment by lmunck** [comment]
Works like a charm! Thank you
