### ISSUE TITLE
Missing support for smart plug with smart metering

### ISSUE THREAD

**Issue by AndersE-75** [JohanBendz/com.tuya.zigbee#258]
Hi, 
I purchased two different smart plugs from same site:
1. NEO ZigBee On Off Smart Metering Plug" from this site: 
https://hubitat-shop.eu/product/neo-zigbee-on-off-power-metering-plug/

2. RTX ZigBee On Off Smart Metering Plug
https://hubitat-shop.eu/product/rtx-zigbee-on-off-smart-metering-plug-2/

Is it possible to add support for the smart metering for Homey? When I add them the Tuya app won't recognice them and they are added as general devices without support of smart metering.

Manufacturer ID: _TZ3000_gjnozsaz

**Comment by PeterKawa** [comment]
please read 1st post: https://community.homey.app/t/app-pro-tuya-zigbee-app/26439?u=peter_kawa

**Comment by AndersE-75** [comment]
> 

Thanks Peter, I'll close this thread. I read in the comments it will be supported in next release.
