### ISSUE TITLE
Feedback on experimental version

### ISSUE THREAD

**Issue by austrier** [JohanBendz/com.tuya.zigbee#262]
Hello !
Last week I purchased several plugs with meter reading which were supposed to be Tuya plugs. Unfortunately I couldn't connect them to Homey, but luckily I found that You already added this brand to Your experimental version.
This version made me able to connect the plugs to homey and they worked fine.
Unfortunately after some hours homey is down and doesn't accept any commands.
I tried to find out the reason what caused this breakdown, and located the issue in Your app (v0.2.6 experimental)
How did I find out?
I just deactivated the Tuya app on my Homey and restarted Homey. Everything went fine again. I tested it twice and waited a whole day before activating the Tuya app again. After a couple of hours Homey was "dead" again.
I hope You can help because I purchased many plugs. ;-)

If You need any protocols from Homey I would be happy to send them to You. Please let me know which ones and where I can find them.

Thank You
Peter

P.S. I used English because all other entries are in English aswell. Your name lets me think that Your native language could be german; so if You prefer to talk in German, go ahead - I am Austrian. ;-)

**Comment by JohanBendz** [comment]
Hi @austrier, thanks for the report. I am aware of some issues with a few of the devices included in the test version. Can you please install the latest version (if you don't have already) and test a few devices you have attached. Then please send a diagnostic report from the Tuya app (you find this under the apps settings)

From Sweden :)

**Comment by austrier** [comment]
Hello Johan !

Thank You for Your reply.

Yes, I installed the most recent version  (test)

As mentioned before when I contacted You the app caused homey to stop working at all.
It seems as there was an issue with the zigbee network on my homey.
Meanwhile I re-installed the homey firmware and reseted the zigbee network. I had to connect all devices again and I managed to connect some IKEA bulbs which was not possible before.
On the other hand I couldn’t connect any “frient” devices and deinstalled this app.
Then I tried to install Your app again and so far it worked and did not cause homey to stop working

Though I still had issues with zigbee lamps from “innr” and after Your message that there might be some issues with certain devices I deinstalled Your tuya app. This reduced my issues a little bit but not completely
Today I will replace these innr lamps by IKEA bulbs which are working fine in other rooms. If this resolves my issues I will install Your app again.

I will keep You informed.

Kind regards
Peter


***@***.***
-------------------------------------------------------------------
manege.media ● Inh. Peter Lunacek
An der Sonnleithen 15/406 ● A-4020 Linz
Telefon: +43 660 321 0000 ● Email: ***@***.******@***.***>
Internet: www.manege.at<http://www.manege.at/> ● www.mediaseven.at<http://www.mediaseven.at/>
-------------------------------------------------------------------

Von: Johan Bendz ***@***.***>
Gesendet: Sonntag, 26. Februar 2023 19:01
An: JohanBendz/com.tuya.zigbee ***@***.***>
Cc: Peter Lunacek ***@***.***>; Mention ***@***.***>
Betreff: Re: [JohanBendz/com.tuya.zigbee] Feedback on experimental version (Issue #262)


Hi @austrier<https://github.com/austrier>, thanks for the report. I am aware of some issues with a few of the devices included in the test version. Can you please install the latest version (if you don't have already) and test a few devices you have attached. Then please send a diagnostic report from the Tuya app (you find this under the apps settings)

From Sweden :)
