### ISSUE TITLE
Tuya 3 and 4 Gang modules support

### ISSUE THREAD

**Issue by kb-net** [JohanBendz/com.tuya.zigbee#263]
Hi Johan,

can U put support for the Tuya (AliExpress) 3 and 4 gang switch modules in the app?

    "modelId": "TS0003",
    "manufacturerName": "_TZ3000_qcdqw8nf"
            "name": "manufacturerName",
                "value": "_TZ3000_qcdqw8nf"
 
This is for the 3-gang module, I don't have the 4-gang module (yet) in my possession.

Thanks,
Paul.
[3-Gang Tuya Switch Module.txt](https://github.com/JohanBendz/com.tuya.zigbee/files/10433346/3-Gang.Tuya.Switch.Module.txt)

**Comment by JohanBendz** [comment]
3 gang added to next release.
