### ISSUE TITLE
missing Capability Listener: onoff

### ISSUE THREAD

**Issue by FreBrake** [JohanBendz/com.tuya.zigbee#264]
Today I got a message from Homey when trying to control my smart socket via Tuya.

"missing Capability Listener: onoff"

Have rebooted the Homey and the App, and also checked that the smart socket is controllable via the Tuya app. All seems fine, but Homey is still not able to control the smart socket. 

App v1.1.22
<img width="544" alt="Skjermbilde 2023-01-17 kl  12 55 55" src="https://user-images.githubusercontent.com/122881323/212892826-171e97d9-3132-4b45-b006-f662ce28baf5.png">

**Comment by JohanBendz** [comment]
Hi @FreBrake, is this still an issue?
If so, can you please send me a crash report from the app after trying to use the device a few times.

// Johan

**Comment by JohanBendz** [comment]
Ping @FreBrake

**Comment by WhiteFrosT01** [comment]
I am suffering from this on my Homey with Tuya cloud plugin v1.1.23. I could help with diagnosing?
