### ISSUE TITLE
AUBESS ZigBee Smart Plug Socket EU 16A/20A With Power Monitor For Tuya

### ISSUE THREAD

**Issue by frode1814** [JohanBendz/com.tuya.zigbee#266]
Hi. I would like to get support for this plug:
Product ID: TS011F
Supplier ID: _TZ3000_hdopuwv6

**Comment by CyB0rgg** [comment]
@frode1814 if you know how to install the app from cli using `homey app install` you can add the support yourself by editing files from this repo / SDK3 branch. I have forked repo with my Zignito / Ajax Smart Plug added, so I could add it for you and then you can clone it and install. Up to you.

**Comment by JohanBendz** [comment]
Added to next update
