### ISSUE TITLE
Tuya zigbee lcd temperature/humidity sensor not working

### ISSUE THREAD

**Issue by DennisMeeki** [JohanBendz/com.tuya.zigbee#267]
Hi,

I am tryimg to install a tuya zigbee lcd temperature sensor. But it does add as a unknown device. 
![Screenshot_20230210_174324_Homey](https://user-images.githubusercontent.com/77803228/218148555-cbc419d8-2af0-47bc-ae48-a4abfb245255.jpg)

![20230210_174301](https://user-images.githubusercontent.com/77803228/218148601-971438b6-9fa4-4806-96bd-24a8f81c650d.jpg)

Any help welcome

Kinds regards,

Dennis

**Comment by JohanBendz** [comment]
Added to next update.
