### ISSUE TITLE
_TZN3000_cfnprab5 / TS011F

### ISSUE THREAD

**Issue by Grobaa** [JohanBendz/com.tuya.zigbee#287]
Is it possible to add this 4 socket power outlet to the compatible devices?

**Comment by Grobaa** [comment]
Duplicate

**Comment by JohanBendz** [comment]
Hi @Grobaa, are you sure the manufacturername is _TZN3000_cfnprab5 with the N after _TZ ?
I have already added _TZ3000_cfnprab5to the app since before.

**Comment by Grobaa** [comment]
Hi Johan
You are absolutely right. And I have managed to add it to my Homey. 
Thank you for doing a great job btw

**Comment by smart-home-dumb-user** [comment]
_TZ3000_cfnprab5 isnt being detected when trying to find a new device with Tuya Zigbee App
