### ISSUE TITLE
Door sensor not supported

### ISSUE THREAD

**Issue by STD078** [JohanBendz/com.tuya.zigbee#299]
I bought 4 sensors.
But tuya zigbee doesn't recconize them.
Canon this be fixed anyhow?
![Screenshot_20230428-172121_Homey](https://user-images.githubusercontent.com/125923664/235188975-8539e825-3e0c-4a4b-876f-e352be284101.jpg)
![Screenshot_20230428-172104_Homey](https://user-images.githubusercontent.com/125923664/235188980-d6b321d3-da58-45a5-b7fd-1a6e6d1c4469.jpg)
![20230428_170221](https://user-images.githubusercontent.com/125923664/235188984-962299fa-7a91-48db-b9b7-65a6165ccb7d.jpg)
![20230428_164140](https://user-images.githubusercontent.com/125923664/235188989-bf7f5034-5e2e-438d-928f-7c0953b08c62.jpg)

**Comment by seegersnl** [comment]
You have to do an interview of the sensor and paste the result here so that johan can add it to the app.

**Comment by STD078** [comment]
Problemen solved by using the test app.
