### ISSUE TITLE
Moes smart knob by tuya

### ISSUE THREAD

**Issue by m8marcus** [JohanBendz/com.tuya.zigbee#300]
hallo!

i tried to add via homeys zigbee but it‘s unknown device

tuya app also is missing this kind of device till now

greetings
marcus

**Comment by m8marcus** [comment]
i am new here trying to make homey better! i am not developer jfyi
thanks

**Comment by JohanBendz** [comment]
Hi @m8marcus, I need Zigbee information from the device to be able to add support for it. This one is however already requested by others. Closing the issue.

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
