### ISSUE TITLE
MOES temperature sensor

### ISSUE THREAD

**Issue by freshslo** [JohanBendz/com.tuya.zigbee#306]
Can you please add temperature sensor from MEOS and smoke detectors from AUBESS. 

Thank you.

**Comment by PepijnvdrVinne** [comment]
Hello, i have a Homey pro and a moes temprature and humidity sensor. Can you please add this?
![Uploading image.jpg…]()

**Comment by JohanBendz** [comment]
@freshslo, I am unable to add anything I know nothing about. Please add device information, including Zigbee manufacturername and product id in a new issue. Best is to add interview data.

**Comment by freshslo** [comment]
14561ebb-4871-425f-a14a-c28c9b245f7cSmoke sensorOn 18 Jun 2023, at 11:24, Johan Bendz ***@***.***> wrote:﻿
@freshslo, I am unable to add anything I know nothing about. Please add device information, including Zigbee manufacturername and product id in a new issue. Best is to add interview data.
