### ISSUE TITLE
Moes Zigbee Temprature Humidity Sensor

### ISSUE THREAD

**Issue by PepijnvdrVinne** [JohanBendz/com.tuya.zigbee#311]
Hello, 
Van you please add the Moes Zigbee Temprature Humidity Sensor?

Whenzou Nova New Energy Co LTD

See Photo for more informetion

kind regards Pepijn 
![IMG_6127](https://github.com/JohanBendz/com.tuya.zigbee/assets/135894473/5f8992d7-4604-41e6-8f86-b80ebd2cfabd)

**Comment by PepijnvdrVinne** [comment]
![Uploading IMG_6128.jpeg…]()

**Comment by RezaRose26** [comment]
I would like that too

**Comment by hsdmiranda** [comment]
+1
