### ISSUE TITLE
Temperature & Humidity Sensor Aubess 

### ISSUE THREAD

**Issue by Roessje** [JohanBendz/com.tuya.zigbee#312]
Van you make the Tuya Temperature & Humidity Sensor from aubess work ?

thanks

**Comment by JohanBendz** [comment]
Hi @Roessje, I can only add support for devices if I get the Zigbee data, they look standard but I don't know before I have the info. If you don't want to buy them before you know they will be supported I suggest contacting Aubess and ask them to send you the Zigbee device manufacturername and productid of each product.
