### ISSUE TITLE
Add support for _TZ3040_6ygjfyll (TS0202) motion sensor

### ISSUE THREAD

**Issue by pienne-be** [JohanBendz/com.tuya.zigbee#316]
"ids": {
    "modelId": "TS0202",
    "manufacturerName": "_TZ3040_6ygjfyll"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:79:e7:da:d8:d1",
    "modelId": "TS0202",
    "manufacturerName": "_TZ3040_6ygjfyll",
    "capabilities": {
      "type": "Buffer",
      "data": [
        128
      ]
    },
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 29037,
        "_reserved": 28,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          4,
          1280,
          0
        ],
        "outputClusters": [
          4,
          6,
          4096,
          25,
          10
        ]
      }
    ],
    "touchlinkGroupIds": [],
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {},
          "identify": {},
          "groups": {},
          "iasZone": {},
          "basic": {}
        },
        "bindings": {
          "groups": {},
          "onOff": {},
          "touchlink": {},
          "ota": {},
          "time": {}
        }
      }
    }
  }

**Comment by JohanBendz** [comment]
Added to next release
