### ISSUE TITLE
Soil sensor QT-07S TUYA

### ISSUE THREAD

**Issue by barendbigfoot** [JohanBendz/com.tuya.zigbee#319]
Hi, 

It would be great if you can add the soil sensor to the tuya-zigbee app for homey.

**Comment by barendbigfoot** [comment]
"ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_myd45weu"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:1b:da:6f:ee:3f",
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_myd45weu",
    "capabilities": {
      "type": "Buffer",
      "data": [
        128
      ]
    },
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 11103,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "touchlinkGroupIds": [],
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {},
          "basic": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }

**Comment by JohanBendz** [comment]
Added

**Comment by barendbigfoot** [comment]
Nice! When will it be released into the app? I can't find it

**Comment by AFishCalledFlipper** [comment]
I can't find the Soil Sensor in the app. On HP2023 the sensor is detected as unknown Zigbee device and you can't do anything with it.
Anymore update?
