### ISSUE TITLE
Will it work? Shown at AliExpress: Tuya zigbee finger bot.  THX!

### ISSUE THREAD

**Issue by haadeess** [JohanBendz/com.tuya.zigbee#320]
https://m.de.aliexpress.com/item/1005005622014199.html?src=google&src=google&albch=shopping&acnt=272-267-0231&slnk=&plac=&mtctp=&albbt=Google_7_shopping&gclsrc=aw.ds&albagn=888888&ds_e_adid=640946559336&ds_e_matchtype=&ds_e_device=m&ds_e_network=u&ds_e_product_group_id=1930099069838&ds_e_product_id=de1005005622014199&ds_e_product_merchant_id=107694812&ds_e_product_country=DE&ds_e_product_language=de&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&albcp=19235412643&albag=145186964380&isSmbAutoCall=false&needSmbHouyi=false&aff_fcid=d5cc9cab9efc4b298d9d23d06a685c35-1688098158955-09485-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=d5cc9cab9efc4b298d9d23d06a685c35-1688098158955-09485-UneMJZVf&terminal_id=a273d05a9740440e805f5b0598c16ddf&afSmartRedirect=y

**Comment by JohanBendz** [comment]
no idea.. I always need an interview..
