### ISSUE TITLE
Tuya smart signee garage door opener 

### ISSUE THREAD

**Issue by eirikwe** [JohanBendz/com.tuya.zigbee#322]
I have a Tuya garage door opener signee that I would love to get working in Homey. 
is that possible to accomplish?

https://www.aliexpress.com/item/1005003610757320.html

Hope this is possible. 
Eirik Eikeland

**Comment by JohanBendz** [comment]
Hi Eirik. Sorry for the late answer. It's possible but might need some work.
I need more info to be able to add support for a device, please start a new issue and add required information.
