### ISSUE TITLE
nedis smartlife wall switch

### ISSUE THREAD

**Issue by OleVag** [JohanBendz/com.tuya.zigbee#327]
![ZBWS40WT_P50](https://github.com/JohanBendz/com.tuya.zigbee/assets/139560191/1c2e4928-0662-4d98-b755-0ef127a08271)

pleace add support for nedis smartlife wall switch zigbee 3.0 4 button.
thanks

**Comment by JohanBendz** [comment]
Hi. I need more info to be able to add support for a device, please start a new issue and add required information.
