### ISSUE TITLE
Tuya Zigbee Water Leak Detector

### ISSUE THREAD

**Issue by AlbyMulder** [JohanBendz/com.tuya.zigbee#334]
Hi, is it possible to ad the Tuya Zigbee Water Leak Detector / Water level sensor ?  It would be nice. Thanks

https://www.amazon.com/Detection-Sensor-Support-Installed-Kitchen/dp/B07ZP3C2XK/ref=sr_1_17?crid=13Q77DSG8IJYG&keywords=tuya+zigbee+water+level+sensor&qid=1690988217&sprefix=tyua+zigbee+water+level+sensor%2Caps%2C163&sr=8-17

**Comment by JohanBendz** [comment]
Hi,
I need more info to be able to add support for a device. Looking at the link you provide the unit is a Wifi device and this app only supports Zigbee devices.

If you have a Zigbee unit, please start a new issue and add required information.
