### ISSUE TITLE
New app (V0.2.14) update results in a not working zigbee watervalve (TS0001)

### ISSUE THREAD

**Issue by pjmpessers** [JohanBendz/com.tuya.zigbee#349]
Great to see that your still active in maintaining the tuya zigbee app.

The latest test release V0.2.14 only my zigbee watervalve (TS0001 _TZ3000Z_iedbgyxt) does not work anymore.
I get the error log:"Could not get device by ID."

Could you fix it?

Thanks in advance.

P.S. I already did a app and homey pro 2023 restart.

**Comment by JohanBendz** [comment]
Should be fixed with latest release.

**Comment by pjmpessers** [comment]
Indeed V0.2.16 fixed the problem. Thanks for the fix.
