### ISSUE TITLE
New update broke NOUS Zigbee Plug connection 

### ISSUE THREAD

**Issue by RepairGuyDK** [JohanBendz/com.tuya.zigbee#350]
All. My NOUS Zigbee Plugs Are now offline with update 0.2.14 

🥲🥲

Model TZ3000

ID : TS011F

Diagnostic code : 4f9a1171-af09-47ef-b655-aaa2e5d89cf8

**Comment by Baumus** [comment]
Same problem with me: All nous smart plugs with metering throw the following error trying to switch them on/off: expected_cluster_id_number

**Comment by JohanBendz** [comment]
Fixed

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
