### ISSUE TITLE
problem with update 0.2.14 

### ISSUE THREAD

**Issue by MrFlash2023** [JohanBendz/com.tuya.zigbee#352]
All my NOUS devices is now unavaliable after update 0.2.14

1821eb6f-4246-4dda-b7a2-30c2f9aa22e9

**Comment by Baumus** [comment]
Same problem with me: All nous smart plugs with metering throw the following error trying to switch the on/off: expected_cluster_id_number

**Comment by JohanBendz** [comment]
Fixed
