### ISSUE TITLE
Latest update broke NOUS Zigbee Plug connection

### ISSUE THREAD

**Issue by RiseOlsen** [JohanBendz/com.tuya.zigbee#353]
Unfortunately all my NOUS Zigbee Plugs are now offline after update 0.2.14. 

4303fcc8-db69-4814-977f-6fc8e520604b

**Comment by hermanolsen** [comment]
Same thing happend to med. Hope the issue will be fixed soon

**Comment by jevvol** [comment]
Same problem

**Comment by Alibozis** [comment]
I've got the same problem :(

**Comment by Baumus** [comment]
Same problem with me: All nous smart plugs with metering throw the following error trying to switch them on/off: expected_cluster_id_number

**Comment by Zsoltt-dom** [comment]
Exact same problem hee.
expected_cluster_id_number

**Comment by RiseOlsen** [comment]
After Update 0.2.16 it work again 👍🏻

**Comment by Baumus** [comment]
Yeah, it's fixed - quick response, a big thank you!
