### ISSUE TITLE
Device Request - Radar sensor ceiling model - _TZE204_sxm7l9xa / TS0601

### ISSUE THREAD

**Issue by nides34** [JohanBendz/com.tuya.zigbee#357]
Hi,

Thanks for your great job!

I have the test version on my Homey Pro and saw that radar sensor : https://fr.aliexpress.com/item/1005005477612297.html has driver in your app.

I thought that ceiling mount and wall mount were similar in firmware but it doesn't seems to be.

Please check below informations about this device:

![IMG_20230909_185508](https://github.com/JohanBendz/com.tuya.zigbee/assets/138219752/8403d250-6ece-489f-8024-593563cc92eb)
![Screenshot_2023-09-09-18-54-29-779](https://github.com/JohanBendz/com.tuya.zigbee/assets/138219752/c31fa2a9-8aae-4204-9e32-0622310d9683)

Could you add this device to the driver list in your app? It would be wonderful :) 

Thanks a lot!

Brand: Loginovo
ManufacturerName: _TZE204_sxm7l9xé
Product ID: TS0601
Device ID: a4:c1:38:21:d0:d2:a3:62
Profile ID:
Interview : below
Image: https://ae01.alicdn.com/kf/S6b18bbdfc28944109bd0e16eb7eb460d7/Smart-Life-Zigbee-D-tecteur-de-Pr-sence-Humaine-Tuya-Wifi-MmWave-Radar-Capteur-de-Montion.jpg_640x640.jpg
Product Name: Human radar sensor

**Comment by nides34** [comment]
I forgot device interview, sorry!

Brand: Loginovo
ManufacturerName: _TZE204_sxm7l9xé
Product ID: TS0601
Device ID: a4:c1:38:21:d0:d2:a3:62
Profile ID:
Interview : below
Image: https://ae01.alicdn.com/kf/S6b18bbdfc28944109bd0e16eb7eb460d7/Smart-Life-Zigbee-D-tecteur-de-Pr-sence-Humaine-Tuya-Wifi-MmWave-Radar-Capteur-de-Montion.jpg_640x640.jpg
Product Name: Human radar sensor

`
  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_sxm7l9xa"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:21:d0:d2:a3:62",
    "networkAddress": 27636,
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_sxm7l9xa",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 27636,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 27636,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 74
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE204_sxm7l9xa"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }`

**Comment by shaarkys** [comment]
Just a comment, with _TZE204_sxm7l9xa it's also ZY-M100-S

    ZY-M100-S: ZigBee based, wall-mounted version
    ZY-M100-L: ZigBee based, ceiling-mounted version

![obrazek](https://github.com/JohanBendz/com.tuya.zigbee/assets/14859895/ec72249f-6e71-4625-b725-dd3577131669)

**Comment by nides34** [comment]
@shaarkys not recognized by my homey with latest test version unfortunately, this is why I opened this topic 😉

**Comment by shaarkys** [comment]
Yep I know, just saying, it looks like with the same Manufacturer / ModelID, it looks like there are two different products (eg. could be confusing for pairing for some users)

**Comment by powermarcel10** [comment]
Any news on this one? Frustrating that the device is added allready, but just not with this manufacturer..

**Comment by shaarkys** [comment]
FYI, it has been added in the most recent version, unfortunately reports only Lx @JohanBendz 
Diag : 3c072755-96be-43dc-a16c-66610752c5dc

Just in case, actual interview : 

`
  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_sxm7l9xa"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:d7:d3:26:58:b2",
    "networkAddress": 10606,
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_sxm7l9xa",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 10606,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 10606,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 74
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE204_sxm7l9xa"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }
`

**Comment by shaarkys** [comment]
@JohanBendz possibly interesting and related conversation for _TZE204_sxm7l9xa : 

        tuyaDatapoints: [
                [105, 'presence', tuya.valueConverter.trueFalse1],
                [104, 'illuminance_lux', tuya.valueConverter.raw],
                [106, 'radar_sensitivity', tuya.valueConverter.raw],
                [109, 'distance', tuya.valueConverter.divideBy100],
                [110, 'fading_time', tuya.valueConverter.divideBy10],
                [107, 'far_detection', tuya.valueConverter.divideBy100],
                [108, 'near_detection', tuya.valueConverter.divideBy100],
                [111, 'detection_delay', tuya.valueConverter.divideBy10],
            ]

https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#_3-understanding-tuya-datapoints

https://github.com/Koenkk/zigbee2mqtt/issues/17483

Probably nothing you don't know already...

**Comment by powermarcel10** [comment]
Same problem here. Only reporting lux. @JohanBendz is this something you can fix?

**Comment by shaarkys** [comment]
I have fix already, working on update...

**Comment by powermarcel10** [comment]
> I have fix already, working on update...

Thats great! Thanks

**Comment by shaarkys** [comment]
@powermarcel10  @nides34 FYI - https://github.com/JohanBendz/com.tuya.zigbee/pull/744

**Comment by nides34** [comment]
> Same problem here. Only reporting lux. @JohanBendz is this something you can fix?

Same problem here.

Thanks @shaarkys waiting for your upcoming update and your researches to resolve🙂👍

**Comment by nides34** [comment]
Hi @shaarkys , @JohanBendz 

Do you found any solution to fix radar sensor occupancy state?

Thanks :)

**Comment by shaarkys** [comment]
I'm using it since my last update... you can either perform CLI install of my fork or wait for Johan :-)

**Comment by nides34** [comment]
Thanks for your reply :)

I don't know how to perform this CLI install :(

**Comment by nides34** [comment]
I found the way ; but got an error with ac206c8 version:

Command failed: npm ls --parseable --all --only=prod
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
npm ERR! code ELSPROBLEMS
npm ERR! extraneous: almost-equal@1.1.0 D:\tuya\node_modules\almost-equal
npm ERR! extraneous: hsluv@0.0.3 D:\tuya\node_modules\hsluv
npm ERR! extraneous: mumath@3.3.4 D:\tuya\node_modules\mumath
npm ERR! invalid: color-space@2.0.1 D:\tuya\node_modules\color-space

I thinks I'll wait Johan official update to avoid any crash :)

**Comment by shaarkys** [comment]
https://community.homey.app/t/how-to-cli-install-method/198
Also prior` homey app install` run `npm install` in the directory, where you downloaded and unpacked version, which you can take from : https://github.com/shaarkys/com.tuya.zigbee  ... or, simply wait ;-) johan is working on major update, eg. latest update 4 days ago.

**Comment by nides34** [comment]
That's great! Missing npm install before, now that's good, thanks for you perfect help!

I will test that this everning when I'll be back home :)

**Comment by nides34** [comment]
Perfect, it runs! Many many thanks!

**Comment by powermarcel10** [comment]
@JohanBendz Can you please add this to the app?
