### ISSUE TITLE
Bug report - [Blitzwolf bw-shp13

### ISSUE THREAD

**Issue by mfkess81** [JohanBendz/com.tuya.zigbee#367]
**Describe the bug**

**To Reproduce**
1. Go to 'device'
2. Click on 'on/off'

**Expected behavior**

Can't add existing blitzwolf bw-shp13 plug anymore. It is saying can add because of no reacting of the device. Also a few exiting devices are doing nothing when you push the on or off button. After a White you see a sort of time-out reacting.

**App and Homey version**
What Homey version are you running? Homey pro 2019
What version of Homey firmware do you use? 10.0.1
What version of the Tuya Zigbee App are you using?v0.1.45

**Screenshots**

**Additional context**

**Comment by JohanBendz** [comment]
Hi @mfkess81, try this version of the app: https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by mfkess81** [comment]
Johan,

I tried the test version V0.2.16. But still the same problem. When i'm adding the plug he is attaching the device. But after a while i get a reaction from homey. That the device is not responding.

Kind regards,
Martijn
________________________________
Van: Johan Bendz ***@***.***>
Verzonden: vrijdag 15 september 2023 14:33
Aan: JohanBendz/com.tuya.zigbee ***@***.***>
CC: mfkess81 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [JohanBendz/com.tuya.zigbee] Bug report - [Blitzwolf bw-shp13 (Issue #367)


Hi @mfkess81<https://github.com/mfkess81>, try this version of the app: https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by JohanBendz** [comment]
I think this has been solved, please let me know if you still have issues with the device.
