### ISSUE TITLE
Device Request - Temperature & Humidity Sensor - AUBESS _TZ3000_xr3htd96 / TS0201

### ISSUE THREAD

**Issue by Sufkonijn** [JohanBendz/com.tuya.zigbee#371]
Hi Johan,

can you please add this device to the app?

    Brand: AUBESS
    ManufacturerName: Zhenzen
    Product ID: TS0201
    Device ID: _TZ3000_xr3htd96
    Profile ID:
    Interview:

  "ids": {
    "modelId": "TS0201",
    "manufacturerName": "_TZ3000_xr3htd96"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 770,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1026,
          1029,
          0
        ],
        "outputClusters": [
          3,
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "identify": {
            "attributes": []
          },
          "temperatureMeasurement": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "measuredValue",
                "value": 2697,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "minMeasuredValue",
                "value": 2648,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 2734,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "relativeHumidity": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "measuredValue",
                "value": 5830,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "minMeasuredValue",
                "value": 5830,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 6170,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 70
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_xr3htd96"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0201"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "identify": {
            "attributes": []
          },
          "ota": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 8
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 9
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }

[    Image](https://a.aliexpress.com/_mrKS4vs)

Best regards,

Sufkonijn

**Comment by testuser83** [comment]
Same :-)

**Comment by suussanne** [comment]
i think i have the same but my interview data seams diffferent
`“ids”: {
“modelId”: “TS0201”,
“manufacturerName”: “_TZ3000_xr3htd96”
},
“endpoints”: {
“ieeeAddress”: “a4:c1:38:08:27:6f:f7:57”,
“modelId”: “TS0201”,
“manufacturerName”: “_TZ3000_xr3htd96”,
“capabilities”: {
“type”: “Buffer”,
“data”: [
128
]
},
“endpointDescriptors”: [
{
“status”: “SUCCESS”,
“nwkAddrOfInterest”: 37982,
“_reserved”: 24,
“endpointId”: 1,
“applicationProfileId”: 260,
“applicationDeviceId”: 770,
“applicationDeviceVersion”: 0,
“_reserved1”: 1,
“inputClusters”: [
1,
3,
1026,
1029,
0
],
“outputClusters”: [
3,
25,
10
]
}
],
“touchlinkGroupIds”: ,
“extendedEndpointDescriptors”: {
“1”: {
“clusters”: {
“powerConfiguration”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 32,
“name”: “batteryVoltage”,
“value”: 25,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 33,
“name”: “batteryPercentageRemaining”,
“value”: 2,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 1,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
}
]
},
“identify”: {
“attributes”: 
},
“temperatureMeasurement”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“name”: “measuredValue”,
“value”: -1113,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 1,
“name”: “minMeasuredValue”,
“value”: -1876,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 2,
“name”: “maxMeasuredValue”,
“value”: 2299,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 2,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
}
]
},
“relativeHumidity”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“name”: “measuredValue”,
“value”: 4649,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 1,
“name”: “minMeasuredValue”,
“value”: 4335,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 2,
“name”: “maxMeasuredValue”,
“value”: 6118,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 2,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
}
]
},
“basic”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“name”: “zclVersion”,
“value”: 3
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 1,
“name”: “appVersion”,
“value”: 70
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 2,
“name”: “stackVersion”,
“value”: 0
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 3,
“name”: “hwVersion”,
“value”: 1
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 4,
“name”: “manufacturerName”,
“value”: “_TZ3000_xr3htd96”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 5,
“name”: “modelId”,
“value”: “TS0201”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 6,
“name”: “dateCode”,
“value”: “”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 7,
“name”: “powerSource”,
“value”: “battery”
},
{
“acl”: [
“readable”,
“writable”,
“reportable”
],
“id”: 65502
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 2
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65534,
“name”: “attributeReportingStatus”,
“value”: “PENDING”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65506
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65507
}
]
}
},
“bindings”: {
“identify”: {
“attributes”: 
},
“ota”: {},
“time”: {
“attributes”: [
{
“acl”: [
“readable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 1
}
]
}
}
}
}
}
`

**Comment by D4204T5** [comment]
any updates about this sensor? also waiting for this one. :)

**Comment by bilellom** [comment]
no news...bad news?!? :-(
Please please add it.

**Comment by suussanne** [comment]
My sensor is working, thanks! 👍

**Comment by suussanne** [comment]
![IMG_5617](https://github.com/JohanBendz/com.tuya.zigbee/assets/139800200/3b7d04ac-7280-4408-a95c-e5621c7a3cfd)

**Comment by bilellom** [comment]
Hi, thank you for you reply, but for me is still not working...
The device seems to be the same : 
ID du fabricant : _TZ3000_xr3htd96
ID du produit : TS0201
Recevoir lorsque inactif : ⨯
Type d'appareil : enddevice
ID de l'appareil : a4:c1:38:ca:97:b3:34:df
Version du micrologiciel
Identifiants de groupe

Could you please help me?
If necessary, could you also tell me how I get the full product description (how do I interview data as shown in the previous posts?)
Thank in advance for you assistance

**Comment by bilellom** [comment]
Hi, I found the reason why it wasn't working for me: I was not running the test version (0.2.18 - https://homey.app/de-ch/app/com.tuya.zigbee/Tuya-Zigbee/test/) but the official released version of the app V0.1.45.
More info : https://community.homey.app/t/app-pro-tuya-zigbee-app/26439
Thanks

**Comment by Sufkonijn** [comment]
It works!!! Thanks Johan nice work!!!

**Comment by Sufkonijn** [comment]
Closed
