### ISSUE TITLE
2 Gang Switch Module

### ISSUE THREAD

**Issue by JohanBendz** [JohanBendz/com.tuya.zigbee#4]
Zemismart Switch DIY Breaker Module

https://nl.aliexpress.com/item/4001093548153.html?spm=a2g0o.productlist.0.0.13457af7G7ZTBT&algo_pvid=04b003e9-22ae-46bf-9773-bf68edeae307&algo_expid=04b003e9-22ae-46bf-9773-bf68edeae307-1&btsid=0ab6f81e15944663651576788e6ef3&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by HSA1963** [comment]
Because these modules are used for different purposes it would be nice to change the application from lamp, switch, fan and so on. Like it is for the plug

**Comment by JohanBendz** [comment]
Already added.
