### ISSUE TITLE
Device Request - Smoke Detector - _TZE200_ntcy3xu1 / TS0601

### ISSUE THREAD

**Issue by SamCan92** [JohanBendz/com.tuya.zigbee#431]
Device Name: _TZE200_ntcy3xu1
Device Model: TS0601
Device Description: Smoke Detector
Link to device image: https://ae01.alicdn.com/kf/U6bc841e8da194d0eb0ff1d756174bd16G/Tuya-Zigbee-Smoke-Detector-Home-Kitchen-Security-Safety-Prevention-Smoke-Sensor-Sound-Alarm-Work-With-Zigbee.jpg

Device Interview:

  "ids": {
    "modelId": "",
    "manufacturerName": "_TZE200_ntcy3xu1"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:35:53:4e:67:5f",
    "networkAddress": 31678,
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_ntcy3xu1",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 31678,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 72
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE200_ntcy3xu1"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }

Additional Comments:
Another Smoke Detector, which i've just got from ali.

**Comment by WJGvdVelden** [comment]
Would be great to have this one working.
Maybe this is helpfull. It is the debug information I get after having the device included in Homey:
dp 1 is Alarm state
dp 4 is Tamper Alert
dp 14 is Battery state

On Hubitat/Drivers/Tuya_Zigbee_Smoke_Detector/Tuya_Zigbee_Smoke_Detector.groovy
@kkossev
kkossev Tuya Zigbee Smoke Detector: ver. 1.0.2 2022-11-17 kkossev - (dev.bran…
a extensive code is available for Home Assistant


[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] ZigBeeDevice has been initialized { firstInit: true, isSubDevice: false }
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] ------------------------------------------
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] Node: 8d243e8f-d4d2-4c85-bc43-05992db29d06
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] - Receive when idle: false
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] - Endpoints: 1
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] -- Clusters:
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] --- basic
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] --- groups
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] --- scenes
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] --- tuya
[log] 2023-01-17 14:07:23 [ManagerDrivers] [Driver:smoke_sensor2] [Device:3e0f811f-050f-4b22-afec-0f3bdb5c2861] ------------------------------------------
2023-01-17T14:07:23.832Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 45,
  dp: 1,
  datatype: 4,
  length: 1,
  data: <Buffer 01>
}
2023-01-17T14:07:24.383Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 45,
  dp: 1,
  datatype: 4,
  length: 1,
  data: <Buffer 01>
}
2023-01-17T14:07:24.931Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 45,
  dp: 1,
  datatype: 4,
  length: 1,
  data: <Buffer 01>
}
2023-01-17T14:07:25.485Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 45,
  dp: 1,
  datatype: 4,
  length: 1,
  data: <Buffer 01>
}
2023-01-17T14:07:25.607Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 46,
  dp: 14,
  datatype: 4,
  length: 1,
  data: <Buffer 02>
}
2023-01-17T14:07:26.714Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 48,
  dp: 14,
  datatype: 4,
  length: 1,
  data: <Buffer 02>
}
2023-01-17T14:07:27.033Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) unknown command received: ZCLStandardHeader {
  frameControl: Bitmap [ clusterSpecific, directionToClient ],
  trxSequenceNumber: 224,
  cmdId: 17,
  data: <Buffer 00 26 40>
} { transId: 0, linkQuality: 55, dstEndpoint: 1, timestamp: 15849591 }
2023-01-17T14:07:27.039Z zigbee-clusters:endpoint ep: 1, cl: tuya (61184), error while handling frame unknown_command_received {
  meta: { transId: 0, linkQuality: 55, dstEndpoint: 1, timestamp: 15849591 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ clusterSpecific, directionToClient ],
    trxSequenceNumber: 224,
    cmdId: 17,
    data: <Buffer 00 26 40>
  }
}
2023-01-17T14:07:27.359Z zigbee-clusters:cluster ep: 1, cl: basic (0) received frame reportAttributes basic.reportAttributes {
  attributes: <Buffer 01 00 20 48 e2 ff 20 38 e4 ff 20 00>
}
2023-01-17T14:07:27.680Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 49,
  dp: 14,
  datatype: 4,
  length: 1,
  data: <Buffer 02>
}
2023-01-17T14:07:28.002Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 50,
  dp: 14,
  datatype: 4,
  length: 1,
  data: <Buffer 02>
}
2023-01-17T14:07:28.322Z zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 51,
  dp: 14,
  datatype: 4,
  length: 1,
  data: <Buffer 02>
}
2023-01-17T14:07:28.647Z zigbee-clusters:endpoint ep: 1, cl: time (10), error while handling frame binding_unavailable {
  meta: { transId: 0, linkQuality: 60, dstEndpoint: 1, timestamp: 15854631 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [  ],
    trxSequenceNumber: 229,
    cmdId: 0,
    data: <Buffer 07 00>
  }
}
2023-01-17T14:07:28.980Z zigbee-clusters:cluster ep: 1, cl: basic (0) received frame reportAttributes basic.reportAttributes {
  attributes: <Buffer df ff 42 3c 4e 01 00 00 69 91 00 00 00 12 9b 00 00 00 69 9c 00 00 00 69 9d 00 00 00 69 9e 00 00 00 69 a1 00 00 00 69 ac 00 00 00 69 b6 00 00 00 69 e4 ... 14 more bytes>
}
2023-01-17T14:07:34.500Z zigbee-clusters:cluster ep: 1, cl: basic (0) received frame reportAttributes basic.reportAttributes {
  attributes: <Buffer df ff 42 28 e7 00 00 00 69 e8 00 00 00 69 e9 00 00 00 69 f3 00 00 00 69 fd 00 00 00 69 2a 01 00 00 13 45 01 00 00 65 46 01 00 00 12>
}

**Comment by WJGvdVelden** [comment]
See pull request #481 for driver for this device.
Works fine for me.

**Comment by JohanBendz** [comment]
Added to next release
