### ISSUE TITLE
Device Request -Smart dimmer switch - MOES / ZS-SR-EUD

### ISSUE THREAD

**Issue by henkdeboom** [JohanBendz/com.tuya.zigbee#436]
SMART DIMMER SWITCH
Please add this switch to the Tuya Zigbee app.
Merk: MOES Model: ZS-SR-EUD
Website verkoper:
https://nl.aliexpress.com/item/1005005870551288.html?spm=a2g0o.order_list.order_list_mai n.5.4f1879d2Ko95DW&gatewayAdapt=glo2nld

   Interview:

 "ids": {
"modelId": "TS0601",
"manufacturerName": "_TZE204_zenj4lxv" },

"endpoints": {
"ieeeAddress": "a4:c1:38:8f:16:e9:b2:96", "networkAddress": 61100,
"modelId": "TS0601", "manufacturerName": "_TZE204_zenj4lxv", "endpointDescriptors": [
{
"status": "SUCCESS", "nwkAddrOfInterest": 61100, "_reserved": 20,
"endpointId": 1, "applicationProfileId": 260, "applicationDeviceId": 81, "applicationDeviceVersion": 0, "_reserved1": 1, "inputClusters": [
4,
5, 61184, 0
], "outputClusters": [
25,
10 ]
}, {
"status": "SUCCESS", "nwkAddrOfInterest": 61100, "_reserved": 10,
"endpointId": 242, "applicationProfileId": 41440, "applicationDeviceId": 97, "applicationDeviceVersion": 0, "_reserved1": 0, "inputClusters": [], "outputClusters": [
33 ]
} ],
"deviceType": "router", "receiveWhenIdle": true, "capabilities": {
"alternatePANCoordinator": false, "deviceType": true, "powerSourceMains": true, "receiveWhenIdle": true, "security": false, "allocateAddress": true

}, "extendedEndpointDescriptors": {
"1": { "clusters": {
"groups": { "attributes": [
{
"acl": [
"readable",
"reportable" ],
"id": 0,
"name": "nameSupport", "value": {
"type": "Buffer", "data": [
0 ]
}, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
}, {
"acl": [ "readable", "reportable"
],
"id": 65533,
"name": "clusterRevision", "value": 2, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
} ]
}, "scenes": {
"attributes": [ {
"acl": [ "readable", "reportable"
],
"id": 0, "reportingConfiguration": {
"status": "NOT_FOUND", "direction": "reported"

} },
{
"acl": [
"readable",
"reportable" ],
"id": 1, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
}, {
"acl": [ "readable", "reportable"
],
"id": 2, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
}, {
"acl": [ "readable", "reportable"
],
"id": 3, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
}, {
"acl": [ "readable", "reportable"
],
"id": 4, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
}, {
"acl": [ "readable", "reportable"

],
"id": 65533,
"name": "clusterRevision", "value": 2, "reportingConfiguration": {
"status": "NOT_FOUND",
"direction": "reported" }
} ]
}, "basic": {
"attributes": [ {
"acl": [ "readable", "reportable"
],
"id": 0,
"name": "zclVersion", "value": 3
}, {
"acl": [ "readable", "reportable"
],
"id": 1,
"name": "appVersion", "value": 74
}, {
"acl": [ "readable", "reportable"
],
"id": 2,
"name": "stackVersion", "value": 0
}, {
"acl": [ "readable", "reportable"
],
"id": 3,
"name": "hwVersion", "value": 1
}, {

"acl": [ "readable", "reportable"
],
"id": 4,
"name": "manufacturerName", "value": "_TZE204_zenj4lxv"
}, {
"acl": [ "readable", "reportable"
],
"id": 5,
"name": "modelId", "value": "TS0601"
}, {
"acl": [ "readable", "reportable"
],
"id": 6,
"name": "dateCode", "value": ""
}, {
"acl": [ "readable", "reportable"
],
"id": 7,
"name": "powerSource", "value": "mains"
}, {
"acl": [ "readable", "writable", "reportable"
],
"id": 65502 },
{
"acl": [
"readable",
"reportable" ],
"id": 65533,
"name": "clusterRevision",

"value": 2 },
{
"acl": [
"readable",
"reportable" ],
"id": 65534,
"name": "attributeReportingStatus", "value": "PENDING"
}, {
"acl": [ "readable", "reportable"
],
"id": 65506 },
{
"acl": [
"readable",
"reportable" ],
"id": 65507 }
] }
}, "bindings": {
"ota": {}, "time": {
"attributes": [ {
"acl": [ "readable"
],
"id": 65533,
"name": "clusterRevision", "value": 1
} ]
} }
}, "242": {
"clusters": {},
"bindings": {} }
} }

**Comment by henkdeboom** [comment]
In the latest version 0.2.18 this device is added but it is not working properly. Dimming level 100% in the app is about 60-70% of the level on the switch setting maximum.

**Comment by JohanBendz** [comment]
Hi @henkdeboom, is this still an issue? Have you tried interviewing the device? This is often enough to have Tuya units behave.
