### ISSUE TITLE
Since last Update Door Window Sensors are not working anymore

### ISSUE THREAD

**Issue by HSA1963** [JohanBendz/com.tuya.zigbee#437]
Since the last update de door window sensors aren't working anymore. I see the sensors transmitting because the led lit green when closing or opening the door but the status in het homey-app is not changing. When deprogramm the door window sensor and adding to another brand hub the sensor is working correct. Trying to prgramm back into the Homey is not possible anymore.

**App and Homey version**
Homey Pro (Early 2019)
Homey firmware 10.0.1
Tuya Zigbee App 1.45? I have tried 1.46 but that didn't solve the problem and cause even more problems

I see the apps in My Apps but not in settings below the account.

bugreportcode if this helps 7ae32387-7389-4bd2-b554-f6e93ee14c02

**Comment by HSA1963** [comment]
I have notice one other part. If I deprogramm an item which is working correct and wordt to reprogram it to the system it won't let you. I see on the device that there was a connection because blinking has stopped, The the next phase is starting and it says divice is not reacting any more so programming is stopped and divice is not added. To be shure connecting to an other Zigbee Hub (Tahoma) then it is working. So there is no problem with the devices.

**Comment by JohanBendz** [comment]
Hi @HSA1963, looking at the diagnostic report I only see a smart plug. The sensor is not initiated as a device by the Homey. Try repairing the device, if this does not help try removing it from Homey and add it again.

**Comment by HSA1963** [comment]
Hi John,Thank you for your reply. I have removed the sensor. It is now not possible to add the sensor again to the Homey system. I first deleted the sensor in the Homey. It is not in the system anymore. Putting the sensor back in programming and adding to the system. You see the sensor stopping with blinking and expect to be added. I have got the message the item is not responding anymore and sensor is not added. I have made two screenshots sorry that they are in DutchMvgr Hans ***@***.***+31642722607Op 28 sep. 2023 21:04 schreef Johan Bendz ***@***.***>:
Hi @HSA1963, looking at the diagnostic report I only see a smart plug. The sensor is not initiated by the device. Try repairing the device, if this does not help try removing it from Homey and add it again.

**Comment by HSA1963** [comment]
Johan Thanks for helping and your thinking it pushed me in the right direction. Problem solved. Basic Zigbee from Homey was corrupted. After a total software update Zigbee part was restored and could add new items and older items which did not reacted anymore started to react again.
