### ISSUE TITLE
NEO Zigbee

### ISSUE THREAD

**Issue by Bam44** [JohanBendz/com.tuya.zigbee#442]
**Describe the bug**
Think the added device is misspelled.

**Expected behavior**
Device will not be recogniced when trying to add it.

**App and Homey version**
What Homey version are you running? Pro (early 2019)
What version of Homey firmware do you use?  V 10.0.1
What version of the Tuya Zigbee App are you using? V 0.2.16

**Additional context**
I have seen that a deivice TS011F_TZ3000_gnjozsaz has been added. When I in earlier versions of the Tuya app got contact, the device name is TS011F_TZ3000_g**jn**ozsaz

**Comment by paulnas** [comment]
I have the same device and the same issue.

**Comment by JohanBendz** [comment]
Hi @Bam44 and @paulnas.
Both ID's are listed in the app and has been for quite a while.

Can you please interview your device and also send my a diagnostic report from the app.

(Other issue about the same problem: https://github.com/JohanBendz/com.tuya.zigbee/issues/445)

**Comment by paulnas** [comment]
Diagnostic report: 1b8808a8-efd4-4028-94dc-5c0a16e97150
Interview result was in #445 but here is another interview:

  "ids": {
    "modelId": "TS011F",
    "manufacturerName": "_TZ3000_gjnozsaz"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:33:43:12:87:28",
    "networkAddress": 47555,
    "modelId": "TS011F",
    "manufacturerName": "_TZ3000_gjnozsaz",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 47555,
        "_reserved": 30,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 266,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          3,
          4,
          5,
          6,
          1794,
          2820,
          57344,
          57345,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 47555,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "identify": {
            "attributes": []
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": true,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16385,
                "name": "onTime",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16386,
                "name": "offWaitTime",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32769,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32770,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 20480,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 32768,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "metering": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "currentSummationDelivered",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 512,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 768,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 771,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 774,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "electricalMeasurement": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1285,
                "name": "rmsVoltage",
                "value": 237,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1288,
                "name": "rmsCurrent",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1291,
                "name": "activePower",
                "value": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 77
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_gjnozsaz"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS011F"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

**Comment by paulnas** [comment]
@JohanBendz I have removed and re-added the device and now it correctly reports metering, with child lock and everything! 👍 Thanks for the help and the awesome app!

@Bam44 maybe also try removing and re-adding?

**Comment by Bam44** [comment]
Sorry, but I can't contact my devices thru the Tuya zigbee app in my Homey pro. I had ver 2.16, but after I deleted the app in Homey and reinstalled it, I just get ver 1.45 wich worked earlier. If I try again, the Homey says "Your app will  soon be installed ". How long is soon"?As I can't contact my device, I can't bring you the information you asking for. HELP!Regards Bengt Skickat från min Galaxy
-------- Originalmeddelande --------Från: Johan Bendz ***@***.***> Datum: 2023-10-01  22:16  (GMT+01:00) Till: "JohanBendz/com.tuya.zigbee" ***@***.***> Kopia: Bam44 ***@***.***>, Mention ***@***.***> Ämne: Re: [JohanBendz/com.tuya.zigbee] NEO Zigbee (Issue #442) 
Hi @Bam44 and @paulnas.
Both ID's are listed in the app and has been for quite a while.
Can you please interview your device and also send my a diagnostic report from the app.

**Comment by paulnas** [comment]
@Bam44 Installation is immediate, so you can use it right away. I'm on app version 0.2.17 which works fine. You don't have to remove the app, just the device (and then re-add it).

**Comment by JohanBendz** [comment]
Great to hear @paulnas, I'll keep this open for a while to let @Bam44 verify it's working.

**Comment by Bam44** [comment]
Don't work. Now got ver 0.2.18 of Tuya app and 10.0.1 of Homey pro (2016-2019).No reaction from Zigbee power plug with following data:Communication protocol: Zigbee 3.0Networking protocol: Zigbee IEEE 802.15.4Plug with metering bought via m.nuWhen trying to add device led flashig but time out after some minutes.Skickat från min Galaxy
-------- Originalmeddelande --------Från: Johan Bendz ***@***.***> Datum: 2023-10-02  23:52  (GMT+01:00) Till: "JohanBendz/com.tuya.zigbee" ***@***.***> Kopia: Bam44 ***@***.***>, Mention ***@***.***> Ämne: Re: [JohanBendz/com.tuya.zigbee] NEO Zigbee (Issue #442) 
Great to hear @paulnas, I'll keep this open for a while to let @Bam44 verify it's working.

**Comment by paulnas** [comment]
@Bam44 I'm not tech support, just a user such as yourself. But when your plug can't connect to the Homey, it's not a problem with the app but rather you don't have any connection to your Homey. Maybe the plug is too far away and you don't have any routers in between the Homey and the plug. So try to connect closer to the Homey. It should at least connect and show up as a generic Zigbee device, even without the right app installed. So the fact that it doesn't, means that you're too far away. For me it works perfectly, I have added the Ikea Trådfri signal amplifier to make sure the signal reaches the Homey and even though my Homey is on the ground floor and the plug is 2 floors up, they connect without issue because the signal amplifier sits in between. The app also works great, exposing all the capabilities of the plug. Thanks @JohanBendz, awesome app!

**Comment by Bam44** [comment]
Thank you for the advice @paulnas but it still doesn't work. I have been sitting just next to the Homey, and tried both with and without Bluetooth activated on my phone. The led on the smartplug is flashig but after a while I get a timeout message.The plugs did work until end of August. August 18 I have an update note at my timeline from Homey 8.1.6 to 10.0.0,  at September 8 I have got a note "Zigbee-unit _deviceName_ has left the network". I don't remeber if it was automatic or when I removed the smartplugs from Homey. After that I can't contact my smartplugs.Skickat från min Galaxy
-------- Originalmeddelande --------Från: paulnas ***@***.***> Datum: 2023-10-03  19:33  (GMT+01:00) Till: "JohanBendz/com.tuya.zigbee" ***@***.***> Kopia: Bam44 ***@***.***>, Mention ***@***.***> Ämne: Re: [JohanBendz/com.tuya.zigbee] NEO Zigbee (Issue #442) 
@Bam44 I'm not tech support, just a user such as yourself. But when your plug can't connect to the Homey, it's not a problem with the app but rather you don't have any connection to your Homey. Maybe the plug is too far away and you don't have any routers in between the Homey and the plug. So try to connect closer to the Homey. It should at least connect and show up as a generic Zigbee device, even without the right app installed. So the fact that it doesn't, means that you're too far away. For me it works perfectly, I have added the Ikea Trådfri signal amplifier to make sure the signal reaches the Homey and even though my Homey is on the ground floor and the plug is 2 floors up, they connect without issue because the signal amplifier sits in between. The app also works great, exposing all the capabilities of the plug. Thanks @JohanBendz, awesome app!

**Comment by Bam44** [comment]
Johan.


With the update to ver 0,2,18, I managed to reconnect one of my smart-plugs. It seems as it needed a factory reset and the manual for the plugs don’t properly show how to do the reset. I have to try to reset the other plugs later. Thank you for your effort to solve my problem.
MVH
Bengt

**Comment by FlyJJ1010** [comment]
Hi @Bam44,
Maybe it has nothing to do with it, but i was using a Neo Wall plug and Neo Door sensor since three years (not on a Homey, But Vera Controller) and both stoped working within a few weeks from eachother. The Plug was never able to connect again to the Vera nor the Homey. I was able to reconnect the door sensor on both but with huge battery drain (empty in 24 hours). So i think in both cases some hardware failure...

**Comment by Bam44** [comment]
Thank you, very helpful. I suspect same with my NEO smart power plugs with metering. I’ve been able to reconnect 1 of 7 units. Got one replaced as this was malfunction at the delivery, the button Led showed opposite as supposed, ON when relay was off and vice versa.


Manual says that after pressing the button (Led) for 5 to 7 seconds unit will be reset but I can’t get this to work. I’ll have to test a bit longer to be absolute sure.


Regards Bengt





Den 9 oktober 2023 15:46:50 +02:00, skrev FlyJJ1010 ***@***.***>:

**Comment by Bam44** [comment]
Hej. Har tidigare, 2023-27-09, anmält via Github #442 men aldrig fått de 7 uttagen från NEO att fungera. Har nu åter laddat ner Tuya Zigbee appen som sägs ha ver 0.1.45, men är osäker på om/när appen uppdateras. Kan inte se vilken version jag har installerad och kan inte heller få Homey att upptäcka mina enheter utan de blir installerade som okänd Zigbee-enhet.
Gäller powerplug 001SPB2 NEO
Produkt ID TS011F
Tillverkar ID _TZ3000_gjnozsaz

**Comment by paulnas** [comment]
> Hej. Har tidigare, 2023-27-09, anmält via Github #442 men aldrig fått de 7 uttagen från NEO att fungera. Har nu åter laddat ner Tuya Zigbee appen som sägs ha ver 0.1.45, men är osäker på om/när appen uppdateras. Kan inte se vilken version jag har installerad och kan inte heller få Homey att upptäcka mina enheter utan de blir installerade som okänd Zigbee-enhet. Gäller powerplug 001SPB2 NEO Produkt ID TS011F Tillverkar ID _TZ3000_gjnozsaz

I've had that working for ages. I have 4 of these exact power plugs and they work great. Not as generic devices but as supported Tuya Zigbee devices. I'm running the test version of the Tuya Zigbee app though, I'm currently at 0.2.73.

**Comment by Bam44** [comment]
Hi,
I've tried this 7 plugs of mine with no luck. My problem is that I had some version around 0.2.15 - 0.2.17 and they didn't work and my Homey Pro (2016-2019) crashed many times so I uninstalled the Tuya Zigbee app and Homey worked as intended. Before X-mas I found my old plugs and tried to install the app again and also tried to connect my wall plugs via Tuya app. I got the answer that there was no app available so the plugs was installed as ordinary Zigbee units but with no possibility to read power consumption among others.
Now in January I once again installed the Tuya Zigbee app and it still says ver 0.1.45. so I just inactivated the app, stillinstalled.
I wonder if there is a way to find out the actually version of my app or how I do to upgrade to latest version. Can I provide with some more information, please tell me.

MVH
Bengt


Den måndag 13 januari 2025 kl. 15:14:33 +01:00, skrev paulnas ***@***.***>:

**Comment by paulnas** [comment]
If you click on the gear icon on the web interface (lower left corner), you get - among other things - the list of apps installed on your Homey. Find the Tuya Zigbee app and then you will see the installed version. Mine says "v0.2.73 Test". If you are on 0.1.45 then you don't have the test version and I believe the regular version is somewhat behind with capabilities. 
The way to switch to the test version is to go to https://homey.app/a/com.tuya.zigbee/test and install from there. Everything you had (devices, flows) will still be there. But it might add your plugs as supported devices.

**Comment by Bam44** [comment]
Thank you.

Did it on my laptop and I still had ver. 0.1.45. I activated my installed version and then followed your instruction and got 0.2.73 Testa. Went to my Android phone and saw there is also ver 0.2.73 Testa. Confused I on my Android searched for the Tuya Zigbee app and found; it still offered me the ver 0.1.45.
I stoped there and tomorrrow I will test to remove one of the wallplug from the Zigbee and reinstall with Tuya Zigbee app ver 0.2.73.
It's obvious that there is a difference between Windows laptop and Android phone when it comes to install this app.

MVH
Bengt


Den måndag 13 januari 2025 kl. 20:13:22 +01:00, skrev paulnas ***@***.***>:

**Comment by Bam44** [comment]
Har skickat diagnostikrapport med följande kod 5cbcd5e9-1f0f-43ea-8a45-749963b9ef83. Bifogar skärmbild från app i mobil.

MVH
Bengt


Den måndag 13 januari 2025 kl. 20:13:22 +01:00, skrev paulnas ***@***.***>:

**Comment by Bam44** [comment]
Hej. När man startar om appen Tuya Zigbee i Homey, försvinner alla röda trianglarna vid varje enhet. Trots detta fungerar det inte att manövrera enheterna manuellt via appen, inte heller via flows.

MVH
Bengt



---------- Vidarebefordrat meddelande ----------
Från: Bengt Månsson ***@***.***>
Datum: 21 februari 2025 13:37:16 +01:00
Ämne: Re: [JohanBendz/com.tuya.zigbee] NEO Zigbee (Issue #442)
Till: JohanBendz/com.tuya.zigbee ***@***.***>

Har skickat diagnostikrapport med följande kod 5cbcd5e9-1f0f-43ea-8a45-749963b9ef83. Bifogar skärmbild från app i mobil.

MVH
Bengt


Den måndag 13 januari 2025 kl. 20:13:22 +01:00, skrev paulnas ***@***.***>:
