### ISSUE TITLE
Device Request - [Device name] - [manufacturerName] / [modelId]

### ISSUE THREAD

**Issue by remyxed** [JohanBendz/com.tuya.zigbee#443]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: Moes Smart ZigBee Scene Switch_Round Rotary Wireless Dimmer Light Switch
Device Model: TS004F
Device Description: Smart knob/button with click and rotation wheel
Link to device image: https://moeshouse.com/cdn/shop/products/tuya-zigbee-smart-knob-switch-wireless-scene-switch-button-scene-button-controller-battery-powered-automation-scenario-702143.jpg?v=1642167834&width=1206 

Additional Comments:
(https://moeshouse.com/products/zigbee-round-dimmer-scene-switch)

**Comment by JohanBendz** [comment]
Hi @remyxed 

The data I need is the information for the device, you provided your Homey data. (sensitive so I removed it).

**ManufacturerName = ?**
Device model = TS004F

**Comment by remyxed** [comment]
Oh my, I am new to this 😲 sorry and thanks for removing the sensitive stuff.

Manufactuer:     _TZ3000_qja6nq5z

From: Johan Bendz ***@***.***>
Date: Thursday, 28 September 2023 at 21:00
To: JohanBendz/com.tuya.zigbee ***@***.***>
Cc: Dirk Kuijt @ Remyxed ***@***.***>, Mention ***@***.***>
Subject: Re: [JohanBendz/com.tuya.zigbee] Device Request - [Device name] - [manufacturerName] / [modelId] (Issue #443)

Hi @remyxed<https://github.com/remyxed>

The data I need is the information for the device, you provided your Homey data. (sensitive so I removed it).

ManufacturerName = ?
Device model = TS004F
