### ISSUE TITLE
Wall Dimmer _TZE200_3p5ydos3 / TS0601 - Could not get device by id

### ISSUE THREAD

**Issue by TheElephant1979** [JohanBendz/com.tuya.zigbee#448]
**Describe the bug**
After pairing / installation (succesfull), i'm trying to switch the light on/off. This will not succeed as i get 'Could not get device by ID'.

**To Reproduce**
Install wall dimmer via Tuya Zigbee (or as generic device), try to switch on/off the light and this will not work.
You recently added this device so it is in test-phase. I did not work before.

**Expected behavior**
Light can be turned on/off, and the light is dimmable

**App and Homey version**
What Homey version are you running? 10.0.1
What version of Homey firmware do you use? 7.4.0.1310
What version of the Tuya Zigbee App are you using? test version 0.2.17

**Screenshots**
![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/13694640/2c7df24c-9fc0-4e7a-8420-39e8977d01b0)

**Additional context**
Wall Dimmer _TZE200_3p5ydos3 / TS0601

Hope that above info is sufficient.

**Comment by TheElephant1979** [comment]
@JohanBendz Same issue here (https://github.com/JohanBendz/com.tuya.zigbee/issues/354).
Tested this again in 0.2.17 and same result: Could not get device by ID.
I have created a bug for this here: https://github.com/JohanBendz/com.tuya.zigbee/issues/448

So there are some duplicates (sorry, second time here). I will try to close the others.

**Comment by TheElephant1979** [comment]
Hi @JohanBendz 

Tested in v0.2.18
- Able to add device to Homey
- Able to switch lights on/off
- Able to dimm

However they seemed to work correct, later in the evening when i tried to switch the light i got an error message saying: 'Apparaat is niet te bereiken'.

Quite strange as i was able to switch on/off and dimm. Anything i can do from this point on to provide you more info?

**Comment by Peter-Celica** [comment]
Hi @JohanBendz same issue here Johan it's still not working only occasionally.
Best regards Peter.

**Comment by JohanBendz** [comment]
@Peter-Celica @TheElephant1979
A new driver (no need to re-pair) is on it's way to the test version. Hope this will fix things.

**Comment by TheElephant1979** [comment]
Awesome! One addition; when switching the device physically the state isn't syncronized to Homey at the moment. Possible to provide a fix for that also?

Lot of updates lately 💪👍🏻

**Comment by Peter-Celica** [comment]
Hi Johan good morning 🌞,
Thanks for your effort and hopefully I will  receive my new Homey today, if
the packet service is on time and I'll let you know if everything is
working well now.

Have a nice day and best regards,
Peter.

Verzonden van mijn Xiaomi MI10 Lite 5G

Op zo 22 sep. 2024 22:01 schreef Johan Bendz ***@***.***>:

**Comment by TheElephant1979** [comment]
Works! 👍🏻

**Comment by JohanBendz** [comment]
Thanks for the update @TheElephant1979 
Good to hear everything works now 😀

**Comment by TheElephant1979** [comment]
> Thanks for the update @TheElephant1979 Good to hear everything works now 😀

You can buy an extra beer next weekend. Enjoy it. *MadeADonation* @JohanBendz
