### ISSUE TITLE
Device Request - Zemismart 24W Ceiling light - _TZ3210_mja6r5ix / TS0505B

### ISSUE THREAD

**Issue by SamCan92** [JohanBendz/com.tuya.zigbee#450]
Device Name: _TZ3210_mja6r5ix
Device Model: TS0505B
Device Description: Zemismart 24W Ceiling light (RGB CW WW)
Link to device image: https://i5.walmartimages.com/asr/f3ea021a-08c8-4a94-91a1-fb6a995a9b93.bcb2a47d5a7900da395b6fa36b4d63d2.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF

Device Interview:

  "ids": {
    "modelId": "TS0505B",
    "manufacturerName": "_TZ3210_mja6r5ix"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:ef:b6:2f:ae:5c",
    "networkAddress": 49368,
    "modelId": "TS0505B",
    "manufacturerName": "_TZ3210_mja6r5ix",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 49368,
        "_reserved": 36,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 269,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          6280,
          4,
          5,
          6,
          8,
          768,
          10,
          4096,
          65518
        ],
        "outputClusters": [
          25,
          4096,
          65518
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "z.1.0",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 112
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3210_mja6r5ix"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0505B"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "unknown"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled",
                "value": true
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId",
                "value": "z.1.0"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": true,
                "reportingConfiguration": {
                  "direction": "reported",
                  "attributeDataType": 0,
                  "minInterval": 0,
                  "maxInterval": 0,
                  "minChange": {
                    "result": null,
                    "length": 0
                  },
                  "status": "SUCCESS"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16387
              },
              {
                "acl": [
                  "reportable"
                ],
                "id": 61440
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "currentLevel",
                "value": 254,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 61440,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 17,
                "name": "onLevel",
                "value": 255
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 19,
                "name": "offTransitionTime",
                "value": 10
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "onTransitionTime",
                "value": 10
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16384
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "touchlink": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "ota": {}
        }
      }
    }
  }

Additional Comments:
Light can be controlled via Homey, but only colors can be choosen, Warm White / Cold White are not available, which makes it quite useless at the moment :)

**Comment by omBratteng** [comment]
Tagging along on this request, I've got a light bulb with the same manufacturer and model.
Adding details here as to not duplicate request.

Device Name: _TZ3210_mja6r5ix
Device Model: TS0505B
Device Description: Tuya E27 RGB+WW+CW Color Changing Led Bulb
Link to device image: https://ae01.alicdn.com/kf/S2380ec04afdc4859a69040196dfa10a39/18W-15W-Zigbee-3-0-Led-Light-bulb-RGB-WW-CW-E27-Wifi-Tuya-Smart-Home.jpg_640x640.jpg_.webp

Device Interview:

<details>
<summary>Details</summary>

```json
{
  "ids": {
    "modelId": "TS0505B",
    "manufacturerName": "_TZ3210_mja6r5ix"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:76:31:1d:13:56",
    "networkAddress": 31826,
    "modelId": "TS0505B",
    "manufacturerName": "_TZ3210_mja6r5ix",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 31826,
        "_reserved": 36,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 269,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          6280,
          4,
          5,
          6,
          8,
          768,
          10,
          4096,
          65518
        ],
        "outputClusters": [
          25,
          4096,
          65518
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "z.1.0",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 112
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3210_mja6r5ix"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0505B"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "unknown"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled",
                "value": true
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId",
                "value": "z.1.0"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": false,
                "reportingConfiguration": {
                  "direction": "reported",
                  "attributeDataType": 0,
                  "minInterval": 0,
                  "maxInterval": 0,
                  "minChange": {
                    "result": null,
                    "length": 0
                  },
                  "status": "SUCCESS"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16387
              },
              {
                "acl": [
                  "reportable"
                ],
                "id": 61440
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "currentLevel",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 61440,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 17,
                "name": "onLevel",
                "value": 255
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 19,
                "name": "offTransitionTime",
                "value": 10
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "onTransitionTime",
                "value": 10
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16384
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "touchlink": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "ota": {}
        }
      }
    }
  }
}
```

</details>

Additional Comments:

https://www.aliexpress.com/item/1005003097642075.html

**Comment by omBratteng** [comment]
Looking at another zigbee implementation of this model, it seems to be a little bit different compare to the other models with the same name.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/ddde6508e81192bf0f6bfd72ffe71903073d68fc/src/devices/tuya.ts#L921-L937

**Comment by JohanBendz** [comment]
This device model, _TZ3210_mja6r5ix, is used for several kind of light devices. I'll add it as standard RGB bulb. If this does not work for someone please let me know. - Added to next release.

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
