### ISSUE TITLE
Bug report - Moes Switch Module isn't responding anymore after app update

### ISSUE THREAD

**Issue by MarcoBannink** [JohanBendz/com.tuya.zigbee#451]
**Describe the bug**
After the app update update of yesterday 2.17 i am unable to control my Moes Smart Switches via Homey. 

**To Reproduce**
1. The device is showing in homey.
2. I press on the device to activate it.
4. See error message missing capability listener onof is shown.
5. No change of device status in homey.

**Expected behavior**

I would expect the device to activate and show as activated in homey

**App and Homey version**
What Homey version are you running?
What version of Homey firmware do you use?
What version of the Tuya Zigbee App are you using?

**Screenshots**
![Screenshot_20230929_193000_Homey](https://github.com/JohanBendz/com.tuya.zigbee/assets/17236580/bbdfb0f8-c609-40f5-9345-08f9182f303c)
![Screenshot_20230929_193013_Homey](https://github.com/JohanBendz/com.tuya.zigbee/assets/17236580/c27c6c67-6d37-4dc8-b014-7c2a1de5c9a9)
![Screenshot_20230929_194429_bolcom](https://github.com/JohanBendz/com.tuya.zigbee/assets/17236580/07a316fa-cd8f-4967-bc4b-338c4e85ff9f)

**Additional context**
The smart switch does react on the physical switch it is connected to.

**Comment by JohanBendz** [comment]
Hi @MarcoBannink, my bad. Will fix asap.
