### ISSUE TITLE
Bug report - constantly crashing devices/app

### ISSUE THREAD

**Issue by strejcd** [JohanBendz/com.tuya.zigbee#454]
**Describe the bug**
I get my tuya app crashed frequently (many times a day). I have latest experimental version but stable version is crashing to. I get the red excl.marks on deviced. 89666d73-8c01-4d51-9ef4-c320cf8925b4 report, I would like to know if there is my homey problem or app problem. Thank you.

**To Reproduce**
N/A

**Expected behavior**
Stop crashing devices

**App and Homey version**
What Homey version are you running? 10.0.1
What version of Homey firmware do you use? 7.4.1.1331
What version of the Tuya Zigbee App are you using? 0.2.17

**Screenshots**
N/a

**Additional context**

**Comment by LucaDallaturca** [comment]
Hello,

I'm experiencing the same problem for something like 1 month now.

Homey version : 10.0.2
Firmware version : ?
Tuya Zigbee app version : 0.2.18

Link for the crash code : 1db0c66a-e3e3-4899-b515-caffb2670ac0

Thanks,
Luca

**Comment by JohanBendz** [comment]
I have not seen this error in any reports for quite some time, if it still happens please start a new issue and send me a fresh diagnostic report.
