### ISSUE TITLE
Just question: is regex for manufacturer id possible?

### ISSUE THREAD

**Issue by pefry** [JohanBendz/com.tuya.zigbee#466]
Dear friends ,

just question... is possible to use regex for the last part in manufacturer string? ...a lot of devices are the same except last part string of manufacturer ID... so would be much easier to add only type of device once..

https://www.freecodecamp.org/news/how-to-write-regular-expression-in-json-file/

Regards
Petr

**Comment by JohanBendz** [comment]
Sorry for the late answer. No, Athoms implementation does not allow this. Sadly..
