### ISSUE TITLE
Homey App store mentions 'App is updated: 3 years ago'?



### ISSUE THREAD

**Issue by PeterKawa** [JohanBendz/com.tuya.zigbee#470]
Hi Johan,

A.f.a.i.k the app store uses the app data to publish the update info? Or is it in case of the Tuya Zigbee app a bug in the app store?

What I read from time to time is, 
users tend to assume the app is not maintained anylonger, when they read "updated 3 years ago"
They probably also never check the "Changelog" (do non-tech folks even know what that should mean.....); Then they will discover the last update was 2 days ago.

Just to let you know!

Best, 
Peter

**Comment by JohanBendz** [comment]
Still is... my bad.. a new live is on it's way,
