### ISSUE TITLE
Device Request - Mini Human Breathe Sensor - _TZE204_qasjif9e / TS0601

### ISSUE THREAD

**Issue by Gand41f** [JohanBendz/com.tuya.zigbee#480]
Device Name: Mini Human Breathe Sensor 
Device Model: TS0601
Device Description: Human presence sensor based on mmWave radar
Link to device image: https://de.aliexpress.com/item/1005005200170242.html?gatewayAdapt=glo2deu (Wallmount, 5V, Zigbee Version)

Device Interview:
`"ids": { "modelId": "TS0601", "manufacturerName": "_TZE204_qasjif9e" }, "endpoints": { "endpointDescriptors": [ { "endpointId": 1, "applicationProfileId": 260, "applicationDeviceId": 81, "applicationDeviceVersion": 0, "_reserved1": 1, "inputClusters": [ 4, 5, 61184, 0 ], "outputClusters": [ 25, 10 ] }, { "endpointId": 242, "applicationProfileId": 41440, "applicationDeviceId": 97, "applicationDeviceVersion": 0, "_reserved1": 0, "inputClusters": [], "outputClusters": [ 33 ] } ], "endpoints": { "1": { "clusters": { "groups": { "attributes": [ { "acl": [ "readable", "reportable" ], "id": 0, "name": "nameSupport", "value": { "type": "Buffer", "data": [ 0 ] }, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 65533, "name": "clusterRevision", "value": 2, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } } ] }, "scenes": { "attributes": [ { "acl": [ "readable", "reportable" ], "id": 0, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 1, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 2, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 3, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 4, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 65533, "name": "clusterRevision", "value": 2, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } } ] }, "basic": { "attributes": [ { "acl": [ "readable", "reportable" ], "id": 0, "name": "zclVersion", "value": 3 }, { "acl": [ "readable", "reportable" ], "id": 1, "name": "appVersion", "value": 74 }, { "acl": [ "readable", "reportable" ], "id": 2, "name": "stackVersion", "value": 0 }, { "acl": [ "readable", "reportable" ], "id": 3, "name": "hwVersion", "value": 1 }, { "acl": [ "readable", "reportable" ], "id": 4, "name": "manufacturerName", "value": "_TZE204_qasjif9e" }, { "acl": [ "readable", "reportable" ], "id": 5, "name": "modelId", "value": "TS0601" }, { "acl": [ "readable", "reportable" ], "id": 6, "name": "dateCode", "value": "" }, { "acl": [ "readable", "reportable" ], "id": 7, "name": "powerSource", "value": "mains" }, { "acl": [ "readable", "writable", "reportable" ], "id": 65502 }, { "acl": [ "readable", "reportable" ], "id": 65533, "name": "clusterRevision", "value": 2 }, { "acl": [ "readable", "reportable" ], "id": 65534, "name": "attributeReportingStatus", "value": "PENDING" }, { "acl": [ "readable", "reportable" ], "id": 65506 }, { "acl": [ "readable", "reportable" ], "id": 65507 } ] } }, "bindings": { "ota": {}, "time": {} } }, "242": { "clusters": {}, "bindings": {} } } }
`

**Comment by HenkRenting** [comment]
This one does not seem to work with the sme device that I have: https://github.com/JohanBendz/com.tuya.zigbee/issues/1092
