### ISSUE TITLE
Bug report - [Tuya app keeps crashing]

### ISSUE THREAD

**Issue by Rickert1993** [JohanBendz/com.tuya.zigbee#486]
**Describe the bug**
i have a issue with the app, it keep crashing and i have to restart the app multiple times a day.
zigbee devices connected with another app are keep worken, only devices connected to the tuya zigbee app are crashing.

**To Reproduce** **_I dont know what you mean with this?_**

**Expected behavior**
well i hope it stop crashing

**App and Homey version**
Homey pro (2019) version: 10.0.2
tuya App version: 0.2.18 test

**Screenshots**
Yellow marked devices are connected with a different app.
![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/108228327/710c904c-6ef4-46e2-8b39-f340ecdd0d99)

**Additional context**
after a app restart, its working again

**Comment by RikvW** [comment]
same issue here, only complete reset of Homey works for me.

**Comment by JohanBendz** [comment]
Should be solved since long..
