### ISSUE TITLE
Bug in use variable Change color shade

### ISSUE THREAD

**Issue by Ritsell** [JohanBendz/com.tuya.zigbee#49]
First of all, a fantastic app, the Tuya Zigbee app!

It is not possible to use a numeric variable in a "Change Color Tone" option. Probably the field expects a "°" after a numerical value which cannot be given from a numerical variable. Can this be solved?

With some pictures I try to make it a bit clear;
1. The action in question which works perfectly with the slider.
2. The variable linked
3 The value of the variable
4 Action does not work with the variable value.

![1](https://user-images.githubusercontent.com/78643938/107116908-c5dda900-6876-11eb-99a7-ff8e563a15e5.jpg)
![2](https://user-images.githubusercontent.com/78643938/107116914-d0983e00-6876-11eb-921e-b024c24f7649.jpg)
![3](https://user-images.githubusercontent.com/78643938/107116928-f7567480-6876-11eb-9acb-38d3b29667a3.jpg)
![4](https://user-images.githubusercontent.com/78643938/107116930-fae9fb80-6876-11eb-9e21-d2b14625b367.jpg)

If you have any questions, please let me know.

**Comment by JohanBendz** [comment]
Hi @Ritsell, ah.. it's actually the help text that need fixing. The value for this tag is between 0 and 1 in steps of 0.01.

**Comment by Ritsell** [comment]
Great, that is indeed the solution !!! The explanation text does indeed need to be clarified a bit. Thanks for your quick response.
