### ISSUE TITLE
Device Request - [Zigbee Temp & Humidity Sensor] - [tuya] / [ZTH05 / TS0601]

### ISSUE THREAD

**Issue by Magic-shadow** [JohanBendz/com.tuya.zigbee#493]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: [Zigbee Temp & Humidity Sensor]
Device Model: [ZTH05]
Device Description: [temp & Humidity sensor with screen]
Link to device image: [[Provide the URL to an image/photo of the device](https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.zigbee2mqtt.io%2Fimages%2Fdevices%2FZTH05.jpg&tbnid=ICYz-gAN_IbuVM&vet=12ahUKEwjW5vmm44GCAxUkzQIHHXZ-CRwQMygAegQIARAz..i&imgrefurl=https%3A%2F%2Fwww.zigbee2mqtt.io%2Fdevices%2FZTH05.html&docid=L1aF9e2ZWkYcfM&w=150&h=150&q=zth05%20temp&ved=2ahUKEwjW5vmm44GCAxUkzQIHHXZ-CRwQMygAegQIARAz)]

Device Interview:
[
  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_upagmta9"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "groups": {},
          "scenes": {},
          "basic": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }]

Additional Comments:
[no extra relevant information]

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by Ottobert** [comment]
I also want my Zigbee Temp & Humidity Sensor] - [tuya] TS0601 added to homey, hope to hear a suloution
