### ISSUE TITLE
Device Request - [Tuya Smart plug with metering EU] - [_TZ3000_okaz9tjs] / [TS011F]

### ISSUE THREAD

**Issue by DrDreeS** [JohanBendz/com.tuya.zigbee#500]
Control system:
Homey pro 2019 (software ver 10.0.2)

App: Tuya Zigbee
DeviceApp: Smart Plug with metering EU
Producent ID/Product ID: _TZ3000_okaz9tjs / TS011F

PROBLEM: Installs Unknown Zigbee Device
Shows only on/off, no metering value (while it has metering)	 

Device Name: [Elivco]
Device Model: [LSPA9]
Device Description: [Tuya Smart plug with metering EU]
https://nl.aliexpress.com/item/1005005665161815.html

Device Interview:

  "ids": {
    "modelId": "TS011F",
    "manufacturerName": "_TZ3000_okaz9tjs"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          6,
          3,
          4,
          5,
          57345,
          2820,
          1794
        ],
        "outputClusters": []
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "electricalMeasurement": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "metering": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      }
    }
  }

Additional Comments:
Bought 3 pcs at aliexpress 
Link: https://nl.aliexpress.com/item/1005005665161815.html

(Bought later 1 pcs at aliexpress (Aubess ZN34485501 _TZ3000_gvn91tmx / TS011F), same problem
 I will send later on an other device request for the Aubess if you dont mind)

Please add this device.
Thanks in advance

**Comment by Boechie** [comment]
@DrDreeS This device is already supported from v.0.2.12. If you install the latest Test version, it will work. You can find the latest (test-)version at https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test . Please close the issue marked as resolved. (Issue #523 duplicates this issue.)

**Comment by DrDreeS** [comment]
Thank you for your trouble, it is working fine now.

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
