### ISSUE TITLE
Device Request - Zigbee Motion Sensor - Tuya / ZG-204ZL/ZG-204Z

### ISSUE THREAD

**Issue by MarxCph** [JohanBendz/com.tuya.zigbee#519]
Hi Johan,

Thank you for adding this Motion Sensor

Device Name: Zigbee Motion Sensor
Device Model: ZG-204ZL/ZG-204Z
Device Description: Motion Sensor
Link to device image: https://www.aliexpress.com/item/1005006161560449.html?spm=a2g0o.productlist.main.55.121223c89kRGxN&algo_pvid=9e60d1c0-a4d3-41a2-8d5b-2f38c11a42db&algo_exp_id=9e60d1c0-a4d3-41a2-8d5b-2f38c11a42db-27&pdp_npi=4%40dis%21DKK%21110.94%2153.25%21%21%21114.38%21%21%402101c5a416989129328303149e679f%2112000036052068237%21sea%21DK%212834747469%21&curPageLogUid=nNPjpEPUEYaL

Device Interview:

  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_3towulqd"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:bf:ef:88:bb:bf",
    "networkAddress": 40260,
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_3towulqd",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 40260,
        "_reserved": 26,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          1280,
          57346,
          61184,
          60928,
          57344,
          1,
          1024
        ],
        "outputClusters": []
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "swBuildId": "0122052017",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "motionSensor"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0,
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "3c:2e:f5:ff:fe:23:20:69"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 33
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "illuminanceMeasurement": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "measuredValue",
                "value": 1000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "minMeasuredValue",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 4000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      }
    }
  }

Additional Comments:
I bought the device on Aliexpress

Thanks in advance.
Martin

**Comment by JohanBendz** [comment]
Added to next release, thanks to @demyvdj 😎
