### ISSUE TITLE
Device Request - Update 13-11-23: Seems to work in the test-version [Tuya Smart Zigbee Plug 16A/20A Eu Outlet 3680W Power Meter Compatiable Met Alexa En Tuya Hub] - [On the device the text: Elivco, model LSPA9] [Like Sun GMBH, Essen] [720416123547]

### ISSUE THREAD

**Issue by ruudbinnendijk** [JohanBendz/com.tuya.zigbee#523]
it would be very nice if this device is supported by the app. Thanks in advance, Ruud

Manufacturer | ModelID (developer tools): _TZ3000_okaz9tjs | TS011F

https://nl.aliexpress.com/i/1005002344798281.html

  "ids": {
    "modelId": "TS011F",
    "manufacturerName": "_TZ3000_okaz9tjs"
  },
  "endpoints": {
    "ieeeAddress": "70:b3:d5:2b:60:03:f9:dd",
    "networkAddress": 1637,
    "modelId": "TS011F",
    "manufacturerName": "_TZ3000_okaz9tjs",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 1637,
        "_reserved": 24,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          6,
          3,
          4,
          5,
          57345,
          2820,
          1794
        ],
        "outputClusters": []
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "500+TZSKT31BS102",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "electricalMeasurement": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "metering": {
            "attributes": "UNSUP_GENERAL_COMMAND",
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {}
      }
    }
  }

Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: [Provide the name of the device]
Device Model: [Provide the model number or identifier]
Device Description: [Describe in short the functionality of the device]
Link to device image: [Provide the URL to an image/photo of the device]

Device Interview:
[Paste the device interview information here]

Additional Comments:
[Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help]

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by Boechie** [comment]
@ruudbinnendijk **Duplicate of issue #500**. This device is already supported from v.0.2.12. If you install the latest Test version, it will work. You can find the latest (test-)version at https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test . Please close the issue marked as resolved.

**Comment by ruudbinnendijk** [comment]
Thank you!

**Comment by HyungsukRyu** [comment]
Do I need a Tuya Hub for the connection with Homey Pro and the Tuya Smart zigbee plug ?

**Comment by ruudbinnendijk** [comment]
Maybe You beter don't use Tuya plugs. 3 out of 4 burnt a fuse here.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Boechie** [comment]
> Do I need a Tuya Hub for the connection with Homey Pro and the Tuya Smart zigbee plug ?

No, you can connect to Homey directly over zigbee. That is what this app supports. Alternatively, you can use the Homey Tuya Cloud app and connect your device to Tuya Cloud, in which case you will need a bridge.
