### ISSUE TITLE
2 and 3 gang switches additional device times out

### ISSUE THREAD

**Issue by Malalicious** [JohanBendz/com.tuya.zigbee#53]
When using the 2 and 3 gang "on wall" switches, the non-primary buttons act oddly. I have tested the following scenarios:

1. Switch the primary button physically: Homey toggles the status CORRECTLY
2. Switch the primary button from within Homey: Homey toggles the status and the device CORRECTLY
3. Switch a secondary button physically: Homey toggles the status INCORRECTLY
4. Switch a secondary button from within Homey: Homey toggles the status INCORRECTLY

When the status is incorrectly toggles, a time out within Homey is popped up but eventually (I guess the ZigBee driver polls the device for its status) Homey figures out what the actual state of the device is and updates this. This can take a while.

**Comment by Malalicious** [comment]
Switched a device a couple of times and created a diagnostics report: 75489e2c-98d2-4ea8-9b5a-23dc41afb0e5

**Comment by Malalicious** [comment]
Been running the app locally to try and debug this issue. It does not seem to be necessarily related to the app. When I check the developer console, I notice that the majority of the ZigBee devices are permanently offline. This started since I upgraded to v5.
![afbeelding](https://user-images.githubusercontent.com/19594845/109618963-7c604100-7b38-11eb-8833-4d9fe8c1918e.png)

**Comment by Malalicious** [comment]
This is not related to the Tuya app but Homey's v5 update.
See: https://community.athom.com/t/zigbee-issue-5-0-0-rc47/38556/6

**Comment by JohanBendz** [comment]
Thanks for the feedback.
