### ISSUE TITLE
Device Request - Temperature & Humidity Sensor - tuya / IH-K009

### ISSUE THREAD

**Issue by BBL222** [JohanBendz/com.tuya.zigbee#533]
"ids": {
    "modelId": "TS0201",
    "manufacturerName": "_TZ3000_dowj6gyi"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:d3:93:15:e5:06",
    "networkAddress": 44099,
    "modelId": "TS0201",
    "manufacturerName": "_TZ3000_dowj6gyi",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 44099,
        "_reserved": 24,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 770,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1026,
          1029,
          0
        ],
        "outputClusters": [
          3,
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {},
          "identify": {},
          "temperatureMeasurement": {},
          "relativeHumidity": {},
          "basic": {}
        },
        "bindings": {
          "identify": {},
          "ota": {},
          "time": {}
        }
      }
    }
  }

**Comment by Boechie** [comment]
@BBL222 This device is already supported from v.0.2.12. You can find the latest (test-)version at https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test . Please close the issue marked as resolved.

**Comment by BBL222** [comment]
Tnx!
