### ISSUE TITLE
Device Request - [SMART HUMAN PRESENCE SENSOR] - [LOGINOVO] / [ZY-M100]

### ISSUE THREAD

**Issue by Roobbbiiiinnnnn** [JohanBendz/com.tuya.zigbee#550]
Device Name: [LOGINOVO]
Device Model: [Smart human presence sensor ZY-M100]
Device Description: [Presence sensor]
Link to device image: [data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEA8PDhANDhAPEBAQDRAQDw8PDg8QFREWFhUSFhYYHSggGBolGxMTITEiJTUrLi4vFx8zODMsNygtLisBCgoKDg0OGhAQGzAlICYvNS4tLzA3Ny4uMisrNjItMS0vLjcvKy0tLzItKzUyNSsrNy0tLS81Ny0rLSstLy0tLf/AABEIAKgBLAMBEQACEQEDEQH/xAAbAAEAAgMBAQAAAAAAAAAAAAAAAgMBBAUGB//EADwQAAICAQEFBQUFBgYDAAAAAAABAgMRBBIhMUFRBQZhcYEHEyKRsRQyUqHBI0KCssLRYqKz0uHwJHKS/8QAGwEBAAMBAQEBAAAAAAAAAAAAAAEFBgQDAgf/xAA1EQEAAgECAwQHCAEFAAAAAAAAAQIDBBEFIUESMcHhE1FhcYGRoQYUIiMysdHwQiQzYnLC/9oADAMBAAIRAxEAPwD7iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYbAbQDKAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQlZ6gQcmQADJIZAzkDKmBNMDIAAAAAAAAAAAAVK7LxFN44y4R+fP0All+AGHN+AEozTAkAAAAAAAAAAAAAAAAonZncuHXr/wBhAZIAAAAAYJGNrAF8J5AkAAAAAAAAAAU2fE9lcF99/0gWYxuW7oBhgQkBXIC2m3O58fqBaAAAAAAAAAAAAACjUT/AHV/F/YCtECZIEDIGl2zp7bdPdXRZ7m6cHGqzalHYnyllb16AbrAAYJEGBiMsEDahLKJEgAAAAAAVanURri5TeF8230S5sDjz7ZsnJRqgoZeNqzMpY67K3L5sDtVRwvHi/MCTAq1FmzGUsOWzGUtlcZYWcLxA1uztZG+mu6KaVizh8UBdICqXh6AbVNm0s8+fmBYAAAAAAAAAAAIzlhNvksgae/nx4vzIEkBNEjIAAQAADDJEWQIsCzTz34A2SQAAAK9RcoRcnv6Lq+gHJnq7pfvKC/wr9WBryqy8ybk+rbb/MDZ7PoW2n0A7IGAMMCvZSWEkl0SwgISArmBqa3V2U1XWVVyvnGuThUtznJLcv8Av5nzaZiJmHphpW+StbTtEzzn1e187t9oWvs+69PUuWxU3Jes5NfkUuTiWXfaIiGzx/Z3SV/VMz8do+keLj6/vRrJLFusvWeCjYqfl7tI8Pveoyd0/J3U4ZosXOMcfHn++70Psr7Tm9VdVOdk9qE01OcpP3kJR688bR2aK94zTW89FVx/DitpqZcURtv0jblO/k+plux4AAAAPHe0HtG2p6SFNk69uVkpbEnFtR2Us45fEys4lmtSKxWdt17wXT48npLXrE7RHf7d/wCHHr7y6pcLG/PD+pxxrc0dVhPDNPP+L1/Z2tutqpldGEfeR29zak1F7m445/C/UucF7Xxxa3fLNarHTHmtSndDbR6udNASRIkAAAZIACLJEGQIMDClhokcrvD29qNPGtxqrSm3iUpOaaS4YWMPecWs1NsPZ7Md6y4bo6ambRee71ONHvzfzqofpNfqcccSv1iFrPA8XS0/T+Hpe7Xbn2uNjcNh1ySeHlNNZT8ODO/S6n08Ty22VGv0P3Waxvvu7J1K9o63LljkvqwNZwAr2QNzs+O9gb4ACLAiwK5AVsCtgeU9ovYVcqXraoqFkHH32yse8hJqOWvxJtb+mfDFZxHT1tT0kd8NJwDX3jLGntO9Z7vZMc/lPq9b5hr4KVct2+EZOL6Pdn6FPivMTEdGu7Mbuz3C1Gz2nU1wnYpY6q2p5/1M+hY0nbU0n1+Kl1VO1wy9Z/x/8z5PuJdMOAAAAD5/7RJ51Wlj+GuUvnPH9JS8Un8dY9jT8Dj8jJPt8PNy+7mhVl9NT3xc8zzzisya+SwcmlxxfLWs/wB6u7XZpx4bXjv28n0DXz/axX4an/mkv9hpGKThIkWIgTRIkAAACAJEWBFkCuQFNkiRnWaRajSzhJZeJuD6Si3ss8NRijJjmv8Ad3Rpc04ctbx/YfM9LGt2Yuk4wcZrK5Tcfgb8M4yZzH2Zn8Xd49G1yzkim+ON55fLr9HrfZu/h1PnTnzxItOFfpt8FFx7vx/Hwe0LZn2nq1vz1QGhrdZXTDbtkox4LLSy+i6vc9wHF0/eSq2coVQvtcIxk/dqGcPrtNY5fMDh9pd9NTVZZCmuunZk4/GnZZu6vOCl1HEclck0rG2zW6HgenyYq5LzM7xv6o/lPux3q1VmrpV90pwslsOLjCMfi3LckubR46fXZZzVi9uU8vn5vTiPCtPTTWnFXaY59enk+nGgY5FgRYEJAVMCtgeV9oXbldem+xqSd12y5RW9wqU87T6ZccL16HBxDLFcU06y0H2f0d8mf08x+Gv1n1fXd8zujtQlHhtLGd+5Z3/lu9ShpaKzvs2UxO7o9zq9ntHRb/3oV+eE8P5JL0O7Bl9Jlpy7pV+uwRTRZtp795fdS/fnoAAAAPnPf+X/AJ1fhp4/z2P9Ci4n/vR7vGWr4LH+lt/28IU9z70tVRJ7lLaj6yi0vzPLQ22zVl68UpM6e8R/dpe17RX7dPrUsek3n+ZGhY9OokXxIE0SMoDIAAAYEWBBkCuRI17WQNqu5V6eVktyirJP0bPnJeKUm09HpipN7xWOsvlMKJWTkorOzGVks7lGEVmTZl6VmY2jpG/whvLZK46xNusxHxl7T2cr4dS/8cF8ov8AuW3Cv0297Pcen8WOPZL2JaqBr6yPwp9GByO1NLG2qUJQdq3NQU9jaa4LPQDzPYlk6dbCE4KiFsJ1xhK9aiyc0tr7yb4bPN5+LhyA1faD2eozr1EVhWLYsx+OPB+sf5Sj4rh2tGSOvKWs+z2pm1LYZ6c4909/1/d5zT2bEq5x4xaa80ylraa23jovb17dbVnq+3ae1ThCa4TjGS8mso2lbRasWjq/OL0mlprPTkkz6fLDArYFbAqmB53tbuRXrb/tNl9tfwRrcK4wz8LbztST/F05HLm0lM1t7LjQ8Zy6TD6KlYnnvz38mzpe4HZ8MbULbWudls/pHCPmuhwV6GTj2tv3WiPdEecuxouwtJQ1KnTaeuS4SjXHb/8ArGToripXuiHBl1moy8sl5n4y6J6OYAAAAHhu+XY2ot1cLqqpWV+5jBuOG1JObaa4/vIqddp8mTJFqxvGzRcK1mHHp5x3ttO+/wC38OPHsnVRacaL0004tVy3NcGcP3bPE8qysZ1mmtG03jb3va2zuk6XdVsNQlGUlOMk5NRfBcPus0Vd9o372Ov2e1PZ7unubFZ9PleiBJEjIGcgZAxkABFkCLAqmSNewgcLvdqNR7uqlVWRqacptLbU2nuy48Fzw/0KviU5J2rWOXVecGph3te8x2o7t3jnldU8YfFbnyKnszDS71l7z2dR/YXy63tfKuH9y44XH5dp9vhDM8dn86kf8fGXrCzUiFscxa8AObOKaae9NNNdUwPAdsL7LdTfGvRU+7urjb7iz3mo925L9m9qPN43JryA9F34qUtFN8didcov+LZ+kmcHEq76eZ9W38Lfgd5rrKx64mPpv4PnO2ksdGZjbm2u07vrXcvV+90VO/fDNb/he7/K4mo4dk7enr7OXy8mF4ti9Hq7e3n8/N22dytYAgwISApmBtaRfD5t/UC4AAAAAAAAAAp1VW1BpceMfNb0BpVkC6IEkSMgZAAMAYAwyBCQFcgI1VbUkuXPy5kjqARnWnxSfmkwmJmO5iqqMViEYxWW8RSSy+L3ERER3FrTbnMpkoAObZHDa6MDzveDsD7RC6C91FWRajs0RU1PirJWZy2pb1jAGrreztZZpfs87dO8Rgl8E9qWw1jM9prfhcjn1WGcuKaQ7eHamum1Fclo3iN/rGzj6LuLqbHvsogueZTk/RJFRXhWXrMNLf7RaeI/DW0/KPF73uz2J9iqlX7x2uUtpvZ2UnhLCWX0LTSaX7vSa777zuznENb97yRfs7bRt63WZ1uBhgQYEJAVTA3Ko4il4ATAAAAAAAAAAAGndXiXhLevPmv1+ZAxECaJGUAA857QO9D7L0M9WqXfJThXGG04xTm38Umk8Lc/N4QGx3L7efaOho1jqdDuUs1t5w4zccp84vGV5gdsCLIEJAQaJG1pa8LPX6AXgAAAABpa+tbnlpt8m96wBpuSiuvrlga0bVv3YXLy6AXafUqMkB2oyTWUAYEQISX5ARkBGEMtfNgbYAAAAAAAAAAAARnFNYYGtKOHh+j6kDKJGcAZAhdTGcZQsjGcJLEozipQkujT3MDMIKKUYpRiliMUkopdElwAyBFkCLAspqzvfD6gbJIAAAAABVqdPGxbMs+DW5ryA87f2LqtpqEqpR5SlKUX6rDAlX3fvf3rq4/+sZT+uAKbuwdWn8E6Zrq3OD+WGB1ey6tRVDF/u5pcHCUm8eOUuAHTjJNZW9AGBBgQkBdVDC8XxAmAAAAAAAAAAAAADEop7mBTKtrxX5gYTAAAAGGBHBAtrp6/IkXAAAAAAAAAAAAAAos0+/MG4S6ren5oCCVy4qqXjmUH8sMCyEJP72yvJuX6ICyMUgJAAAAAAAAAAAAAAAAAEZQT5ARdXj8wMe7fgA92/ADKq6vP5ATUUuAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//2Q==
]

Device Interview:
[
  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_qasjif9e"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 74
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE204_qasjif9e"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 8
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 9
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 3
              }
            ]
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }
]

Additional Comments:
[https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.aliexpress.com/item/1005004274734390.html&ved=2ahUKEwia4uKWg9aCAxVBIRAIHVnGBlQQFnoECBEQAQ&usg=AOvVaw0959zk6ZNPQjkoT5XQBSq3]

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
