### ISSUE TITLE
Device Request - [zigbee irrigation controller ] - [Gi experience ] / [QT06]

### ISSUE THREAD

**Issue by Yakuza79be** [JohanBendz/com.tuya.zigbee#555]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: [Provide the name of the device]
Device Model: [Provide the model number or identifier]
Device Description: [Describe in short the functionality of the device]
Link to device image: [Provide the URL to an image/photo of the device]

Device Interview:
[Paste the device interview information here]

Additional Comments:
[Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help]

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by Yakuza79be** [comment]
Hi, please add the Tuya Zigbee irrigation controller. Found some code on the internet but I’m a newbie.
GIEX 
![IMG_5816](https://github.com/JohanBendz/com.tuya.zigbee/assets/151874103/5f6913d5-7bfd-4816-b17f-0da4c126e4d9)

**Comment by JohanBendz** [comment]
Without the interview there is nothing I can add.. If you still want this added please create a new issue and follow guidelines.
