### ISSUE TITLE
Device Request [Tuya ZigBee Human Presence Sensor, ZY-M100 series] - TZE204_ijxvkhd0 / TS0601

### ISSUE THREAD

**Issue by tjarb** [JohanBendz/com.tuya.zigbee#565]
[I suggest to add "_TZE204_ijxvkhd0" to"com.tuya.zigbee-SDK3\com.tuya.zigbee-SDK3\drivers\radar_sensor\driver.compose.json"]

Bought this device through AliExpress:
https://nl.aliexpress.com/item/1005006128737558.html?spm=a2g0o.order_list.order_list_main.5.533279d25ORxW4&gatewayAdapt=glo2nld

Device Name: Tuya ZigBee Human Presence Sensor
Device Model: ZY-M100 series ( 230V and 5V version share same Manufacturer and ModelID) 
Device Description: mmWave presence sensors
Link to device image: 
![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/55927848/de1d4095-44e5-4fde-9ca4-eb963802aab5)

Referenced projects:
https://www.zigbee2mqtt.io/supported-devices/#s=zy-m100
https://blakadder.com/zy-m100/
https://smarthomescene.com/reviews/tuya-zigbee-human-presence-sensor-zy-m100-review

Interview result:
`
{
    "ids": {
        "modelId": "TS0601",
        "manufacturerName": "_TZE204_ijxvkhd0"
    },
    "endpoints": {
        "ieeeAddress": "a4:c1:38:0c:d6:b1:c5:db",
        "networkAddress": 61737,
        "modelId": "TS0601",
        "manufacturerName": "_TZE204_ijxvkhd0",
        "endpointDescriptors": [
            {
                "status": "SUCCESS",
                "nwkAddrOfInterest": 61737,
                "_reserved": 20,
                "endpointId": 1,
                "applicationProfileId": 260,
                "applicationDeviceId": 81,
                "applicationDeviceVersion": 0,
                "_reserved1": 1,
                "inputClusters": [
                    4,
                    5,
                    61184,
                    0
                ],
                "outputClusters": [
                    25,
                    10
                ]
            },
            {
                "status": "SUCCESS",
                "nwkAddrOfInterest": 61737,
                "_reserved": 10,
                "endpointId": 242,
                "applicationProfileId": 41440,
                "applicationDeviceId": 97,
                "applicationDeviceVersion": 0,
                "_reserved1": 0,
                "inputClusters": [],
                "outputClusters": [
                    33
                ]
            }
        ],
        "deviceType": "router",
        "receiveWhenIdle": true,
        "capabilities": {
            "alternatePANCoordinator": false,
            "deviceType": true,
            "powerSourceMains": true,
            "receiveWhenIdle": true,
            "security": false,
            "allocateAddress": true
        },
        "extendedEndpointDescriptors": {
            "1": {
                "clusters": {
                    "groups": {
                        "attributes": [
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 0,
                                "name": "nameSupport",
                                "value": {
                                    "type": "Buffer",
                                    "data": [
                                        0
                                    ]
                                },
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 65533,
                                "name": "clusterRevision",
                                "value": 2,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            }
                        ]
                    },
                    "scenes": {
                        "attributes": [
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 0,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 1,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 2,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 3,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 4,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 65533,
                                "name": "clusterRevision",
                                "value": 2,
                                "reportingConfiguration": {
                                    "status": "NOT_FOUND",
                                    "direction": "reported"
                                }
                            }
                        ]
                    },
                    "basic": {
                        "attributes": [
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 0,
                                "name": "zclVersion",
                                "value": 3
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 1,
                                "name": "appVersion",
                                "value": 74
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 2,
                                "name": "stackVersion",
                                "value": 0
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 3,
                                "name": "hwVersion",
                                "value": 1
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 4,
                                "name": "manufacturerName",
                                "value": "_TZE204_ijxvkhd0"
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 5,
                                "name": "modelId",
                                "value": "TS0601"
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 6,
                                "name": "dateCode",
                                "value": ""
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 7,
                                "name": "powerSource",
                                "value": "mains"
                            },
                            {
                                "acl": [
                                    "readable",
                                    "writable",
                                    "reportable"
                                ],
                                "id": 65502
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 65533,
                                "name": "clusterRevision",
                                "value": 2
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 65534,
                                "name": "attributeReportingStatus",
                                "value": "PENDING"
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 65506
                            },
                            {
                                "acl": [
                                    "readable",
                                    "reportable"
                                ],
                                "id": 65507
                            }
                        ]
                    }
                },
                "bindings": {
                    "ota": {},
                    "time": {
                        "attributes": [
                            {
                                "acl": [
                                    "readable"
                                ],
                                "id": 65533,
                                "name": "clusterRevision",
                                "value": 1
                            }
                        ]
                    }
                }
            },
            "242": {
                "clusters": {},
                "bindings": {}
            }
        }
    }
}
`

**Comment by tjarb** [comment]
I suggested to add "_TZE204_ijxvkhd0" to"com.tuya.zigbee-SDK3\com.tuya.zigbee-SDK3\drivers\radar_sensor\driver.compose.json"

Done that, build and installed on homey pro. The LUX measurements works but the motion detection is not working.

**Comment by tjarb** [comment]
So, I found that the ZY-M100 uses other endpoints.
https://github.com/zigpy/zha-device-handlers/issues/2378#issuecomment-1548362639

I'll try to make a radar_sensor_2 dir and make a new device based on:

> Here is the description for the datapoints:
104 - Lux
105 - Presence
106 - Motion sensitivity
107 - Max detection distance
108 - Min detection distance
109 - Target distance
110 - Detection delay
111 - Fading time
>

**Comment by tjarb** [comment]
Oke I made a new driver dir named "radar_sensor_2" and modified the datapoints and device info. The detection now works for ZY-M100 (_TZE204_ijxvkhd0, _TZE204_ijxvkhd0)

Attached the content for these devices
[radar_sensor_2.zip](https://github.com/JohanBendz/com.tuya.zigbee/files/13543635/radar_sensor_2.zip)

**Comment by Trikos** [comment]
Hey, I also have this sensor but mine isnt the ceiling version but the wall. Do they have the same model id _TZE204_ijxvkhd0?

**Comment by Trikos** [comment]
How do I use the zip created? Where should I put those files?

**Comment by tjarb** [comment]
hi @Trikos ,

I got both. The AC ceiling mount and the USB wall mount models have the same IDs.

You first need to download ths tiya code, download as archive an extract somewhere to your disk. 
the download my zip file, it shoud be extracted to the drivers folder 
"com.tuya.zigbee-SDK3\com.tuya.zigbee-SDK3\drivers\"

with the result "com.tuya.zigbee-"SDK3\com.tuya.zigbee-SDK3\drivers\radar_sensor_2\"

after that I just use the "homey login", "homey app run" or "homey app install" commands as described in the Homey DSK documentation.
https://apps.developer.homey.app/the-basics/getting-started

**Comment by tjarb** [comment]
hi @Trikos ,

I've added your ID. You may give it a try: https://github.com/JohanBendz/com.tuya.zigbee/issues/565#issuecomment-1837077987

**Comment by Trikos** [comment]
Wait, I thought It was for home assistant xD I guess its not, my bad
