### ISSUE TITLE
Device Request - Temperature and Humidity Sensor - _TZ3000_saiqcn0y/ TS0201

### ISSUE THREAD

**Issue by bilellom** [JohanBendz/com.tuya.zigbee#566]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: Temperature & Humidity Sensor
Device Model: zigbee ZN37318601
Device Description: Sensor for Temp and Humidity
Link to device image: https://www.aliexpress.com/item/1005005595631552.html?spm=a2g0o.order_list.order_list_main.55.33361802HNX8Ep

Device Interview:
  "ids": { "modelId": "TS0201", "manufacturerName": "_TZ3000_saiqcn0y" }, "endpoints": { "ieeeAddress": "a4:c1:38:d4:0c:7f:0f:29", "networkAddress": 61275, "modelId": "TS0201", "manufacturerName": "_TZ3000_saiqcn0y", "endpointDescriptors": [ { "status": "SUCCESS", "nwkAddrOfInterest": 61275, "_reserved": 24, "endpointId": 1, "applicationProfileId": 260, "applicationDeviceId": 770, "applicationDeviceVersion": 0, "_reserved1": 1, "inputClusters": [ 1, 3, 1026, 1029, 0 ], "outputClusters": [ 3, 25, 10 ] } ], "deviceType": "enddevice", "receiveWhenIdle": false, "capabilities": { "alternatePANCoordinator": false, "deviceType": false, "powerSourceMains": false, "receiveWhenIdle": false, "security": false, "allocateAddress": true }, "extendedEndpointDescriptors": { "1": { "clusters": { "powerConfiguration": { "attributes": [ { "acl": [ "readable", "reportable" ], "id": 0, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 32, "name": "batteryVoltage", "value": 30, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 33, "name": "batteryPercentageRemaining", "value": 200, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 65533, "name": "clusterRevision", "value": 1, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } } ] }, "identify": { "attributes": [] }, "temperatureMeasurement": {}, "relativeHumidity": { "attributes": [ { "acl": [ "readable", "reportable" ], "id": 0, "name": "measuredValue", "value": 5847, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 1, "name": "minMeasuredValue", "value": 5847, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 2, "name": "maxMeasuredValue", "value": 6148, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } }, { "acl": [ "readable", "reportable" ], "id": 65533, "name": "clusterRevision", "value": 2, "reportingConfiguration": { "status": "NOT_FOUND", "direction": "reported" } } ] }, "basic": { "attributes": [ { "acl": [ "readable", "reportable" ], "id": 0, "name": "zclVersion", "value": 3 }, { "acl": [ "readable", "reportable" ], "id": 1, "name": "appVersion", "value": 70 }, { "acl": [ "readable", "reportable" ], "id": 2, "name": "stackVersion", "value": 0 }, { "acl": [ "readable", "reportable" ], "id": 3, "name": "hwVersion", "value": 1 }, { "acl": [ "readable", "reportable" ], "id": 4, "name": "manufacturerName", "value": "_TZ3000_saiqcn0y" }, { "acl": [ "readable", "reportable" ], "id": 5, "name": "modelId", "value": "TS0201" }, { "acl": [ "readable", "reportable" ], "id": 6, "name": "dateCode", "value": "" }, { "acl": [ "readable", "reportable" ], "id": 7, "name": "powerSource", "value": "battery" }, { "acl": [ "readable", "writable", "reportable" ], "id": 65502 }, { "acl": [ "readable", "reportable" ], "id": 65533, "name": "clusterRevision", "value": 2 }, { "acl": [ "readable", "reportable" ], "id": 65534, "name": "attributeReportingStatus", "value": "PENDING" }, { "acl": [ "readable", "reportable" ], "id": 65506 }, { "acl": [ "readable", "reportable" ], "id": 65507 } ] } }, "bindings": { "identify": { "attributes": [] }, "ota": {}, "time": {} } } } }

Additional Comments:
Similar to _TZ3000_xr3htd96 TS0201

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by stefan-schweiger** [comment]
Already exists as a request:
https://github.com/JohanBendz/com.tuya.zigbee/issues/561

**Comment by bilellom** [comment]
duplicate https://github.com/JohanBendz/com.tuya.zigbee/issues/561 request, so I close it
