### ISSUE TITLE
Device Request - Flood Sensor - _TZ3000_upgcbody / TS0207

### ISSUE THREAD

**Issue by bilellom** [JohanBendz/com.tuya.zigbee#568]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name:  Water Sensor Leak Detector Flood Water
Device Model: 898WZ
Device Description: Flood Sensor
Link to device image: https://www.aliexpress.com/item/1005005066497327.html?spm=a2g0o.order_list.order_list_main.54.33361802HNX8Ep#nav-specification

Device Interview:
ID du fabricant : _TZ3000_upgcbody
ID du produit : TS0207
Recevoir lorsque inactif
⨯
Type d'appareil
enddevice
ID de l'appareil : a4:c1:38:e5:93:3e:8f:cb
Version du micrologiciel
Identifiants de groupe

Additional Comments:
Similar to _TZ3000_4uvovz4r / TS0207
When I try to interview the device I always get this answer : 
Interview failed (error: Failed to interview device (error: Timeout (25000ms): get node capabilities))
Are the info I put above enough to add this device? Otherwise can you help me get the device info trough the way explained below?

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by edwinff** [comment]
[Similar device here](https://nl.aliexpress.com/item/1005005651861263.html?spm=a2g0o.detail.0.0.27dd2614owdaNT&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.362094.0&scm_id=1007.40050.362094.0&scm-url=1007.40050.362094.0&pvid=f3ab9fc2-7e36-4e48-a245-eb695108435b&_t=gps-id:pcDetailTopMoreOtherSeller,scm-url:1007.40050.362094.0,pvid:f3ab9fc2-7e36-4e48-a245-eb695108435b,tpp_buckets:668%232846%238111%231996&pdp_npi=4%40dis%21EUR%2111.97%215.86%21%21%2190.99%21%21%40210384cc17014455138763167eb566%2112000033891954698%21rec%21NL%21183483565%21), with different form factor.

"modelId":string"TS0207"
"manufacturerName":string"_TZ3000_kstbkt6a"

...

  "ids": {
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_kstbkt6a"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "identify": {
            "attributes": []
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "waterSensor",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0,
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "00:12:4b:00:18:dd:5f:2c",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 255,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 65
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_kstbkt6a"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0207"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 8
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 9
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }
...

**Comment by obetsak** [comment]
There already exist a issue for this device since match 26/3 2022
 Water Sensor - TS0207 / _TZ3000_upgcbody #176 

intervju for _TZ3000_upgcbody / TS0207

``` json  
"ids": {
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_upgcbody"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:ec:e0:f6:82:2a",
    "networkAddress": 29868,
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_upgcbody",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 29868,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "identify": {
            "attributes": []
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "enrolled",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "waterSensor",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0,
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "3c:2e:f5:ff:fe:22:b9:7a",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 65
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_upgcbody"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0207"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }
```

**Comment by bilellom** [comment]
> There already exist a issue for this device since match 26/3 2022 Water Sensor - TS0207 / _TZ3000_upgcbody #176
> 
> intervju for _TZ3000_upgcbody / TS0207
> 
> ```json
> "ids": {
>     "modelId": "TS0207",
>     "manufacturerName": "_TZ3000_upgcbody"
>   },
>   "endpoints": {
>     "ieeeAddress": "a4:c1:38:ec:e0:f6:82:2a",
>     "networkAddress": 29868,
>     "modelId": "TS0207",
>     "manufacturerName": "_TZ3000_upgcbody",
>     "endpointDescriptors": [
>       {
>         "status": "SUCCESS",
>         "nwkAddrOfInterest": 29868,
>         "_reserved": 20,
>         "endpointId": 1,
>         "applicationProfileId": 260,
>         "applicationDeviceId": 1026,
>         "applicationDeviceVersion": 0,
>         "_reserved1": 1,
>         "inputClusters": [
>           1,
>           3,
>           1280,
>           0
>         ],
>         "outputClusters": [
>           25,
>           10
>         ]
>       }
>     ],
>     "deviceType": "enddevice",
>     "receiveWhenIdle": false,
>     "capabilities": {
>       "alternatePANCoordinator": false,
>       "deviceType": false,
>       "powerSourceMains": false,
>       "receiveWhenIdle": false,
>       "security": false,
>       "allocateAddress": true
>     },
>     "extendedEndpointDescriptors": {
>       "1": {
>         "clusters": {
>           "powerConfiguration": {
>             "attributes": [
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 0,
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 32,
>                 "name": "batteryVoltage",
>                 "value": 30,
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 33,
>                 "name": "batteryPercentageRemaining",
>                 "value": 200,
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 65533,
>                 "name": "clusterRevision",
>                 "value": 1,
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               }
>             ]
>           },
>           "identify": {
>             "attributes": []
>           },
>           "iasZone": {
>             "attributes": [
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 0,
>                 "name": "zoneState",
>                 "value": "enrolled",
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 1,
>                 "name": "zoneType",
>                 "value": "waterSensor",
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 2,
>                 "name": "zoneStatus",
>                 "value": {
>                   "type": "Buffer",
>                   "data": [
>                     0,
>                     0
>                   ]
>                 },
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "writable",
>                   "reportable"
>                 ],
>                 "id": 16,
>                 "name": "iasCIEAddress",
>                 "value": "3c:2e:f5:ff:fe:22:b9:7a",
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 17,
>                 "name": "zoneId",
>                 "value": 1,
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 65533,
>                 "name": "clusterRevision",
>                 "value": 1,
>                 "reportingConfiguration": {
>                   "status": "NOT_FOUND",
>                   "direction": "reported"
>                 }
>               }
>             ]
>           },
>           "basic": {
>             "attributes": [
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 0,
>                 "name": "zclVersion",
>                 "value": 3
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 1,
>                 "name": "appVersion",
>                 "value": 65
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 2,
>                 "name": "stackVersion",
>                 "value": 0
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 3,
>                 "name": "hwVersion",
>                 "value": 1
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 4,
>                 "name": "manufacturerName",
>                 "value": "_TZ3000_upgcbody"
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 5,
>                 "name": "modelId",
>                 "value": "TS0207"
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 6,
>                 "name": "dateCode",
>                 "value": ""
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 7,
>                 "name": "powerSource",
>                 "value": "battery"
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "writable",
>                   "reportable"
>                 ],
>                 "id": 65502
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 65533,
>                 "name": "clusterRevision",
>                 "value": 2
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 65534,
>                 "name": "attributeReportingStatus",
>                 "value": "PENDING"
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 65506
>               },
>               {
>                 "acl": [
>                   "readable",
>                   "reportable"
>                 ],
>                 "id": 65507
>               }
>             ]
>           }
>         },
>         "bindings": {
>           "ota": {},
>           "time": {}
>         }
>       }
>     }
>   }
> ```

Hi thank you for you answer. Could you please confirm: because an issue for the same product already exist, I should close my request.
