### ISSUE TITLE
Bug report - TS05020A tunable white light can’t change colors

### ISSUE THREAD

**Issue by Bkroes123** [JohanBendz/com.tuya.zigbee#586]
**Describe the bug**
I just added my lidl tunable white light’s to the homey instead of the silvercrest hub. But when i trie to change the color it does only change a tiny bit. Because of that i do still use the lidl app. Because it is cold white al the time with the homey app. 

**To Reproduce**
1. Go to the light
2. Click on color
3. Scroll down to the color you want
4. Nothing happens or only a tiny bit. 

**Expected behavior**
I would like that i can change the color to a warmer color. 

**App and Homey version**
What Homey version are you running? 7.5.2.1367
What version of Homey firmware do you use? 10.0.3
What version of the Tuya Zigbee App are you using? 0.1.45

**Comment by mmixxu** [comment]
I had same problem.
Try download test version of Tuya Zigbee App: https://homey.app/en-fi/app/com.tuya.zigbee/Tuya-Zigbee/test/
It fixed my problem.

**Comment by Bkroes123** [comment]
It did! Thnx!
