### ISSUE TITLE
Button remotes do not trigger

### ISSUE THREAD

**Issue by Malalicious** [JohanBendz/com.tuya.zigbee#59]
Button remotes got added in the latest test version but they do not seem to work properly. Upon pressing a button it does not trigger the flow card actions. I would help you debug but the code isn't updated in the SDK3 branch on Github to support the remotes

**Comment by JohanBendz** [comment]
Hi there. I'm waiting for a button to arrive in the mail, will fix this asap when it does. I think t's the action handling/bindings that are wrong but it's hard to troubleshoot without the units. Hmm, if I have not already I'll make sure latest updates get synced.

**Comment by JohanBendz** [comment]
Should now be fixed, and github is updated.
Battery info is currently not supported.
