### ISSUE TITLE
Device Request - [MOES (TUYA) ] - [TUYA] / [Zigbee, Fingerbot Button Pusher]

### ISSUE THREAD

**Issue by ocyberbum** [JohanBendz/com.tuya.zigbee#593]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: [MOES Tuya Fingerbot]
Device Model: [Tuya Fingerbot Button, ZigBee]
Device Description: [ZigBee , Remote Touch , ON/OFF Button Pushing for Switches]
Link to device image:  https://www.aliexpress.us/item/3256805698344160.html?spm=a2g0o.detail.0.0.f9233cc88Hx2O3&mp=1&gatewayAdapt=glo2usa

Device interview:

  "ids": {
    "modelId": "TS0001",
    "manufacturerName": "_TZ3210_j4pdtz9v"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:53:19:a2:32:13",
    "networkAddress": 36842,
    "modelId": "TS0001",
    "manufacturerName": "_TZ3210_j4pdtz9v",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 36842,
        "_reserved": 18,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 0,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          6,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": true,
                "reportingConfiguration": {
                  "direction": "reported",
                  "attributeDataType": 16,
                  "minInterval": 60,
                  "maxInterval": 600,
                  "status": "SUCCESS"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 72
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3210_j4pdtz9v"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0001"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }

Additional Comments:
[Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help]
I have 3 devices , 2 Zigbee fingerbots and 1 hub, I have one fingerbot connected to my homeypro 2023 as a generic device that is used to turn off my PC, The other fingerbot is connected to the hub and linked to my Tuya IoT account that i was using with HA at one time. Main problem is that you can not set any parameters for the finger bot like mode, travel height up/down etc
 

bought
Zigbee Fingerbot
https://www.aliexpress.us/item/3256805698344160.html?spm=a2g0o.order_list.order_list_main.5.351c1802q8as3O&gatewayAdapt=glo2usa
Hub
https://www.amazon.com/dp/B09TZH95FG?ref=ppx_yo2ov_dt_b_product_details&th=1

on order:
Another version of fingerbot with USB-C/ rechargeable
https://www.aliexpress.us/item/3256805974075991.html?spm=a2g0o.detail.0.0.65099UJU9UJUcj&mp=1&gatewayAdapt=glo2usa

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.tuya.zigbee/issues/869
