### ISSUE TITLE
Device Request - Water Leakage Sensor with Alarm Siren - _TZ3000_mugyhz0q / TS0207

### ISSUE THREAD

**Issue by obetsak** [JohanBendz/com.tuya.zigbee#594]
Device Name: ONENUO Water Leakage Sensor with Alarm Siren
Device Model: _TZ3000_mugyhz0q
Device Description: Water Detector Leakage Sensor with 80DB Alarm siren
Link to device image: https://ae01.alicdn.com/kf/S84f91d7629f34224a61c2a6d651d5bf8Q/ONENUO-Tuya-Zigbee-Water-Detector-Leakage-Sensor-Alarm-Leak-Detector-80DB-Sound-Smart-Life-APP-Flood.jpg_.webp

Device Interview:
`
  "ids": {
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_mugyhz0q"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:43:a1:01:dd:2e",
    "networkAddress": 11257,
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_mugyhz0q",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 11257,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "identify": {},
          "iasZone": {},
          "basic": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }`

Additional Comments:
Bought at aliexpress. https://www.aliexpress.com/item/1005005942082875.html
Same as _TZ3000_upgcbody but with alarm siren

**Comment by JohanBendz** [comment]
added to next release, but I see no way to trigger the siren from Homey so I guess it's not an option to trigger/silence the siren other than getting the device wet/dry.

**Comment by obetsak** [comment]
Didnt even think that would be possible so havent looken in to it. Just saw as a extra safety if the integration fir som reason fail at the wrong time.
