### ISSUE TITLE
RGB light bars do not change color

### ISSUE THREAD

**Issue by Malalicious** [JohanBendz/com.tuya.zigbee#60]
Setting the color of the RGB light bars from LIDL does not seem to work. It simply does not update the color.
I've tried to debug the problem a little but I am assuming this may be an issue in the way Homey handles the colors:

I tried:
- Added directly to Homey using this app
- Added to Philips Hue and using the Philips Hue Homey app, I added the device

In neither scenario does the light bar change colors. Changing brightness seems to work.

**Comment by JohanBendz** [comment]
Hi @Malalicious. Have you tried interviewing the device after adding it to this app and then restart this app?  https://developer.athom.com/tools/zigbee

**Comment by Malalicious** [comment]
So strange. Interviewing the device fixed the issue. Curious as to why that's a thing :)
