### ISSUE TITLE
Device Request - LCD Temperature and Humidity Sensor - _TZ3000_bjawzodf / TY0201

### ISSUE THREAD

**Issue by finnamu** [JohanBendz/com.tuya.zigbee#604]
Device Name: LCD Temperature and Humidity Sensor
Device Model: TY0201
Device Description: LCD Temperature and Humidity Sensor
Link to device image: https://apps-cdn.athom.com/app/com.tuya.zigbee/77/960a9b04-d182-4c64-b66f-91a0ea332dbd/drivers/lcdtemphumidsensor_3/assets/images/large.png

Device Interview:
  "ids": {
    "modelId": "TY0201",
    "manufacturerName": "_TZ3000_bjawzodf"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:5a:0c:07:62:40",
    "networkAddress": 4526,
    "modelId": "TY0201",
    "manufacturerName": "_TZ3000_bjawzodf",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 4526,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 770,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [
          0,
          1,
          3,
          1026,
          1029
        ],
        "outputClusters": [
          25
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND"
          },
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 32,
                "name": "batteryVoltage"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 58
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {},
          "temperatureMeasurement": {},
          "relativeHumidity": {}
        },
        "bindings": {
          "ota": {}
        }
      }
    }
  }

Additional Comments:
(https://www.aliexpress.com/item/1005005951863680.html?spm=a2g0o.order_list.order_list_main.24.443b1802CjUSVR)

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by obetsak** [comment]
I got this device today and have managed to get the temperature and humidity reporting working but not the battery level or alarm. was about to make a pull request to add this as a new device but are struggling to create a pull request that only includes this change.  I have a similar sensor since before but this specific sensor doesn't accept the attributereportconfiguration for some reason so it looks like batterystatus isn't reported so far anyway.

**Comment by Gizmopower1** [comment]
Please add this. It is the same as:
“ids”: {
“modelId”: “TS0601”,
“manufacturerName”: “_TZE200_bjawzodf”

**Comment by Gizmopower1** [comment]
> I got this device today and have managed to get the temperature and humidity reporting working but not the battery level or alarm. was about to make a pull request to add this as a new device but are struggling to create a pull request that only includes this change. I have a similar sensor since before but this specific sensor doesn't accept the attributereportconfiguration for some reason so it looks like batterystatus isn't reported so far anyway.

How did you make it work? I have 10 of these and impossible to pair.
I dont think its even included in the app yet...

**Comment by gabrielczubak** [comment]
> > I got this device today and have managed to get the temperature and humidity reporting working but not the battery level or alarm. was about to make a pull request to add this as a new device but are struggling to create a pull request that only includes this change. I have a similar sensor since before but this specific sensor doesn't accept the attributereportconfiguration for some reason so it looks like batterystatus isn't reported so far anyway.
> 
> How did you make it work? I have 10 of these and impossible to pair. I dont think its even included in the app yet...

I used the code from [here](https://github.com/JohanBendz/com.tuya.zigbee/pull/607) and it worked for me (without reporting the battery).

This is now quite a frequently sold device. It would be good to see it in this app. I am waiting for this!

**Comment by Gizmopower1** [comment]
> > > I got this device today and have managed to get the temperature and humidity reporting working but not the battery level or alarm. was about to make a pull request to add this as a new device but are struggling to create a pull request that only includes this change. I have a similar sensor since before but this specific sensor doesn't accept the attributereportconfiguration for some reason so it looks like batterystatus isn't reported so far anyway.
> > 
> > 
> > How did you make it work? I have 10 of these and impossible to pair. I dont think its even included in the app yet...
> 
> I used the code from [here](https://github.com/JohanBendz/com.tuya.zigbee/pull/607) and it worked for me (without reporting the battery).
> 
> This is now quite a frequently sold device. It would be good to see it in this app. I am waiting for this!

Would you mind link or share how to use the code?
I think I did something similar, but many years ago. Cant remember now..

**Comment by gabrielczubak** [comment]
> > > > I got this device today and have managed to get the temperature and humidity reporting working but not the battery level or alarm. was about to make a pull request to add this as a new device but are struggling to create a pull request that only includes this change. I have a similar sensor since before but this specific sensor doesn't accept the attributereportconfiguration for some reason so it looks like batterystatus isn't reported so far anyway.
> > > 
> > > 
> > > How did you make it work? I have 10 of these and impossible to pair. I dont think its even included in the app yet...
> > 
> > 
> > I used the code from [here](https://github.com/JohanBendz/com.tuya.zigbee/pull/607) and it worked for me (without reporting the battery).
> > This is now quite a frequently sold device. It would be good to see it in this app. I am waiting for this!
> 
> Would you mind link or share how to use the code? I think I did something similar, but many years ago. Cant remember now..

I created the Tuya application as a separate application in the development version (copied the code of the whole application, added [this code](https://github.com/JohanBendz/com.tuya.zigbee/pull/607) to it and ran it).
[Here how to run such a custom application](https://youtu.be/v_RUamZzby8?si=JOmRPh9FF5xxF824).
