### ISSUE TITLE
switch_1_gang and switch_2_gang as class socket instead of light

### ISSUE THREAD

**Issue by MarcoGos** [JohanBendz/com.tuya.zigbee#61]
When using the switch 1-gang or switch-2 gang behind a wall outlet to switch for instance a connected pump, it will show up as a light. It will also show up as a light in HomeKit. It would be very useful if these switches are class socket. You would be able to set the "What's plugged in?"-setting. So hereby a request to change the class in the driver.compose.json files to "socket".
PS. I already tested it by installing a modified version via CLI.

**Comment by JohanBendz** [comment]
OK, changed in next release for all switches,
