### ISSUE TITLE
Device Request - [Temperature Humidity Sensor Fridge] - [_TZE204_upagmta9] / [TS0601]

### ISSUE THREAD

**Issue by Majkl-M** [JohanBendz/com.tuya.zigbee#660]
Device Name: [[Temperature Humidity Sensor Fridge]
Device Model: [TS0601 _TZE204_upagmta9 ]
Link to device image: 
[https://www.aliexpress.com/item/1005004666251263.html?spm=a2g0o.order_list.order_list_main.49.281c1802ySx95v]

Device Interview:

  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_upagmta9"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:db:53:63:13:b7",
    "networkAddress": 61282,
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_upagmta9",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 61282,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {},
          "basic": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }

**Comment by PiTRiS87** [comment]
Does not seem to work. Only error when running app from command line i see:
2024-09-30T21:48:20.175Z [log] [ManagerDrivers] [Driver:lcdtemphumidsensor_3] [Device:dded030a-2b54-4b29-a3e5-eab8c32eb65c] Received end device announce indication
  zigbee-clusters:endpoint ep: 1, cl: time (10), error while handling frame binding_unavailable {
  meta: { dstEndpoint: 1 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [  ],
    trxSequenceNumber: 161,
    cmdId: 0,
    data: <Buffer 07 00>
  }
}

**Comment by JohanBendz** [comment]
Hi @PiTRiS87, looks like the same ID is used for several models.. I will move it to a driver that will work but the image will be wrong.. if you are ok with this :)

**Comment by PiTRiS87** [comment]
@JohanBendz sure, why not :) I will try to find it and try again, as I threw it away as it was chewing through a battery a week :D hopefully it was due to the zigbee driver...
