### ISSUE TITLE
Feature Request - Please add temp hum sensor [TUYATEC-HaoiuWzy	RH3052]

### ISSUE THREAD

**Issue by jtebbens** [JohanBendz/com.tuya.zigbee#669]
**Is your feature request related to a problem or is it a nice addition? Please describe.**

Please add temperature / Hum sensor type:
TUYATEC-HaoiuWzy	RH3052

**Describe the solution you'd like**
Sensor support addition

**Describe alternatives you've considered**

**Additional context**

**Comment by obetsak** [comment]
@jtebbens if you are not sure this is just another id for already existing device it is better to add an issue of type "new device" since then you will get the template for the information needed but you need to add zigbee interview with the device from homey  https://tools.developer.homey.app/

**Comment by jtebbens** [comment]
Appologies, yeah I noticed I've used the wrong template. Let me request again.

**Comment by jtebbens** [comment]
I cant generate the interview as the device is in a recreation spot so remotely connecting/pairing it again takes time.
