### ISSUE TITLE
Device Request - [Smart Home Door Sensor Zigbee] - _TZ3000_a33rw7ou / TS0203

### ISSUE THREAD

**Issue by SparklingKnuckle69** [JohanBendz/com.tuya.zigbee#684]
Device Name: Smart Home Door Sensor Zigbee
Device Model: TS0203
Device Description: [Tuya Smart door magnet sensor Zigbee]
Link to device image: https://www.aliexpress.com/item/1005005427105167.html

Device Interview:

  "ids": {
    "modelId": "TS0203",
    "manufacturerName": "_TZ3000_a33rw7ou"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:dd:85:0f:fa:10",
    "networkAddress": 20005,
    "modelId": "TS0203",
    "manufacturerName": "_TZ3000_a33rw7ou",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 20005,
        "_reserved": 32,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          3,
          4,
          5,
          6,
          8,
          4096,
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "identify": {
            "attributes": []
          },
          "iasZone": {},
          "basic": {}
        },
        "bindings": {
          "identify": {
            "attributes": []
          },
          "groups": {},
          "scenes": {},
          "onOff": {},
          "levelControl": {},
          "touchlink": {},
          "ota": {},
          "time": {}
        }
      }
    }
  }

Additional Comments:
https://www.aliexpress.com/item/1005005427105167.html

**Comment by JohanBendz** [comment]
Adde to next release.
