### ISSUE TITLE
Device Request - [Device name] - [manufacturerName] / [modelId]

### ISSUE THREAD

**Issue by gvanhartevelt** [JohanBendz/com.tuya.zigbee#685]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: [Scene Switch]
Device Model: [4 button]
Device Description: [Switch with 4 buttons]
Link to device image: [![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/156919996/e4fbbaf7-f8de-461c-8712-c55e2bd7cf7b)Provide the URL to an image/photo of the device]

Device Interview:
[Paste the device interview information here]

Additional Comments:
[Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help]

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by JohanBendz** [comment]
@gvanhartevelt, without Device Interview I have nothing to work with..
