### ISSUE TITLE
The AM43 Blinds Drive Tuya Zigbee

### ISSUE THREAD

**Issue by eeckelaertyannick** [JohanBendz/com.tuya.zigbee#70]
![9803BFBD-CCBB-440B-9A33-FB5A2B768FC3](https://user-images.githubusercontent.com/82699595/119553160-a9b93580-bd9b-11eb-9110-4288b37c4aef.png)

Hi,

can you add support for the AM43 Blinds drive. Dit not find it in the app en i just bought 3. The are working fine but want to use them with Homey.

thx in advance 

grtz Yannick

€ 44,39  65％ Off | Tuya Zigbee Roller Schaduw Driver Smart Keten Jaloezieën Motor Schaduw Roller Ingebouwde Batterij Controle Via Alexa Google Home Smartthings
https://a.aliexpress.com/_mrtzwOt

**Comment by JohanBendz** [comment]
Hi @eeckelaertyannick, can you please interview one device and post the data here?

**Comment by eeckelaertyannick** [comment]
Hi Johan,

Thx for the quik response.
I hope I dit this right. First time.
Just learning ho to use Homey en dev. Mode etc.
Newbe :)



  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_zah67ekd"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          4,
          5,
          61184
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 71
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE200_zah67ekd"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65504
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65505
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "time": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      }
    }
  }

Met vriendelijke groet,

Yannick Eeckelaert

**Comment by eeckelaertyannick** [comment]
Hey Johan,

Did you have some news for me?
Or need more data? Thx in advance!

Met vriendelijke groet,

Yannick Eeckelaert

**Comment by eeckelaertyannick** [comment]
Can you give me an update Johan?

**Comment by provanguard** [comment]
Hello, I would like to ask if support for this device is expected soon? I am looking to automate my existing blinds and this devices seems to be optimal - zigbee protocol with potentially only local, direct control from Homey.

**Comment by eeckelaertyannick** [comment]
I hope sow 2 i have 3 device but no support jet.... i do not know of Johan is still working in the app. It dit not an answer in mondts

**Comment by provanguard** [comment]
Looking at the git history, maybe SDK v3 is giving issues.

**Comment by provanguard** [comment]
@eeckelaertyannick Do you know if any other products exist that are supported in Homey?

**Comment by eeckelaertyannick** [comment]
No, :( om just waiting. Hope Johan can give an update

**Comment by JohanBendz** [comment]
"modelId": "TS0601",
    "manufacturerName": "_TZE200_rddyvrci"

**Comment by eeckelaertyannick** [comment]
Hi Johan,

Thx for the response.
But what did you mean? :)

**Comment by JohanBendz** [comment]
"modelId": "TS0601",
    "manufacturerName": "_TZE200_nueqqe6k"
    
    @eeckelaertyannick hahaha.. sorry.. :) I'm just adding codes to the info for the unit. several units will use the same driver

**Comment by eeckelaertyannick** [comment]
Ok Johan! 

Thx :) I presume that you are adding it?

Thx in advance!!!

Met vriendelijke groet,

Yannick Eeckelaert

**Comment by eeckelaertyannick** [comment]
Hey Johan same question. Is this already possible to use? I have the device four 2 j now en not connected to homey thx!

**Comment by eeckelaertyannick** [comment]
@JohanBendz Hey Johan same question. Is this already possible to use? I have the device four 2 j now en not connected to homey thx!

**Comment by eeckelaertyannick** [comment]
Thx Johan, just found out that it works on the curtain motor. 3 device work now thx! Closing now

**Comment by doxmen** [comment]
> Thx Johan, just found out that it works on the curtain motor. 3 device work now thx! Closing now

Hi Johan, i'm using the same devices and my homey doesn't reconize the dives. They carry the same manuafacture and deviceID... Which device from de homey app did you use?

**Comment by Bomben1** [comment]
Is it possible to add Tuya AM43 in homey?
