### ISSUE TITLE
SMOKE & CO SENSOR

### ISSUE THREAD

**Issue by Merk72** [JohanBendz/com.tuya.zigbee#704]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: [[Aggiungi recensione](https://www.amazon.it/review/review-your-purchases/?asin=B0CGX1D8F6&channel=dp_poi&ref_=dp_poi_reviews)
Marca: Runidur
RUNIDUR WLAN Rilevatore di Fumo e CO Combinato Wifi, Rilevatore di Fumo Combinato Intelligente e Rilevatore di Monossido di Carbonio, Sensore Preciso con Batteria da 10]
Device Model: [Provide the model number or identifier]
Device Description: [Describe in short the functionality of the device]
Link to device image: [Provide the URL to an image/photo of the device]

Device Interview:
[Paste the device interview information here]

Additional Comments:
[Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help]

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

**Comment by obetsak** [comment]
There is not enough information in this issue to add the device.
You need to add a product interview and the more information provide the easier is it to add the device.
You link is not working but from the product description it doesn't look like this is even a zigbee device.

**Comment by Merk72** [comment]
I bought this device because I read that it is possible inserts in app Tuya or smart life and so I thought to can put it on my homey pro early 2023 with your app for homey TUYA CLOUD.I have already insert it in smart life and it work well but when I go in your app on homey pro it is not possible to found it.This is all informations and specification of product:[Funzione Wi-Fi]: I rilevatori intelligenti di fumo e monossido di carbonio con funzione Wi-Fi offrono maggiore sicurezza attraverso funzioni come notifiche istantanee di allarme sullo smartphone e monitoraggio remoto. Permettono di essere avvisati il più rapidamente possibile e di rispondere adeguatamente in caso di incendio o livelli elevati di monossido di carbonio, migliorando la sicurezza[Doppia protezione]: Questo rilevatore di fumo e CO WiFi combina un sensore di fumo fotoelettrico e un sensore di CO elettrochimico. Il sistema 2 in 1 consente di risparmiare spazio ed è economico. Ti avvisa immediatamente quando viene rilevato fumo pericoloso o livelli elevati di monossido di carbonio, garantendo la protezione della tua famiglia[Batteria a lunga durata]: Questo rilevatore intelligente di fumo e monossido di carbonio.Batteria al litio CR17505 da 3V incorporata per alimentazione continua di 10 anni, efficienza energetica e rispetto dell'ambiente, tempo di attesa estremamente lungo. Fornisce a te e alla tua famiglia un ambiente di sonno sicuro[Design piatto]: Grazie al suo design sottile, questo rilevatore di fumo e co combina WiFi occupa poco spazio visivo e ha un aspetto attraente e semplice, in modo che possa essere ben integrato nell'ambiente[Robusto e durevole]: Questo rilevatore di fumo e monossido di carbonio WiFi utilizza materiale ABS, è ignifugo e robusto; Con un'entrata circolare a 360°, in caso di emergenza invia un allarme in modo preciso e affidabile con un volume di oltre 85 dBMostra menoSpecifiche del prodotto Produttore‎Runidur Codice articolo ‎CS12W Dimensioni prodotto ‎12 x 12 x 2,8 cm; 136 grammi Pile ‎1 Metallo al litio pile necessarie. (incluse) Numero modello articolo ‎CS12W Voltaggio ‎3 Volt (CC) Numero di articoli‎1 Batterie/Pile incluse? ‎Sì Batterie/Pile necessarie? ‎Sì Peso articolo ‎136 g Ulteriori informazioniASIN:  B0CGX1D8F6Posizione nella classifica Bestseller di Amazon: n. 12,779 in Fai da te (Visualizza i Top 100 nella categoria Fai da te) n. 4 in Rilevatori di fumo e monossido di carbonioDisponibile su Amazon.it a partire dal:  30 agosto 2023Tell me what other informations could be help.Thanks for your reply and sorry if I don’t speak and write well in English Marco SacchiOn 29 Jan 2024, at 19:29, Jonas Kastebo ***@***.***> wrote:﻿
There is not enough information in this issue to add the device.
You need to add a product interview and the more information provide the easier is it to add the device.
You link is not working but from the product description it doesn't look like this is even a zigbee device.

**Comment by Merk72** [comment]
﻿﻿I bought this device because I read that it is possible inserts in app Tuya or smart life and so I thought to can put it on my homey pro early 2023 with your app for homey TUYA CLOUD.I have already insert it in smart life and it work well but when I go in your app on homey pro it is not possible to found it.This is all informations and specification of product:[Funzione Wi-Fi]: I rilevatori intelligenti di fumo e monossido di carbonio con funzione Wi-Fi offrono maggiore sicurezza attraverso funzioni come notifiche istantanee di allarme sullo smartphone e monitoraggio remoto. Permettono di essere avvisati il più rapidamente possibile e di rispondere adeguatamente in caso di incendio o livelli elevati di monossido di carbonio, migliorando la sicurezza[Doppia protezione]: Questo rilevatore di fumo e CO WiFi combina un sensore di fumo fotoelettrico e un sensore di CO elettrochimico. Il sistema 2 in 1 consente di risparmiare spazio ed è economico. Ti avvisa immediatamente quando viene rilevato fumo pericoloso o livelli elevati di monossido di carbonio, garantendo la protezione della tua famiglia[Batteria a lunga durata]: Questo rilevatore intelligente di fumo e monossido di carbonio.Batteria al litio CR17505 da 3V incorporata per alimentazione continua di 10 anni, efficienza energetica e rispetto dell'ambiente, tempo di attesa estremamente lungo. Fornisce a te e alla tua famiglia un ambiente di sonno sicuro[Design piatto]: Grazie al suo design sottile, questo rilevatore di fumo e co combina WiFi occupa poco spazio visivo e ha un aspetto attraente e semplice, in modo che possa essere ben integrato nell'ambiente[Robusto e durevole]: Questo rilevatore di fumo e monossido di carbonio WiFi utilizza materiale ABS, è ignifugo e robusto; Con un'entrata circolare a 360°, in caso di emergenza invia un allarme in modo preciso e affidabile con un volume di oltre 85 dBMostra menoSpecifiche del prodotto Produttore‎Runidur Codice articolo ‎CS12W Dimensioni prodotto ‎12 x 12 x 2,8 cm; 136 grammi Pile ‎1 Metallo al litio pile necessarie. (incluse) Numero modello articolo ‎CS12W Voltaggio ‎3 Volt (CC) Numero di articoli‎1 Batterie/Pile incluse? ‎Sì Batterie/Pile necessarie? ‎Sì Peso articolo ‎136 g Ulteriori informazioniASIN:  B0CGX1D8F6Posizione nella classifica Bestseller di Amazon: n. 12,779 in Fai da te (Visualizza i Top 100 nella categoria Fai da te) n. 4 in Rilevatori di fumo e monossido di carbonioDisponibile su Amazon.it a partire dal:  30 agosto 2023Tell me what other informations could be help.Thanks for your reply and sorry if I don’t speak and write well in English Marco SacchiOn 29 Jan 2024, at 19:29, Jonas Kastebo ***@***.***> wrote:﻿
There is not enough information in this issue to add the device.
You need to add a product interview and the more information provide the easier is it to add the device.
You link is not working but from the product description it doesn't look like this is even a zigbee device.

**Comment by obetsak** [comment]
I not sure where you read that it supported tuya and since there is nothing in your description that says that. But even if it did this app will not support wifi devices you need to talk to the developer of the tuya cloud app to the tuya zugbee app. https://homey.app/sv-se/app/com.tuya.cloud/Tuya-cloud/

**Comment by Merk72** [comment]
I send you a photo where I read or I see that the product can work with Tuya app or Smart Life.Marco SacchiOn 30 Jan 2024, at 01:33, Jonas Kastebo ***@***.***> wrote:﻿
I not sure where you read that it supported tuya and since there is nothing in your description that says that. But even if it did this app will not support wifi devices you need to talk to the developer of the tuya cloud app to the tuya zugbee app. https://homey.app/sv-se/app/com.tuya.cloud/Tuya-cloud/

**Comment by obetsak** [comment]
> I send you a photo where I read or I see that the product can work with Tuya app or Smart Life.Marco SacchiOn 30 Jan 2024, at 01:33, Jonas Kastebo ***@***.***> wrote:﻿ I not sure where you read that it supported tuya and since there is nothing in your description that says that. But even if it did this app will not support wifi devices you need to talk to the developer of the tuya cloud app to the tuya zugbee app. https://homey.app/sv-se/app/com.tuya.cloud/Tuya-cloud/ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I believe you but from what i can see your device is a wifi device so this is the wrong place/app for you anyway.

But If it where a zigbee device you need to provide the information requested in the device request template otherwise no one can help you anyway since it is not possible to know that device you have even if one have a link to the page where you bought it.

**Comment by JohanBendz** [comment]
Hi @Merk72, as Jonas says above the device you have is a WiFi device and will not be supported in this app. Support for the WiFi app is found here: https://github.com/jurgenheine/com.tuya.cloud
