### ISSUE TITLE
Device Request - Tuya Temperatuur Vochtigheid Sensor - _TZE204_upagmta9 / TS0601

### ISSUE THREAD

**Issue by Tonlaar** [JohanBendz/com.tuya.zigbee#711]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Homey is upgraded to firmware v7.6.1.1408.
- I have a physical example of the device

Device Name: [Tuya Temperatuur Vochtigheid Sensor]
Device Model: [TH05S/TH05/ZTH05]
Device Description: [Tuya Temperatuur Vochtigheid Sensor Mini Lcd Digitale Display Compatibel Met Bluetooth App Afstandsbediening Thermometer Hygrometer]
Link to device image: [https://nl.aliexpress.com/item/1005004865399211.html]

Device Interview:
[  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE204_upagmta9"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "groups": {},
          "scenes": {},
          "basic": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }
]

Additional Comments:
[It is successfully added to Homey as a generic device]

**Comment by shahzadsk** [comment]
@Tonlaar  can you please edit title with device name, manufacturer / model id - will make this easier to search for :)
