### ISSUE TITLE
Device Request - Zigbee door window sensor - Conecto home _TZ3000_uvti8nkd / TS0203

### ISSUE THREAD

**Issue by Hennhal** [JohanBendz/com.tuya.zigbee#712]
"ids": {
    "modelId": "TS0203",
    "manufacturerName": "_TZ3000_uvti8nkd"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:ef:65:2f:ca:60",
    "networkAddress": 44676,
    "modelId": "TS0203",
    "manufacturerName": "_TZ3000_uvti8nkd",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 44676,
        "_reserved": 32,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          3,
          4,
          5,
          6,
          8,
          4096,
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {},
          "identify": {},
          "iasZone": {},
          "basic": {}
        },
        "bindings": {
          "identify": {},
          "groups": {},
          "scenes": {},
          "onOff": {},
          "levelControl": {},
          "touchlink": {},
          "ota": {},
          "time": {}
        }
      }
    }
  }

**Comment by JohanBendz** [comment]
Hi @Hennhal, can you please provide a url to where I can see the device?

**Comment by Hennhal** [comment]
https://www.power.no/smarte-hjem/smarte-alarmer-og-sensor/doer-og-vinduessensorer/conecto-zigbee-doer-vindussensor/p-2267902/

**Comment by Hennhal** [comment]
https://www.power.no/smarte-hjem/smarte-alarmer-og-sensor/doer-og-vinduessensorer/conecto-zigbee-doer-vindussensor/p-2267902/

**Comment by Hennhal** [comment]
> Hi @Hennhal, can you please provide a url to where I can see the device?

Hi @JohanBendz , is the device ready for use now?

**Comment by Hennhal** [comment]
Hi, @JohanBendz i can still not get this to work.
