### ISSUE TITLE
Device Request - Smart Wall Switch - _TZE200_r731zlxk / TS0601

### ISSUE THREAD

**Issue by MarceloSilvaLeite** [JohanBendz/com.tuya.zigbee#717]
- Device Name: `Smart Wall Switch`
- Device Model: `TS0601`
- Device Description: `Smart Wall Seitch 6 Gang`
- Link to device image: https://pt.aliexpress.com/item/1005004084521839.html?spm=a2g0o.order_list.order_list_main.195.d01dcaa4UIA3V5&gatewayAdapt=glo2bra
- 
### Device Interview

  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_r731zlxk"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:e3:dc:27:65:07",
    "networkAddress": 54355,
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_r731zlxk",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 54355,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 54355,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 70
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE200_r731zlxk"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite Now in test version.

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz, I have version 0.2.60 of the app installed on my Homey Pro. I tested the 6 Gang Wall Switch device and I am having issues when I press the physical keys on the device. They have a delay in the response times of the on and off status, especially key 6, for which I have no response.

Diagnostics Report
4f4d8ee9-5f5a-4c28-b034-da8a547115ad

**Comment by JohanBendz** [comment]
Hi @MarceloSilvaLeite
The diagnostic report show no errors but there are no button 5 and 6 activity.
I can see you pressed button 1, 3, 2, 4 in that order.

Can you restart the app, and press the buttons in the order below.

| Button Position           | Action    | Expected Result                         | Status |
|---------------------------|-----------|-----------------------------------------|--------|
| Button 1 (Top Left)       | Press On  | Homey shows Button 1 is ON              |        |
| Button 1 (Top Left)       | Press Off | Homey shows Button 1 is OFF             |        |
| Button 2 (Top Center)     | Press On  | Homey shows Button 2 is ON              |        |
| Button 2 (Top Center)     | Press Off | Homey shows Button 2 is OFF             |        |
| Button 3 (Top Right)      | Press On  | Homey shows Button 3 is ON              |        |
| Button 3 (Top Right)      | Press Off | Homey shows Button 3 is OFF             |        |
| Button 4 (Bottom Left)    | Press On  | Homey shows Button 4 is ON              |        |
| Button 4 (Bottom Left)    | Press Off | Homey shows Button 4 is OFF             |        |
| Button 5 (Bottom Center)  | Press On  | Homey shows Button 5 is ON              |        |
| Button 5 (Bottom Center)  | Press Off | Homey shows Button 5 is OFF             |        |
| Button 6 (Bottom Right)   | Press On  | Homey shows Button 6 is ON              |        |
| Button 6 (Bottom Right)   | Press Off | Homey shows Button 6 is OFF             |        |

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz.
I performed tests on the 6 Gang Wall Switch device, but the sequence you asked me to perform does not match the outputs described on the device. I performed the tests according to the sequence of the device. First pressing keys 1, 2, 3, 4, 5 and 6. I did not obtain the status of key 6.
Below are images of the device and position of the keys.

Diagnostics Report:
f7b6294f-ef45-41e5-9cf2-b26eb3ddb6e8

![20240925_083722](https://github.com/user-attachments/assets/7021b003-5ce4-4b52-bb6a-6f5460bdb39c)
![20240925_083742](https://github.com/user-attachments/assets/0ad2a56e-576c-415f-a26d-9268a77b6d21)

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite Found a typo, an update will come later today.

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz , I tested the device after the update and everything seems to be working correctly. Congratulations on the great work.

I hope the other devices will be added soon.

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz , after testing the 6 Gang Wall Switch and 4 Gang Wall Switch devices for a few days, I noticed that when my Homey pro Hub is updated or even when I restart it, they don't work as they should. I have to delete and then add them again to get them working properly again.

**Comment by JohanBendz** [comment]
Hmm, interesting @MarceloSilvaLeite... not expected. I'll look into it.

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite A fix in the upcoming Test version. Let me know if there are any issues.

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz, I have run some tests and everything seems to be working correctly.
