### ISSUE TITLE
Device Request - Smart Wall Switch - _TZE200_shkxsgis / TS0601

### ISSUE THREAD

**Issue by MarceloSilvaLeite** [JohanBendz/com.tuya.zigbee#718]
### Device Information

- Device Name: `Smart Wall Switch`
- Device Model: `TS0601`
- Device Description: `Smart Wall Switch 4 Gang`
- Link to device image: https://pt.aliexpress.com/item/1005004084501331.html?spm=a2g0o.order_list.order_list_main.190.d01dcaa4UIA3V5&gatewayAdapt=glo2bra

### Device Interview

  "ids": {
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_shkxsgis"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:5b:01:a2:dc:c6",
    "networkAddress": 36126,
    "modelId": "TS0601",
    "manufacturerName": "_TZE200_shkxsgis",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 36126,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 81,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          4,
          5,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 70
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZE200_shkxsgis"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0601"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }

**Comment by pw44** [comment]
any news about?

**Comment by MarceloSilvaLeite** [comment]
> alguma novidade sobre?

Hello @pw44, unfortunately there is no news so far.

**Comment by pw44** [comment]
> > alguma novidade sobre?
> 
> Hello @pw44, unfortunately there is no news so far.

solved with zigbee2mqtt - immediately recognized.

**Comment by MarceloSilvaLeite** [comment]
> > > alguma novidade sobre?
> > 
> > 
> > Hello @pw44, unfortunately there is no news so far.
> 
> solved with zigbee2mqtt - immediately recognized.

I don't have any experience with zigbee2mqtt, do you have a link so I can try to see and try to include my device?

**Comment by pw44** [comment]
https://www.zigbee2mqtt.io/

Am 06.05.24 um 12:20 schrieb MarceloSilvaLeite:

**Comment by pw44** [comment]
> > > > alguma novidade sobre?
> > > 
> > > 
> > > Hello @pw44, unfortunately there is no news so far.
> > 
> > 
> > solved with zigbee2mqtt - immediately recognized.
> 
> I don't have any experience with zigbee2mqtt, do you have a link so I can try to see and try to include my device?

https://www.zigbee2mqtt.io/

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.tuya.zigbee/issues/560

**Comment by MarceloSilvaLeite** [comment]
Hello @JohanBendz, I tried to add the device but it is not supported yet.

**Comment by MarceloSilvaLeite** [comment]
Hello Johan Bendz, I tried to add the device but it is not supported yet.
________________________________
De: Johan Bendz ***@***.***>
Enviado: quinta-feira, 12 de setembro de 2024 03:06
Para: JohanBendz/com.tuya.zigbee ***@***.***>
Cc: MarceloSilvaLeite ***@***.***>; Author ***@***.***>
Assunto: Re: [JohanBendz/com.tuya.zigbee] Device Request - Smart Wall Switch - _TZE200_shkxsgis / TS0601 (Issue #718)


Closed #718<https://github.com/JohanBendz/com.tuya.zigbee/issues/718> as completed.

**Comment by JohanBendz** [comment]
Hi @MarceloSilvaLeite, it's only in the test version so far.. coming to live in a while.
https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz, yes I am using the test version but the device is not supported yet. Version 0.2.50

**Comment by JohanBendz** [comment]
ooops, not ready.. working on this.

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite Now added :)

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite.. your device show datapoints it should not use so I will have to figure this one out.. I'll add some logging to the new update out now. no other change.. please try it and send a new diagnostic report.

Hmm, are you able to test using CLI? If so this will be a much smoother ride..

**Comment by MarceloSilvaLeite** [comment]
@JohanBendz, waiting for a new update to test on the device.

Regarding testing using the CLI, I still don't know how to use it, but I'll do some research on the subject.

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite OK, now at app store.

**Comment by MarceloSilvaLeite** [comment]
@JohanBendz I just ran the tests and the problem still persists. Remembering that I deleted the device and added it again

Diagnostics Report:
e2270597-2dd9-4835-b5bc-b6ab54172d18

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite OK, thanks.
What did you test? Pushing the buttons or trying to trigger them from the app? Or both? Just wanna understand what I see in the log.

**Comment by MarceloSilvaLeite** [comment]
@JohanBendz, I performed the tests only through the app. I'm not at home to perform the tests on the physical keys. But if you want, I can ask my daughter to test at home and I'll send you another Diagnostics Report if necessary.

**Comment by MarceloSilvaLeite** [comment]
@JohanBendz, now also testing physical keys

Diagnostics Report:
f6f49a02-32d5-48e0-b33b-1e138acadb38

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite New version out.

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz, I updated the app to version 0.2.56, removed the device from the app, disconnected it from the power grid, after a while I connected it to the power grid, added the device and added it to Homey. I tested both through the app and physically. It still doesn't work correctly, only Switch 1 responds correctly.

Diagnostics Report:
fb4d699b-27f1-4677-a403-7319f0f30547

**Comment by MarceloSilvaLeite** [comment]
@JohanBendz, The link below refers to the driver that I use for it in Hubitat, it works for both 4 and 6 channels that I also sent to add to the app. I don't know if it can help you, I hope so, I thank you in advance for your patience and time spent trying to solve the problem.

https://raw.githubusercontent.com/martinkura-svk/Hubitat/main/Moes%20ZigBee%20Wall%20Switch

**Comment by JohanBendz** [comment]
@MarceloSilvaLeite All I see in the log is the Radar Sensor.

**Comment by MarceloSilvaLeite** [comment]
@JohanBendz, I deleted the radar sensor and sent another log.

Diagnostics Report:
3889c34a-6d6e-4372-91f3-aeddb520f34d

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz, Still having issues, app version 2.57. I tested both via the app and physically. It still doesn't work properly, only Switch 1 responds correctly.

Diagnostic report:
b3ba9b7f-3115-4873-b01f-3ba5a725da34

**Comment by MarceloSilvaLeite** [comment]
Hi @JohanBendz, updated the app to version 0.2.58 and performed tests on the Wall Switch 4 Gang device, now everything works correctly. Congratulations on the great work.

**Comment by JohanBendz** [comment]
Happy everything works, always hard to add devices I can't test myself. Closing this.

**Comment by MarceloSilvaLeite** [comment]
> Happy everything works, always hard to add devices I can't test myself. Closing this.

I imagine it won't be easy. Maybe now I'll have less work when I add the 6 Gang Wall Switch, #717, since it's from the same line. I hope when I add it I won't have as much work.
