### ISSUE TITLE
Bug report - 1 button Smart Remote Controller only works every other click

### ISSUE THREAD

**Issue by sinan92** [JohanBendz/com.tuya.zigbee#747]
### Describe the bug

> A clear and concise description of what the bug is.

I have the following button:
https://nl.aliexpress.com/i/1005005266369364.html?gatewayAdapt=glo2nld

Which is: 
_TZ3000_fa9mlvja
TS0041

I added it as a 1 button Smart Remote Controller.

Added the following flow:
If :1 Click
Then: Toggle lights

When I play the flow it works great every time. When I press the button the first time it also works. The second time it does not work. Third time it works, fourth time it doesn't. Every iteration the result is the same.

### Expected behavior

I want it to toggle every click not every other click. This does work when I press the flow directly in the app.

### App and Homey version

> * What Homey version are you running?
Homey Pro 2019
> * What version of Homey firmware do you use?
Latest
> * What version of the Tuya Zigbee App are you using?
0.2.25

**Comment by eelco2k** [comment]
Nice work @sinan92 😜😉
