### ISSUE TITLE
Bug report - Not presence/motion detection Tuya/Loginovo 24G Zigbee ceiling version

### ISSUE THREAD

**Issue by roberto2391** [JohanBendz/com.tuya.zigbee#748]
### Describe the bug

Clear and detailed bug explained here with screenshots: https://community.homey.app/t/app-pro-tuya-zigbee-app/26439/4620?u=roberto2391

### To Reproduce

1. Go to the device
2. Click on radar device sensor
3. No updates related to presence/motion
![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/44460712/babd3f99-16c8-4c39-88d7-aa3b5068be37)

### Expected behavior

It is expected to detect presence/motion sensor but nothing happens, on the other hand the luminance is working fine.
![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/44460712/a85d09f9-3895-4d7b-aad9-28018819204d)

### App and Homey version

> * What Homey version are you running? 10.3.0
> * What version of Homey firmware do you use? 18.19.0
> * What version of the Tuya Zigbee App are you using? 0.2.25
### Screenshots

Added here in the following comment-> 
(https://community.homey.app/t/app-pro-tuya-zigbee-app/26439/4620?u=roberto2391)

### Additional context

My zigbee device is on ceiling mount 2,5 meters height.

Interview made to this zigbee device:

“ids”: {
“modelId”: “TS0601”,
“manufacturerName”: “_TZE204_ijxvkhd0”
},
“endpoints”: {
“ieeeAddress”: “a4:c1:38:30:1b:0d:d2:26”,
“networkAddress”: 57820,
“modelId”: “TS0601”,
“manufacturerName”: “_TZE204_ijxvkhd0”,
“endpointDescriptors”: [
{
“status”: “SUCCESS”,
“nwkAddrOfInterest”: 57820,
“_reserved”: 20,
“endpointId”: 1,
“applicationProfileId”: 260,
“applicationDeviceId”: 81,
“applicationDeviceVersion”: 0,
“_reserved1”: 1,
“inputClusters”: [
4,
5,
61184,
0
],
“outputClusters”: [
25,
10
]
},
{
“status”: “SUCCESS”,
“nwkAddrOfInterest”: 57820,
“_reserved”: 10,
“endpointId”: 242,
“applicationProfileId”: 41440,
“applicationDeviceId”: 97,
“applicationDeviceVersion”: 0,
“_reserved1”: 0,
“inputClusters”: ,
“outputClusters”: [
33
]
}
],
“deviceType”: “router”,
“receiveWhenIdle”: true,
“capabilities”: {
“alternatePANCoordinator”: false,
“deviceType”: true,
“powerSourceMains”: true,
“receiveWhenIdle”: true,
“security”: false,
“allocateAddress”: true
},
“extendedEndpointDescriptors”: {
“1”: {
“clusters”: {
“groups”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“name”: “nameSupport”,
“value”: {
“type”: “Buffer”,
“data”: [
0
]
},
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 2,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
}
]
},
“scenes”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 1,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 2,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 3,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 4,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 2,
“reportingConfiguration”: {
“status”: “NOT_FOUND”,
“direction”: “reported”
}
}
]
},
“basic”: {
“attributes”: [
{
“acl”: [
“readable”,
“reportable”
],
“id”: 0,
“name”: “zclVersion”,
“value”: 3
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 1,
“name”: “appVersion”,
“value”: 74
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 2,
“name”: “stackVersion”,
“value”: 0
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 3,
“name”: “hwVersion”,
“value”: 1
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 4,
“name”: “manufacturerName”,
“value”: “_TZE204_ijxvkhd0”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 5,
“name”: “modelId”,
“value”: “TS0601”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 6,
“name”: “dateCode”,
“value”: “”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 7,
“name”: “powerSource”,
“value”: “mains”
},
{
“acl”: [
“readable”,
“writable”,
“reportable”
],
“id”: 65502
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 2
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65534,
“name”: “attributeReportingStatus”,
“value”: “PENDING”
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65506
},
{
“acl”: [
“readable”,
“reportable”
],
“id”: 65507
}
]
}
},
“bindings”: {
“ota”: {},
“time”: {
“attributes”: [
{
“acl”: [
“readable”
],
“id”: 65533,
“name”: “clusterRevision”,
“value”: 1
}
]
}
}
},
“242”: {
“clusters”: {},
“bindings”: {}
}
}
}

**Comment by shaarkys** [comment]
https://github.com/shaarkys/com.tuya.zigbee/commit/976d3c716ee235a9a93e658136fd55cbb88cc8d5

**Comment by roberto2391** [comment]
Hello @shaarkys do you know when you will do the pull request in order to fix this bug from my device as radar sensor 2? thanks in advance.

**Comment by shaarkys** [comment]
I don't.

**Comment by roberto2391** [comment]
so, please could you share how to fix from my side with your solution now?

**Comment by shaarkys** [comment]
Yes, I did already.

**Comment by roberto2391** [comment]
so, could you update a new test tuya zigbee app version with the solution provided for my device as radar sensor 2? thanks

**Comment by shaarkys** [comment]
nope, I can't (not developer) + as you can see, there are 400 issues to be updated.
The fastest and easiest solution has been already offered to you - if you are not okay with that, then please wait until developer (Johan) will push the updates. In the meantime, you can maybe take a look on the Paypal link for Johan and send him your wishes 

_Note : I will be not answering on any other non relevant question, thank you._

**Comment by roberto2391** [comment]
Bug fixed, thanks!

> [shaarkys@976d3c7](https://github.com/shaarkys/com.tuya.zigbee/commit/976d3c716ee235a9a93e658136fd55cbb88cc8d5)
