### ISSUE TITLE
Dos not work

### ISSUE THREAD

**Issue by ghost** [JohanBendz/com.tuya.zigbee#75]
Tuya Smart Zigbee Plug 16A Eu Outlet 3680W Power Meter Compatiable Met Alexa Zigbee2mqtt Home Assistent En Tuya Hub

€ 9,36  36%OFF | Tuya Smart Zigbee Plug 16A Eu Outlet 3680W Power Meter Compatiable Met Alexa Zigbee2mqtt Home Assistent En Tuya Hub
https://a.aliexpress.com/_mKCatTT

**Comment by Sufkonijn** [comment]
This is the #89 TS011F _TZ3000_cphmq0q7

**Comment by JohanBendz** [comment]
Added to next release.
