### ISSUE TITLE
Bug report - Zigbee Curtain module does not work

### ISSUE THREAD

**Issue by F201181** [JohanBendz/com.tuya.zigbee#756]
### Describe the bug

I bought a new curtain module but is not recognized well in the Tuya Zigbee app. The devices is added as a power switch in case of a curtain module. In the live version and in the experimental version the same behavior.

I've noticed in the following issue that the device is added in September 2023;
https://github.com/JohanBendz/com.tuya.zigbee/issues/361

### To Reproduce

1. Add device
2. Select the Tuya zigbee app
3. Put the curtain module in paring mode
4. The device is added as a power switch because the device "curtain module" is not recognized

### Expected behavior

That the device is added as a curtain switch / module

### App and Homey version

> * What Homey version are you running?
10.3.0
> * What version of Homey firmware do you use?
10.3.0
> * What version of the Tuya Zigbee App are you using?
Experimental v0.2.25
### Screenshots

> If applicable, add screenshots to help explain your problem.

### Additional context

> Add any other context about the problem here.

**Comment by JohanBendz** [comment]
If your device is _TZ3210_dwytrmda it is already added.
