### ISSUE TITLE
Feature Request - [Short description]

### ISSUE THREAD

**Issue by dyrvigk** [JohanBendz/com.tuya.zigbee#763]
this is a 4 button  device from foss fesh same model ts0044 as many other 4 button tuya devices but not reconiced using test version 
_TZ3000_jcspr0tp
Produkt-id
TS0044

⨯
Device Type
enddevice
Enheds-id
a4:c1:38:29:6f:ab:f9:7c

**Comment by JohanBendz** [comment]
Hi @dyrvigk, since a Tuya device can be just about anything I would like some more info, best is to attach an interview but at least let me know what kind of device you have. Is it a grid powered wall switch or a battery operated button? Since your info states "enddevice" I guess button...

**Comment by dyrvigk** [comment]
> Hi @dyrvigk, since a Tuya device can be just about anything I would like some more info, best is to attach an interview but at least let me know what kind of device you have. Is it a grid powered wall switch or a battery operated button? Since your info states "enddevice" I guess button...

yes i have one that works  Producent-id
_TZ3000_wkai4ga5
Produkt-id
TS0044
Modtag, når den er inaktiv
⨯
Device Type
enddevice
Enheds-id
f0:82:c0:ff:fe:0a:29:b7

the other one i can find in zigbee2mqtt and also i homey but it should have 4 buttons  with 1 short press 1 long press and 1 hold and same for teh 3 other buttons   it is from foss fesh 

 Last seen
N/A
Availability
[Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type
EndDevice
Zigbee Model
TS0044
Zigbee Manufacturer
_TZ3000_jcspr0tp
Description
Wireless switch with 4 buttons
Support status
Supported

IEEE Address
0xa4c138296fabf97c
Network address
0x8326
Manufacturer
[TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model
[TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html#tuya-ts0044)
Power
Battery 
Interview completed
True

**Comment by dyrvigk** [comment]
here is more info from zigbee2mqtt 

 zigbeeModel: ['TS0044'],
    model: 'TS0044',
    vendor: '_TZ3000_jcspr0tp',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4}}), batteryPercentage(), onOff({"powerOnBehavior":false,"endpoints":{"1":1,"2":2,"3":3,"4":4}})],
    meta: {"multiEndpoint":true},

it dosent work in zigbee2mqtt also 


_TZ3000_jcspr0tp
Produkt-id
TS0044
Modtag, når den er inaktiv
⨯
Device Type
enddevice
Enheds-id
a4:c1:38:29:6f:ab:f9:7c

**Comment by dyrvigk** [comment]
it finds it as a socket outlet

**Comment by dyrvigk** [comment]
here is the interview i dont know how to get that from homey 

Zigbee2MQTT:info  2024-02-25 19:56:06: Device '0xa4c138296fabf97c' joined
Zigbee2MQTT:info  2024-02-25 19:56:06: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138296fabf97c","ieee_address":"0xa4c138296fabf97c"},"type":"device_joined"}'
Zigbee2MQTT:info  2024-02-25 19:56:06: Starting interview of '0xa4c138296fabf97c'
Zigbee2MQTT:info  2024-02-25 19:56:06: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138296fabf97c","ieee_address":"0xa4c138296fabf97c","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2024-02-25 19:56:06: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138296fabf97c","ieee_address":"0xa4c138296fabf97c"},"type":"device_announce"}'
Zigbee2MQTT:info  2024-02-25 19:56:14: Successfully interviewed '0xa4c138296fabf97c', device has successfully been paired
Zigbee2MQTT:info  2024-02-25 19:56:14: Device '0xa4c138296fabf97c' is supported, identified as: TuYa Wireless switch with 4 buttons (TS0044)
Zigbee2MQTT:info  2024-02-25 19:56:14: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Wireless switch with 4 buttons","exposes":[{"access":1,"category":"diagnostic","description":"Remaining battery in %, can take up to 24 hours before reported","label":"Battery","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","label":"Action","name":"action","property":"action","type":"enum","values":["1_single","1_double","1_hold","2_single","2_double","2_hold","3_single","3_double","3_hold","4_single","4_double","4_hold"]},{"access":1,"category":"diagnostic","description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0044","options":[],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0xa4c138296fabf97c","ieee_address":"0xa4c138296fabf97c","status":"successful","supported":true},"type":"device_interview"}'
Zigbee2MQTT:info  2024-02-25 19:56:14: Configuring '0xa4c138296fabf97c'
Zigbee2MQTT:info  2024-02-25 19:56:14: MQTT publish: topic 'homeassistant/sensor/0xa4c138296fabf97c/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c138296fabf97c"],"manufacturer":"TuYa","model":"Wireless switch with 4 buttons (TS0044)","name":"0xa4c138296fabf97c","via_device":"zigbee2mqtt_bridge_0x00124b0021cbf123"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0xa4c138296fabf97c","object_id":"0xa4c138296fabf97c_battery","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0xa4c138296fabf97c","unique_id":"0xa4c138296fabf97c_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Zigbee2MQTT:info  2024-02-25 19:56:14: MQTT publish: topic 'homeassistant/sensor/0xa4c138296fabf97c/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c138296fabf97c"],"manufacturer":"TuYa","model":"Wireless switch with 4 buttons (TS0044)","name":"0xa4c138296fabf97c","via_device":"zigbee2mqtt_bridge_0x00124b0021cbf123"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/0xa4c138296fabf97c","name":"Action","object_id":"0xa4c138296fabf97c_action","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0xa4c138296fabf97c","unique_id":"0xa4c138296fabf97c_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Zigbee2MQTT:info  2024-02-25 19:56:14: MQTT publish: topic 'homeassistant/sensor/0xa4c138296fabf97c/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c138296fabf97c"],"manufacturer":"TuYa","model":"Wireless switch with 4 buttons (TS0044)","name":"0xa4c138296fabf97c","via_device":"zigbee2mqtt_bridge_0x00124b0021cbf123"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0xa4c138296fabf97c","name":"Linkquality","object_id":"0xa4c138296fabf97c_linkquality","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0xa4c138296fabf97c","unique_id":"0xa4c138296fabf97c_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2024-02-25 19:56:14: Successfully configured '0xa4c138296fabf97c'
Zigbee2MQTT:info  2024-02-25 20:00:50: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/generate_external_definition', payload '{"data":{"id":"0xa4c138296fabf97c","source":"const {deviceEndpoints, batteryPercentage, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');\n\nconst definition = {\n    zigbeeModel: ['TS0044'],\n    model: 'TS0044',\n    vendor: '_TZ3000_jcspr0tp',\n    description: 'Automatically generated definition',\n    extend: [deviceEndpoints({\"endpoints\":{\"1\":1,\"2\":2,\"3\":3,\"4\":4}}), batteryPercentage(), onOff({\"powerOnBehavior\":false,\"endpoints\":{\"1\":1,\"2\":2,\"3\":3,\"4\":4}})],\n    meta: {\"multiEndpoint\":true},\n};\n\nmodule.exports = definition;"},"status":"ok","transaction":"92p5v-2"}'
Zigbee2MQTT:info  2024-02-25 20:10:39: Configuring '0xa4c138296fabf97c'
Zigbee2MQTT:error 2024-02-25 20:11:09: Failed to configure '0xa4c138296fabf97c', attempt 1 (Error: Read 0xa4c138296fabf97c/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:466:28)
    at Object.configureMagicPacket [as configure] (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:378:9)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
Zigbee2MQTT:info  2024-02-25 20:11:09: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0xa4c138296fabf97c"},"error":"Failed to configure (Read 0xa4c138296fabf97c/1 genBasic([\"manufacturerName\",\"zclVersion\",\"appVersion\",\"modelId\",\"powerSource\",65534], {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205)))","status":"error","transaction":"92p5v-3"}'
Zigbee2MQTT:info  2024-02-25 20:11:10: Successfully changed options
Zigbee2MQTT:info  2024-02-25 20:11:10: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":
