### ISSUE TITLE
Device Request - [Smoke Detector] - [_TZ3210_up3pngle] / [TS0205]

### ISSUE THREAD

**Issue by strmarc** [JohanBendz/com.tuya.zigbee#776]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

### Device Information

- Device Name: `Smokedetector`
- Device Model: `TS0205`
- Device Description: `SmokeDetector`
- Link to device image: The image of the device is already there
### Device Interview

```json
{
      "ids": {
    "modelId": "TS0205",
    "manufacturerName": "_TZ3210_up3pngle"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:75:9d:e6:5b:77",
    "networkAddress": 8650,
    "modelId": "TS0205",
    "manufacturerName": "_TZ3210_up3pngle",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 8650,
        "_reserved": 30,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          4,
          5,
          1,
          1280
        ],
        "outputClusters": [
          3,
          4,
          6,
          4096,
          10,
          25
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65472
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65487
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65504
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65505
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          },
          "groups": {},
          "scenes": {},
          "powerConfiguration": {},
          "iasZone": {}
        },
        "bindings": {
          "groups": {},
          "identify": {},
          "onOff": {},
          "touchlink": {},
          "time": {},
          "ota": {}
        }
      }
    }
  }


}
```

### Additional Comments:
The device is already present in the app but I guess there was a sort of an update or another minor change in the device that it does not support the present version in the Homey APP.

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by Peter-Celica** [comment]
Hi Johan good day, same request for me, bought @ AliExpress:
https://nl.aliexpress.com/item/1005005854203557.html?spm=a2g0o.order_list.order_list_main.30.477e79d2BEI8zq&gatewayAdapt=glo2nld
Thanks and best regards, Peter.

**Comment by JAJEPP** [comment]
Same here, already requested once by me. [https://github.com/JohanBendz/com.tuya.zigbee/issues/736#issue-2128276260](https://github.com/JohanBendz/com.tuya.zigbee/issues/736#issue-2128276260)

**Comment by gravis123** [comment]
same request here.

**Comment by gravis123** [comment]
Is it possible to download the sourcecode and add the new device on your own? it seems to be very similar to the existig 0502 device? Im not deep into programming but found the code for the existing 0502 and when looking at the log from the device it seems to be quite close to the existing 0502...

**Comment by Makepeace77** [comment]
I have it too from ali. Can anyone add it?

**Comment by strmarc** [comment]
> Is it possible to download the sourcecode and add the new device on your own? it seems to be very similar to the existig 0502 device? Im not deep into programming but found the code for the existing 0502 and when looking at the log from the device it seems to be quite close to the existing 0502...


I really love to do it on my own or help with adding it. But I need a start how to? Is there a guideline how to?

**Comment by ericvanbeurden** [comment]
Have this one as well, ordered from Aliexpress.

**Comment by Peter-Celica** [comment]
Hi Johan good afternoon,

Thanks for this one, working fine only no Battery reading, see screenshots.
![Screenshot_2024-09-12-13-59-52-994_app homey](https://github.com/user-attachments/assets/fbd543b6-a749-4e95-af67-5f65e7e1a9ce)
![Screenshot_2024-09-12-14-00-00-994_app homey](https://github.com/user-attachments/assets/f3ddbd60-c664-48e7-a24e-5e60356e154d)

Thanks and have a nice day,
Best regards Peter.

**Comment by ericvanbeurden** [comment]
Confirmed, also no battery indicator from my side.
