### ISSUE TITLE
 Device Request - [TS0225] - [TZE200_2aaelwxk] / [TS0225] human presence sensor

### ISSUE THREAD

**Issue by jazzarmac** [JohanBendz/com.tuya.zigbee#800]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

### Device Information

- Device Name: `Provide the name of the device`
- Device Model: `Provide the model number or identifier`
- Device Description: `Describe in short the functionality of the device`
- Link to device image: [Provide the URL to an image/photo of the device](https://www.url-to-images.com)

### Device Interview

```json
{
    [" 
  "ids": {
    "modelId": "TS0225",
    "manufacturerName": "_TZE200_2aaelwxk"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          1280,
          57346,
          61184,
          60928,
          57344,
          1024
        ],
        "outputClusters": [
          3,
          57346,
          61184,
          60928,
          57344
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "motionSensor"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0,
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "00:12:4b:00:0a:c6:58:49"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "illuminanceMeasurement": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "measuredValue",
                "value": 1000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "minMeasuredValue",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 4000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }"]
}
```

### Additional Comments:

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by victoroos** [comment]
I thought this was already added: https://github.com/JohanBendz/com.tuya.zigbee/issues/789

**Comment by jazzarmac** [comment]
Hi sorry didn't notice it was already added. I still can't add it to homey its not recognised and goes on as unknown ziggbe device. I'm using the test version app .
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eelco2k** [comment]
@jazzarmac it's supported in this forked repo:  (radar_sensor_2)
https://github.com/eelco2k/com.tuya.zigbee

**Comment by jazzarmac** [comment]
Hi thanks , I'm a total newbie , I wouldn't know what to do with this:(

Jim
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eelco2k** [comment]
See small installation explanation here:Device Request - Human Presence detector - ZG-205Z · Issue #831 · JohanBendz/com.tuya.zigbeegithub.comHi thanks , I'm a total newbie , I wouldn't know what to do with this:(


Jim

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

From: Eelco ***@***.***>

Sent: Thursday, May 9, 2024 2:01:43 PM

To: JohanBendz/com.tuya.zigbee ***@***.***>

Cc: jazzarmac ***@***.***>; Mention ***@***.***>

Subject: Re: [JohanBendz/com.tuya.zigbee] Device Request - [TS0225] - [TZE200_2aaelwxk] / [TS0225] human presence sensor (Issue #800)





@jazzarmac<https://github.com/jazzarmac> it's supported in this forked repo: (radar_sensor_2)

https://github.com/eelco2k/com.tuya.zigbee

**Comment by jazzarmac** [comment]
Hi there
Any chance this could be released as an app so it's easy to install? I don't fancy messing about with CLI and node etc...
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eelco2k** [comment]
I think the only way is that the original maintainer merges my PR (https://github.com/JohanBendz/com.tuya.zigbee/pull/774 ) and releases the new version to the homey App Store.

and as the latest commit to SDK3 branch was 3 months ago I don’t think this is going to happen soon.

**Comment by jazzarmac** [comment]
Hi thanks for the reply. Just looks like I'll have to wait the or buy something else. Doesn't look like there's been much activity as far as releases go . Part of the problem with homey, to many apps relies on individual developers, but that's a other issue

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eelco2k** [comment]
Yes it is a little bit unfortunate but I think because this app has to add so many devices which all have different capabilities it’s very cumbersome to maintain. So still shoutout to the developers who try to maintain the main branches and releases. 
If there is an update of de SDK3 branch I will try to sync my fork so that it at least has latest version of original code. So then if needed you only have to pull the forked branch again and run the homey app install command. 

I did not have the need to reinstall so many times so once you installed the app via cli it will work for a long period

**Comment by dlnraja** [comment]
Hi, Check the actively maintained fork: https://github.com/dlnraja/com.tuya.zigbee Forum: https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352
