### ISSUE TITLE
Curtain module - _TZ3000_vd43bbfq / TS130F

### ISSUE THREAD

**Issue by valvarez** [JohanBendz/com.tuya.zigbee#82]
Hi Johan,
I see quikly your code and I already find this device on your list but with comment "not tested".
I get this device and it doesn't work with fail "invalid_device_by_id".
Thx for your fix, and ask me if you need more information ;)

  "ids": {
    "modelId": "TS130F",
    "manufacturerName": "_TZ3000_vd43bbfq"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 514,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          4,
          5,
          258
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 64
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_vd43bbfq"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS130F"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65504
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65505
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "windowCovering": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 8,
                "name": "currentPositionLiftPercentage",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61440
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61441
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61442
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61443
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "time": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      }
    }
  }

**Comment by PhAnt0mFS** [comment]
I think I found the issue for the "Invalid_device_by_id" error. 
I'm able to control my device by changing the line below. (Have not tried it with actual load but I can hear the relays clicking and no error message.)

**In device.js on line 4**
Original: const { debug, CLUSTER } = require('zigbee-clusters');
New: const { Cluster, debug, CLUSTER } = require('zigbee-clusters');
```

[log] 2021-06-26 15:18:13 [ManagerDrivers] [Driver:curtain_module] [Device:1f12416e-7e17-45da-aeab-f97be7e4b00c] set windowcoverings_set → 0.35 (cluster: windowCovering, endpoint: 1)

2021-06-26T15:18:13.205Z zigbee-clusters:cluster ep: 1, cl: windowCovering (258) send frame ZCLStandardHeader {
  frameControl: [ 'clusterSpecific' ],
  data: windowCovering.goToLiftPercentage { percentageLiftValue: 65 },
  cmdId: 5,
  trxSequenceNumber: 12
}

2021-06-26T15:18:13.367Z zigbee-clusters:cluster ep: 1, cl: windowCovering (258) received frame defaultResponse windowCovering.defaultResponse { cmdId: 5, status: 'SUCCESS' }
```

**Comment by JohanBendz** [comment]
Hi @PhAnt0mFS, thanks for finding my mistake! I have been waiting to fix this until I got an item myself and had it delivered just the other day. I will test with my device now and if it works I'll post an update asap.

**Comment by PhAnt0mFS** [comment]
No problem! The smallest issues are the hardest to find, especially when you don't have the device itself. I hope I saved you some time troubleshooting. 

(Also time for Homey to provide PO-boxes to Developers so people can send in unsupported devices. (As a gift or course))

**Comment by Dutchman2** [comment]
> Hi @PhAnt0mFS, thanks for finding my mistake! I have been waiting to fix this until I got an item myself and had it delivered just the other day. I will test with my device now and if it works I'll post an update asap.

Hallo Johan,

Fijne app, bedankt daar voor. Ben je al in staat om het probleem met de curtain module op te lossen? Ik kijk er erg naar uit. Alvast bedankt.

Groeten
Fred

**Comment by parassita889** [comment]
hi I have 3 curtain tuya zigbee and I receive "Invalid_device_by_id" how can I solve the problem?

**Comment by Titske** [comment]
hi i am a new homey user. i have 14 modules. please update so i can use my homey more.
thank you.

**Comment by JohanBendz** [comment]
Added to next release of the app.
