### ISSUE TITLE
LCD Temperature & Humidity Sensor: No updates after installation

### ISSUE THREAD

**Issue by Sven266** [JohanBendz/com.tuya.zigbee#83]
Hi,
the installation in Homey was flawless. Alle fine. But the values like temperature and humidity don't update even after hours.
What have I done wrong?

Thanks

**Comment by Lansuper** [comment]
Updates sometimes take up to 10 hours, even with big temperature changes during that period. Tried to set reporting to 2 digits, without effect. Is there a way to force an update more often?
