### ISSUE TITLE
Device Request - Human Presence detector - ZG-205Z

### ISSUE THREAD

**Issue by mikkelnl** [JohanBendz/com.tuya.zigbee#831]
### Device Information

- Device Name: Smart Human Presence Sensor
- Device Model: ZG-205Z
- Link to device image: https://ae01.alicdn.com/kf/Sec139cab9747498e92aabf7a0ea0812c2/WiFi-Zigbee-Smart-Human-Presence-Sensor-Luminance-Distance-Detection-Tuya-Smart-Life-Home-Automation-For-Z2M.jpg_.webp and https://www.aliexpress.com/item/1005006010216719.html

### Device Interview

```json
{
    
  "ids": {
    "modelId": "TS0225",
    "manufacturerName": "_TZE200_2aaelwxk"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:27:e0:1c:c5:e5",
    "networkAddress": 41205,
    "modelId": "TS0225",
    "manufacturerName": "_TZE200_2aaelwxk",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 41205,
        "_reserved": 34,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          1280,
          57346,
          61184,
          60928,
          57344,
          1024
        ],
        "outputClusters": [
          3,
          57346,
          61184,
          60928,
          57344
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 41205,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "0122052017",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "motionSensor"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0,
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "b0:c7:de:ff:fe:5b:70:50"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "illuminanceMeasurement": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "measuredValue",
                "value": 1000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "minMeasuredValue",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 4000
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }
}
```

### Additional Comments:

Zigbee precense detector. It might be the same 'device' as 'Radar' in the test-version of the app, but when added Homey adds it as a generic Zigbee device. Bought from Aliexpress via https://www.aliexpress.com/item/1005006010216719.html

Corresponding 'issue': https://github.com/JohanBendz/com.tuya.zigbee/issues/828

**Comment by eelco2k** [comment]
@mikkelnl check my fork of repo it should be supported there 
https://github.com/eelco2k/com.tuya.zigbee/tree/SDK3/drivers/radar_sensor_2

**Comment by mikkelnl** [comment]
> @mikkelnl check my fork of repo it should be supported there https://github.com/eelco2k/com.tuya.zigbee/tree/SDK3/drivers/radar_sensor_2

Thanks, though I have no idea how to get this on my Homey? ;-)

**Comment by eelco2k** [comment]
make sure you install homey cli 
https://apps.developer.homey.app/the-basics/getting-started/homey-cli

```bash
npm install --global --no-optional homey
```

clone the repo:
```bash
git clone https://github.com/eelco2k/com.tuya.zigbee
```

login with your homey account via:
```bash
homey login
```

go to the com.tuya.zigbee folder in the terminal and run this command to install:
```bash
npm install
homey app install
```

now you have installed the forked version of the tuya app. bear in mind you can only install one version of the tuya app. the official or another. not both. I've just updated/merged the latest version of JohanBendz repo into my forked one, so it should be up-2-date

**Comment by mikkelnl** [comment]
Thanks! The install worked, the device was detected, but so far it is not picking up movement or anything... I'll wait and test some more...

**Comment by eelco2k** [comment]
﻿ Check out the sensitivity settings as well. I’ve got 3 devices and all working.

**Comment by eelco2k** [comment]
If you want to see what is going on you could try:
homey app run 
Instead of 
homey app install

you will get some logging in the terminal. ﻿

**Comment by mikkelnl** [comment]
> Check out the sensitivity settings as well. I’ve got 3 devices and all working.  Thanks! The install worked, the device was detected, but so far it is not picking up movement or anything... I'll wait and test some more... —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Thanks... I tried to increase the first sensitivity setting to 10, but when trying to save, I get: "Could not get device by id"

**Comment by eelco2k** [comment]
Use:
homey app run

and post error messages. Thanks!

**Comment by mikkelnl** [comment]
This is the output, my guess is it has something to do with 'Cannot find module colore-space-hsv'?

https://pastebin.com/8PiNK33n

**Comment by eelco2k** [comment]
Did you run: npm install
In the cloned repo folder?

**Comment by mikkelnl** [comment]
> Did you run: npm install In the cloned repo folder?

Yep:

> up to date, audited 13 packages in 433ms
>found 0 vulnerabilities

**Comment by eelco2k** [comment]
npm install color-space

it’s an npm package which is not installed. Not sure why

**Comment by mikkelnl** [comment]
Using 'homey app run' worked: the device shows sensor data in Homey...

When I use 'homey app install', it won't show any sensor data when I add the device in homey.

Strange? Thanks for your help btw.

/edit
Wait, it now registers lux... I'll wait a minute...

**Comment by eelco2k** [comment]
Yes i could sometimes take a minute to settle. This is also mentioned in the official manual. Hopefully it fixes it for you.

i've updated my repo, and it updated the package.lock file. and there the node_modules/color-space is there...

what you could do is remove the node_modules/ folder. do another git pull, and run npm install again...

Hopefully this should all work!

**Comment by mikkelnl** [comment]
Thanks for all your help!

After a few minutes all sensors seem to be working... Awesome...!

**Comment by mikkelnl** [comment]
One more thing; in Flows I only seem to be able to select 'when movement is detected', and not the 'presence' (big or small) detection? Is this correct?

**Comment by eelco2k** [comment]
Yes, for now. When I have time I will add those for device specific as well. There is a general one but not sure if that works correctly. You can find it when selecting the if card and go to tuya zigbee and then cards. There are small en big detections. But I think they should be per device specific. Could be a bug. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by mikkelnl** [comment]
> Yes, for now. When I have time I will add those for device specific as well. There is a general one but not sure if that works correctly. You can find it when selecting the if card and go to tuya zigbee and then cards. There are small en big detections. But I think they should be per device specific. Could be a bug. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Hi! Just checking; there is no card to use in flows to check the current lux/lx value, correct? I am trying to have some lights turn on when presence is detected but only when it is dark enough...

**Comment by eelco2k** [comment]
I don’t think device flow cards are implemented now. Will add them hopefully next week when I have more time. The json should be edited so that it’s per device all the flow trigger cards. Yes, for now. When I have time I will add those for device specific as well. There is a general one but not sure if that works correctly. You can find it when selecting the if card and go to tuya zigbee and then cards. There are small en big detections. But I think they should be per device specific. Could be a bug. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

Hi! Just checking; there is no card to use in flows to check the current lux/lx value, correct? I am trying to have some lights turn on when presence is detected but only when it is dark enough...

**Comment by eelco2k** [comment]
i've updated the repo with the device flow cards. do a `git pull` and re-run `homey app install` now the device trigger cards should appear. Lux flow card was already there. cause this is a build-in capability.

**Comment by Barend-Brandhout** [comment]
Hi, I tried everything as you described above, but I still can't manage to install the ZG-205Z on my Homey. I don't know what I am doing wrong. I do get some error messages while installing and that has to do with the validation of the app. I added my logs in this comment. What went wrong and can you help me?

[Log Homey Zigbee.txt](https://github.com/user-attachments/files/16641587/Log.Homey.Zigbee.txt)

**Comment by eelco2k** [comment]
This looks like a problem with the curtain-module and not related to my driver. I still have the latest commit from johanbendz package. So it is synced. Create a new issue and hopefully the person who created the curtain module can fix this error.
