### ISSUE TITLE
Bug report unable to use experimental version

### ISSUE THREAD

**Issue by tweakerrobin** [JohanBendz/com.tuya.zigbee#837]
Dear friends, 
When installing the experimental version of Tuya Zigbee 0.2.25 after deinstalling the stable version at some point (+/-5min) when I try to delete and add a curtain tuya device,  my homey (newest version) just goes back to the stable version of the app. (0.1.45) 

I tried to turn of automatic update for this app after installing the experimental version, but still it goes back to version 0.1.45

I even enabled "Enable experimental updates", on   ttps://tools.developer.homey.app/tools/settings which was off. but did not helped. 

At the precise moment when I install a new device sometimes I get a error and the install is blocked or the device is installed but in any case  the app version is changed to the older stable version :S

homey pro (early 2023) version 10.3.4

Thank you all for your contributions!

**Comment by tweakerrobin** [comment]
It's not typical behavior for Homey's platform to automatically revert an app to its stable version upon encountering an error with a device. Generally, errors should be logged, and possibly reported, without altering the app's version unless a rollback is part of a specific error-handling protocol designed by the app developers. It might be a specific issue with the Tuya Zigbee app or its integration with Homey.

**Comment by JohanBendz** [comment]
Not something the app is designed to do... never heard of it before. Send a diagnostic to Athom and get in contact with their support. Looks more like an "app store issue".
