### ISSUE TITLE
TS0504B Led strip 

### ISSUE THREAD

**Issue by Tijn-hhs** [JohanBendz/com.tuya.zigbee#84]
Hi,

I bought a tuya zigbee led strip(TS0504B).
Hoping i can control it with my homey.

unfortunately I can't get it paired with your app.

Can you help me? How do I get it done?
Thank you in advance.

**Comment by JohanBendz** [comment]
Hi @Tijn-hhs, sorry for the late answer.
I need the manufacturerName to be able to add support for your device. You can find it in the devices settings if you add it as a generic unit.

**Comment by Tijn-hhs** [comment]
Hi @JohanBendz 
Thank you very much for your response.
The name = zb_manufacturer_name="_TZ3000_ukuvyhaa"
 
Happy New Year.
