### ISSUE TITLE
Is latest version of tuya zigbee app 0.1.45?

### ISSUE THREAD

**Issue by bbrodnik** [JohanBendz/com.tuya.zigbee#842]
### Describe the bug

When adding Tuya Zigbee app to homey, it shows version 0.1.45, what is also shown when it is installed.
If I look at Changelog, there are records up to version 0.2.25.
I also found device [Temperature and Humidity Sensor] - [_TZ3000_xr3htd96] / [TS0201] which is on the list of supported devices, but is not recognized by app.

### Expected behavior

I would expect update to version at least 0.2.24 to be available, because version 0.1.45 is old (from 3. mar. 2021 as noted in changelog).

### App and Homey version

> * What Homey version are you running? Homey Pro (Early 2023)
> * What version of Homey firmware do you use? 10.3.5
> * What version of the Tuya Zigbee App are you using? 0.1.45

### Screenshots

> If applicable, add screenshots to help explain your problem.

![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/66665235/0db072f4-ce38-4c82-b7b8-9ea765eb532d)

![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/66665235/46f1fdba-1df2-4793-aaef-deb44d3259a8)

![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/66665235/33d849dd-43a8-404c-afaa-1b6c054eedd7)

> Add any other context about the problem here.

**Comment by tweakerrobin** [comment]
when you go to this [link](https://homey.app/en-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/ ) you will find the experimental version. which can have some bugs

**Comment by JohanBendz** [comment]
The link to the test version is in the change log, just click "Test".

And yes, I will update the Live Tuya app. "Any week now"

**Comment by bbrodnik** [comment]
Thank you, Johan, it works. Wish you all the best.
