### ISSUE TITLE
Bug report - [v0.2.25 development often crash]

### ISSUE THREAD

**Issue by nides34** [JohanBendz/com.tuya.zigbee#847]
### Describe the bug

Hi,

I'm using this version of Tuya Zigbee app: https://github.com/shaarkys/com.tuya.zigbee

Few times in a day, app crashes alone ; all zigbee devices have red warning icon, and in app list, Tuya Zigbee appears as "crashed". I restart it, and it rules right.

I have 25 devices. RAM usage is around 80-120Mb. CPU usage is around 7-12%.

### App and Homey version

> * What Homey version are you running? Homey Pro 2023
> * What version of Homey firmware do you use? 10.3.5
> * What version of the Tuya Zigbee App are you using? 0.2.25 development

Is there anything to do?

Thanks :)

**Comment by nides34** [comment]
Hi,

My app crashes every 6mn. I have deleted most of door sensors. I have 2 door sensors, 6 radars and 2 temperature sensors.

Is there anything to test the problem?

can the crash interfere with the zigbee of other applications?

Thanks :)

**Comment by JohanBendz** [comment]
Hi @nides34, is this still an issue? Is it only this app that crashes or also other Zigbee apps?

**Comment by nides34** [comment]
Hi @JohanBendz 

Sorry for my late answer.

Since my previous message, crashes stopped suddenly. I had uninstalled developpment app and reinstalled test version, there were always crashes, but one day, nothing... I have no explanations but... it runs!

Thanks for all your work :)

**Comment by JohanBendz** [comment]
Great to hear @nides34 , closing the issue.
