### ISSUE TITLE
Tuya 4 channel board ZG-005-RF disappeared in Homey Tuya Zigbee App

### ISSUE THREAD

**Issue by JosBilde** [JohanBendz/com.tuya.zigbee#852]
### Describe the bug

> A clear and concise description of what the bug is.
My Tuya 4 channel boards stopped working in Homey, message “App unavailable”.
When I go to https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/ I don’t see it as a supported device anymore?..
### To Reproduce

1. Go to 'https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/'
2. 
3. Scroll down to '.supported devices'
4. See error: no 4 channel board available anymore.

### Expected behavior

> A clear and concise description of what you expected to happen.

### App and Homey version

> * What Homey version are you running? homey pro 2023
> * What version of Homey firmware do you use? 11.0.0
> * What version of the Tuya Zigbee App are you using? 0.1.45

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Additional context

> Add any other context about the problem here.

**Comment by JohanBendz** [comment]
Hi @JosBilde, this device was only ever in the test version: https://homey.app/nl-nl/app/com.tuya.zigbee/Tuya-Zigbee/test/
