### ISSUE TITLE
Device Request - Moes Zigbee Water Valve Timer (model: 'TS0049', vendor: '_TZ3000_cjfmu5he')

### ISSUE THREAD

**Issue by PiTRiS87** [JohanBendz/com.tuya.zigbee#857]
Hello,

low priority one, as device works as basic zigbee device with on/off functionality, but would be nice to have proper driver
- sometimes it gives "aborted" error message even though it works
- no battery status
Information regarding device can be seen here: https://github.com/Koenkk/zigbee2mqtt/issues/21788

**Comment by tonymkhael** [comment]
Hello @PiTRiS87 , Mine also work with HA/ZHA however it's draining batteries like crazy (Network signal is good). Could you please provide me with your zigbee info (mainly anything related to Firmware version)?

**Comment by PiTRiS87** [comment]
Hi... tried to check, but homey is not showing any information regarding fw version... Also, interview seems not to work.
Will update if I get more info :/

**Comment by PiTRiS87** [comment]
Seems like it works with same driver as Smart Garden Irrigation Controller _TZ3210_eymunffl / TS0101 (Woox)
Works, battery is showing up (not sure if properly, fairly new device, so battery will be at 100%).
If someone can confirm, I'll try to push it (or you can push it :)), if not, will wait till battery updates

**Comment by danielponte** [comment]
I have exactly this same model _TZ3000_cjfmu5he and it works absolutely fine, there is just one minor "problem": it turns off at exactly 10 minutes. There is no countdown setting, it just turns off. Only exposes I see are battery, state (on/off) and link quality. Dont know if this is like a self protection or a default configuration thats not exposed.
