### ISSUE TITLE
Device Request - [Zigbee Temperature and Humidity sensor] - [_TZ3000_qaaysllp] / [TS0201]

### ISSUE THREAD

**Issue by HakobDongian** [JohanBendz/com.tuya.zigbee#894]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

Product Category
wsdcg

### Device Information
Manufacturer: _TZ3000_qaaysllp
Device ID: TS0201
Product Name: Zigbee温湿度 NEO
Device ID: bf8a0952998f4f64a9e3nj
Product Category: wsdcg
Device Description: Temperature and Humidity sensor
Link to device Image (Aliexpress): https://nl.aliexpress.com/item/1005002434961203.html

```json
[
  {
    "code": "temp_unit_convert",
    "value": "c"
  },
  {
    "code": "maxtemp_set",
    "value": 40
  },
  {
    "code": "minitemp_set",
    "value": 10
  },
  {
    "code": "maxhum_set",
    "value": 90
  },
  {
    "code": "minihum_set",
    "value": 20
  },
  {
    "code": "switch",
    "value": true
  }
]
```

### Additional Comments:
I will submit some more devices i have, work in Tuya app, not in Tuya clud for Homey.
If you need more information please contact me.
Best Regards Hakob.

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by JohanBendz** [comment]
Already supported by the Zigbee app.
