### ISSUE TITLE
Device Request - [Zigbee Temperature and Humidity sensor] - [_TZE200_vvmbj46n] / [TS0601]

### ISSUE THREAD

**Issue by HakobDongian** [JohanBendz/com.tuya.zigbee#895]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

### Device Information

Manufacturer: _TZE200_vvmbj46n
Device ID: TS0601
Product Name: Zigbee Temperature & Humidity Sensor
Device ID: bf7e5ef9b8c3c2e76bxyig
Product Category: wsdcg
Device Description: Temperature and Humidity sensor
Link to device Image (Aliexpress): https://nl.aliexpress.com/item/1005006989545316.html

### Device Interview

```json
[
  {
    "code": "temp_unit_convert"
  },
  {
    "code": "maxtemp_set",
    "value": -10
  },
  {
    "code": "minitemp_set",
    "value": -10
  },
  {
    "code": "maxhum_set",
    "value": 0
  },
  {
    "code": "minihum_set",
    "value": 0
  },
  {
    "code": "switch",
    "value": false
  }
]
```

### Additional Comments:
I will submit some more devices i have, work in Tuya app, not in Tuya clud for Homey.
If you need more information please contact me.
Best Regards Hakob.

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by slicke** [comment]
I got this device yesterday and noticed that it's compatible with another temp I bought from AliExpress.
I've added support for it to my pull request: https://github.com/JohanBendz/com.tuya.zigbee/pull/927
