### ISSUE TITLE
Curtain Switch - TS130F

### ISSUE THREAD

**Issue by JohanBendz** [JohanBendz/com.tuya.zigbee#9]
Producent ID: _TZ3000_8kzqqzu4
Product ID: TS130F
Device ID: 514
Profile ID: 260

https://nl.aliexpress.com/item/4001190275372.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&tt=MG&aff_request_id=74ebbf3c318347d296b3cecc88eca5fa-1597677509127-01291-_BOUwwy&aff_platform=default&sk=_BOUwwy&mergeHashcode=45872506825&description=%E2%82%AC%2B12,44%2B%2B52%EF%BC%85%2BOff%2B%7C%2BTuya%2BSmart%2BLife%2BZigBee%2B3.0%2BCurtain%2BBlind%2BSwitch%2Bfor%2BRoller%2BShutter%2BElectric%2Bmotor%2BGoogle%2BHome%2BAlexa%2BEcho%2BVoice%2BControl%2BDIY&aff_trace_key=74ebbf3c318347d296b3cecc88eca5fa-1597677509127-01291-_BOUwwy&businessType=ProductDetail&title=%E2%82%AC%2B12,44%2B%2B52%EF%BC%85%2BOff%2B%7C%2BTuya%2BSmart%2BLife%2BZigBee%2B3.0%2BCurtain%2BBlind%2BSwitch%2Bfor%2BRoller%2BShutter%2BElectric%2Bmotor%2BGoogle%2BHome%2BAlexa%2BEcho%2BVoice%2BControl%2BDIY&platform=AE&terminal_id=487f755ebf8d49fead69c9f23bab80a9&templateKey=white_backgroup_101

**Comment by JohanBendz** [comment]
_TZ3000_vd43bbfq

**Comment by JohanBendz** [comment]
Multiple devices mixedup.. Curtain Module released for testing.

**Comment by PaulSchryve** [comment]
(already posted on forum)

I have installed one of those

Curtain Module
_TZ3000_vd43bbfq / TS130F - Test, not verified
When i do any command i get an “invalid device” error.
I just have sent an app report.
Do you need more info / test to solve this ?

To reset the device you need to power on / off 5 time the curtain.
(Comes from Aliexpress :
Module de commutateur de rideau Tuya Smart Life Zigbee, pour moteur de volet roulant et de store, commande à distance par application compatible avec Google Home | AliExpress 4 )

Thanks & have a good day !

**Comment by ghost** [comment]
This is the interview result from Curtain Module _TZ3000_vd43bbfq / TS130F
It has the same behavior as PaulSchryve describes. 

  "ids": {
    "modelId": "TS130F",
    "manufacturerName": "_TZ3000_vd43bbfq"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 514,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          4,
          5,
          258
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 64
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_vd43bbfq"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS130F"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65504
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65505
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "windowCovering": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 8,
                "name": "currentPositionLiftPercentage",
                "value": 100
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61440
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61441
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61442
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 61443
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "time": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      }
    }
  }

**Comment by JohanBendz** [comment]
Additional manufacturer id:
TS130F _TZ3000_dph3rpss

Zemismart – interrupteur intelligent pour rideaux, Tuya Zigbee, neutre requis, moteur de store à rouleau, télécommande Alexa Google Home | AliExpress

**Comment by JohanBendz** [comment]
Added to next release / 2 different devices.
