### ISSUE TITLE
Question about zigbee endpoint

### ISSUE THREAD

**Issue by jrevillard** [JohanBendz/com.tuya.zigbee#912]
Hello @JohanBendz ,

I already add some devices to the application and I would like to add a new one. But I would like to understand once for all how the endpoint configuration works. I asked my question in the forum but I was told to do it here so please see the.link:

https://community.homey.app/t/app-pro-tuya-zigbee-app/26439/4821?u=jerome_revillard

Thanks!
Jérôme

**Comment by JohanBendz** [comment]
Hi @jrevillard, I hope the new helper files and the documentation in them will help!

**Comment by jrevillard** [comment]
Hello,

I checked quickly and I think so !

Thanks for your help 

Best,
Jérôme
