### ISSUE TITLE
Bug report - [Short description] temperature and humidity sensor

### ISSUE THREAD

**Issue by Adri1359** [JohanBendz/com.tuya.zigbee#921]
### Describe the bug

> A clear and concise description of what the bug is. Can’t anymore tuya zigbee temperature and humidity sensor add to homey 2019. Before it was oké. 

### Expected behavior

> A clear and concise description of what you expected to happen.

### App and Homey version

> * What Homey version are you running? Early 2019
> * What version of Homey firmware do you use? 12.0.0
> * What version of the Tuya Zigbee App are you using? V0.1.45

### Screenshots

![image](https://github.com/user-attachments/assets/dbe20a86-9864-4ff0-a034-f02e7a2a8813)

> If applicable, add screenshots to help explain your problem.

### Additional context

> Add any other context about the problem here.

**Comment by JohanBendz** [comment]
Hi @Adri1359, what's the device Zigbee info? (add it as unknown zigbee and check settings)

**Comment by Adri1359** [comment]
Hi JohanBendz,It’s working with the test tuya zigbee app, thxGr AdriOp 4 sep 2024 om 12:04 heeft Johan Bendz ***@***.***> het volgende geschreven:﻿
Hi @Adri1359, what's the device Zigbee info? (add it as unknown zigbee and check settings)
