### ISSUE TITLE
Bug report - Temp & Humidity sensor adds as unknown device

### ISSUE THREAD

**Issue by weenan** [JohanBendz/com.tuya.zigbee#926]
### Describe the bug

When adding the Temperature & Humidity sensor it says there is no app available for the device and it gets added as an unknown zigbee device with only on/off capabilites

### To Reproduce

1. Add Device
2. Select the Tuya Zigbee app
3. Put the sensor in the add mode
4. Device is added as unknown device

### Expected behavior

The device should be added as a sensor with temperature and humidity capabilites.

### App and Homey version

* Homey Pro (Early 2019)
* Version 12.0.0
* Tuya Zigbee app version 0.1.45

### Screenshots

![Screenshot 2024-09-04 102026](https://github.com/user-attachments/assets/c758189a-2680-4002-a8d1-7f9973adf984)
![Screenshot 2024-09-04 102056](https://github.com/user-attachments/assets/9e47c3c6-680f-42a3-8ada-d9ccef0fbc0f)

### Additional context

> Add any other context about the problem here.

**Comment by JohanBendz** [comment]
Hi @weenan, a bit further down in that view is the Zigbee info I need to help you.

**Comment by weenan** [comment]
> Hi @weenan, a bit further down in that view is the Zigbee info I need to help you.

@JohanBendz Wow that was fast!

I´m guessing this is what you mean?

![Screenshot 2024-09-05 185238](https://github.com/user-attachments/assets/c61a4b88-35fc-48e9-8f78-78545872de15)

**Comment by MalSve** [comment]
I have the same problem with
![2024-09-08 11 21](https://github.com/user-attachments/assets/b6ec8cab-5210-45e4-af13-24354c85b43a)

**App and Homey version**
Homey Pro (Early 2018)
Version 12.0.1
Tuya Zigbee app version 0.2.36

**Comment by JohanBendz** [comment]
Added to the test version.

**Comment by weenan** [comment]
> Added to the test version.

You´re a star. Works like a charm!

**Comment by MalSve** [comment]
Is booth added to testversion?
