### ISSUE TITLE
Homey App Store version is very behind

### ISSUE THREAD

**Issue by aescolastico** [JohanBendz/com.tuya.zigbee#934]
Hello,
Are there plans to mark a newer build as stable on the app store? The latest version it will officially let you install through the app store is still 0.1.45.

**Comment by JohanBendz** [comment]
Hi @aescolastico a new Live version is due within days.
You can install the test version while waiting for the new Live version:
https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/
If you use any of the devices currently only in the test version you can speed up the release of the new Live version by letting me know what drivers works and not (I'm just as happy to know something works.. :) )

**Comment by aescolastico** [comment]
> Hi @aescolastico a new Live version is due within days. You can install the test version while waiting for the new Live version: https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/ If you use any of the devices currently only in the test version you can speed up the release of the new Live version by letting me know what drivers works and not (I'm just as happy to know something works.. :) )

ah ok thanks. I installed the test version in the mean time. is there any way to associate a previously added generic zigbee device with the app after the fact? or do we have to remove and readd the device for it to be a Tuya Zigbee device.

**Comment by JohanBendz** [comment]
@aescolastico, no... you will have to remove and reinstall.
