### ISSUE TITLE
Device request shenzhen typ ZTH01 TEMP/HUM

### ISSUE THREAD

**Issue by Jano1960** [JohanBendz/com.tuya.zigbee#937]
![Screenshot_20240909-151534_Homey](https://github.com/user-attachments/assets/b9e4ccce-de98-4444-b092-64538fa0ac43)
![Screenshot_20240909-151527_Homey](https://github.com/user-attachments/assets/d1cd9b13-3dc6-4db4-a56b-fc598cd2ec4b)
![20240909_142908](https://github.com/user-attachments/assets/abd574c2-2a31-4bf7-949c-1f46db2f1b11)
![20240909_142747](https://github.com/user-attachments/assets/55e5026a-7606-4b81-9c6a-9c2b6fa458b3)
![20240909_142725](https://github.com/user-attachments/assets/e01301ac-fa59-4f22-913b-312810cabc52)

### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

### Device Information

- Device Name: `Provide the name of the device`
- Device Model: `Provide the model number or identifier`
- Device Description: `Describe in short the functionality of the device`
- Link to device image: [Provide the URL to an image/photo of the device](https://www.url-to-images.com)

### Device Interview

```json
{
    ["Paste the device interview information here"]
}
```

### Additional Comments:

> **Note:** Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help

### How to interview a device

- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by JohanBendz** [comment]
Hi @Jano1960, this is supported by the test version of the app.
https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by Jano1960** [comment]
Thank you very much.

It works

Greetings

Jan Oskam

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
