### ISSUE TITLE
Device Request Tuya Temperature and humidity sensor _TZ3000_zl1kmjqx

### ISSUE THREAD

**Issue by MalSve** [JohanBendz/com.tuya.zigbee#939]
I wrote this in another thread but i don't know if it was fixed
![image](https://github.com/user-attachments/assets/2d51d94f-c81c-4791-a49b-ef29c297cb19)

**App and Homey version**
Homey Pro (Early 2018)
Version 12.0.1
Tuya Zigbee app version 0.2.36

I got unknown Zigbee when i try to add it.

**Comment by JohanBendz** [comment]
Hi @MalSve, this is supported by the test version of the app.
https://homey.app/en-gb/app/com.tuya.zigbee/Tuya-Zigbee/test/

**Comment by MalSve** [comment]
It still goes as unknown Zigbee. I have Tuya Zigbee 0.2.37.
