### ISSUE TITLE
Bug report - test app crash

### ISSUE THREAD

**Issue by Rens-H** [JohanBendz/com.tuya.zigbee#947]
### Describe the bug

> Randomly the application crashes all devices have exclamation marks.

Restarting the app resolves the problem temporarily 

### To Reproduce

N/a
New diagnostic 9a1c5246-1b31-48ef-8eaf-b5f2d0435f73

### Expected behavior

> A clear and concise description of what you expected to happen.

### App and Homey version

> * What Homey version are you running?
App 8.4.0.1538
> * What version of Homey firmware do you use?12.01
> * What version of the Tuya Zigbee App are you using?
0.2.40

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Additional context

> Add any other context about the problem here.

**Comment by JohanBendz** [comment]
Hi @Rens-H, I'v seen a few diagnostic reports reporting the same but none have any info.. all blank.. so I'm a bit lost here. Do you get any in app errors or anything else I can troubleshoot?

**Comment by Rens-H** [comment]
@JohanBendz since the last couple of updates  I did not experience any crashes anymore. Maybe something you did in them fixed the problem

**Comment by Rens-H** [comment]
Closed too soon
@JohanBendz 
![Screenshot_2024-09-15-23-01-23-48_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/a99674a6-2ade-4795-bc76-4c9e05106084)

**Comment by Rens-H** [comment]
![Screenshot_2024-09-15-23-04-05-08_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/39164101-7c96-48fc-8e31-4a837ed0cd7b)
![Screenshot_2024-09-15-23-03-57-12_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/fb01241c-5d6e-429f-8bbe-14d9735ecf76)

**Comment by Rens-H** [comment]
@JohanBendz  I found the issue, it was a Rogue wall plug that was causing this issue.

![1726590576675895246254190479417](https://github.com/user-attachments/assets/32aba92b-1d30-421f-aed8-5051959c15dd)

**Comment by JohanBendz** [comment]
Thanks for the feedback @Rens-H, can be hard to find those.. happy you did! :)

**Comment by Rens-H** [comment]
as updated on community forum pm , the issue is still present

**Comment by JohanBendz** [comment]
Hi @Rens-H, from what I can tell, the issue is with the smart plugs—the polling causes Zigbee congestion and timeouts. I’ve rewritten the code to avoid polling. Hope I’m not breaking stuff... Would you be able to test the new code from Github using CLI?

**Comment by Rens-H** [comment]
Never done it before, where can I find information on how to do it?

**Comment by JohanBendz** [comment]
Hmm, if you have not done that before it's quite a learning curve..
https://community.homey.app/t/how-to-cli-install-method/198
There has been updates so read the complete thread.
(If you get through that.. there is no need to install Docker, just use Homey App Run --remote instead)

**Comment by Rens-H** [comment]
I will try when I have the time, I removed the last added wall plugs and it's more stable, although this morning I had a crash again.
Isn't this related just to homey pro early 2019 ? Will homey pro 2023 handle this better ? ( other zigbee chip ) ?

**Comment by JohanBendz** [comment]
Hi @Rens-H, still problems? If so please send a fresh diagnostic report.
And if you are able please post a list of your zigbee units: https://tools.developer.homey.app/tools/zigbee

**Comment by Rens-H** [comment]
Hi Johan, sorry for the delay, but because of the lateste updates the app was restarted.

Issue still there: 6e62ac23-9564-416c-b8e5-12a72788ab4a

![image](https://github.com/user-attachments/assets/15348611-8276-4e31-8a77-f6488155c51b)

**Comment by Rens-H** [comment]
just bought a homey pro 2023. Please close this ticket
I will monitor the app.

Thanks for the effort.
