### ISSUE TITLE
Bug report - _TZ3000_zl1kmjqx still doesn't work

### ISSUE THREAD

**Issue by MalSve** [JohanBendz/com.tuya.zigbee#953]
When I try to add the device, I now get the error message as shown. It is a temperature/humidity sensor from Tuya.

Homey v 12.0.1
Tuya Zigbee v 12.50

![IMG_1037](https://github.com/user-attachments/assets/4cd26d41-5494-4975-b7e3-8d78153475e6)

**Comment by JohanBendz** [comment]
Hej @MalSve, det låter som att du har problem utanför appen. T.ex. en dålig/svag strömadapter, krockande WiFi eller annan störning på Zigbee nätet. Prova att använda https://my.homey.app när du lägger till enheten, hjälper inte det så börja felsöka här: https://community.homey.app/t/advanced-zigbee-troubleshooting-on-homey/115930

**Comment by XethaX** [comment]
Got the same problem, cant add _TZ3000_zl1kmjqx sensor.
