### ISSUE TITLE
Please add the tuya ts0215 to your app 

### ISSUE THREAD

**Issue by JulDozer** [JohanBendz/com.tuya.zigbee#97]
Hello 
Could you please add the tuya ts0215, so that you can use it as an alarm remote control? 
Thanks in advance

**Comment by JohanBendz** [comment]
Hi @JulDozer, sorry for the late answer.

What is ts0215? I have added support for _TZ3000_fsiepnrh / ts0215A, this is a 4 button Smart Remote Controller. Is this what you ask for?

**Comment by JulDozer** [comment]
yes it is the remote control with 4 tuya button.
to help you :
https://a.aliexpress.com/_uX1Vvv
