### ISSUE TITLE
Device Request - 1 button smart button - TS0041 (_TZ3000_qgwcxxws)

### ISSUE THREAD

**Issue by tobyworks** [JohanBendz/com.tuya.zigbee#972]
### Prerequisites:

- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device.

### Device Information

- Device Name: 1 button smart switch
- Device Model: TS0041 (_TZ3000_qgwcxxws)
- Device Description: a single button smart button from aliexpress
- Link to device image: https://nl.aliexpress.com/item/1005006774161745.html?src=google 

### Device Interview

N.A.

### How to interview a device

Cant interview the device it never comes up with the dialog

> **Note:** To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want to be added. Thank you for your contribution!

**Comment by tobyworks** [comment]
Does this mean it's added?

**Comment by oheimala** [comment]
I have few of these buttons also. They appear as an unknown zigbee devices despite the "_TZ3000_qgwcxxws / TS0041" is listed in the compatible devices under "1 Button Smart Remote Controller"
