### ISSUE TITLE
Tuya Fingerbot via Bluetooth on Homey

### ISSUE THREAD

**Issue by Theluh** [JohanBendz/com.tuya.zigbee#99]
Dear Johan,

Have you ever considered to add Tuya Fingerbot on Homey. The Fingerbot is controlled via Bluetooth and is currently not supported in any app. I don’t have the hub which support Bluetooth (only zigbee) and actually I don’t use the hub anymore because I control all devices directly via your Tuya zigbee app on Homey. GREAT WORK!!

Since I don’t have the competence to program at this level I can’t do it myself. But I’m very willing to support you a device, I could order it via AliExpress and send it to you.

On Github there is already a page about the “Tuya-cloud-fingerbot-demo”. Maybe this is helpful.
https://github.com/Tuya-Community/tuya-cloud-fingerbot-demo

Greeting Martijn

**Comment by JohanBendz** [comment]
Hi @Theluh, sorry for the late answer.
This is a very nice feature of the Tuya platform, it is however better suited for the Tuya Cloud app. I try to stay away from the Tuya gateway/API/Wifi devices and let Jürgen handle those in his app :D :D

**Comment by JohanBendz** [comment]
Zigbee version: https://github.com/JohanBendz/com.tuya.zigbee/issues/869
