### ISSUE TITLE
Device Request - [Tuya Zigbee Door/Window Sensor - AliExpress] - [_TZ3000_n2egfsli] / [SNZB-04]

### ISSUE THREAD

**Issue by OMGatito** [JohanBendz/com.tuya.zigbee#998]
Device Information

Device Name: 'Door Sensor'
Device Model: _TZ3000_n2egfsli / SNZB-04
Device Description: Tuya ZigBee 3.0 Door Sensor
Link to device image: https://nl.aliexpress.com/item/1005007384428100.html?spm=a2g0o.productlist.main.1.1f568c3fKTcJXD&algo_pvid=7ab00a15-5272-44ed-9f15-f14043ee7a23&algo_exp_id=7ab00a15-5272-44ed-9f15-f14043ee7a23-0&pdp_npi=4%40dis%21EUR%2110.68%215.39%21%21%2180.60%2140.64%21%40211b80d117292393287587740eaf73%2112000040522651613%21sea%21NL%21703758525%21X&curPageLogUid=xK8Gl0sQeU7j&utparam-url=scene%3Asearch%7Cquery_from%3A

### Device Interview

  "ids": {
    "modelId": "SNZB-04",
    "manufacturerName": "_TZ3000_n2egfsli"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:e5:16:cc:d3:60",
    "networkAddress": 18309,
    "modelId": "SNZB-04",
    "manufacturerName": "_TZ3000_n2egfsli",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 18309,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [
          0,
          3,
          1,
          1280,
          32
        ],
        "outputClusters": [
          25
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "swBuildId": "0122052017",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "pollControl": {
      "checkInInterval": 14400,
      "longPollInterval": 14400,
      "shortPollInterval": 1,
      "checkInIntervalMin": 0,
      "longPollIntervalMin": 0,
      "shortPollWritten": true,
      "longPollWritten": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "stackVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 16384,
                "name": "swBuildId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision"
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "direction": "reported",
                  "attributeDataType": 32,
                  "minInterval": 0,
                  "maxInterval": 3600,
                  "minChange": 3,
                  "status": "SUCCESS"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "direction": "reported",
                  "attributeDataType": 32,
                  "minInterval": 0,
                  "maxInterval": 3600,
                  "minChange": 6,
                  "status": "SUCCESS"
                }
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "iasZone": {
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "pollControl": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "checkInInterval",
                "value": 14400
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "longPollInterval",
                "value": 14400
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2,
                "name": "shortPollInterval",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 3,
                "name": "fastPollTimeout",
                "value": 40
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "checkInIntervalMin",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "longPollIntervalMin",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6,
                "name": "fastPollTimeoutMax",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {}
        }
      }
    }
  }

### Additional Comments:

https://nl.aliexpress.com/item/1005007384428100.html?spm=a2g0o.productlist.main.1.1f568c3fKTcJXD&algo_pvid=7ab00a15-5272-44ed-9f15-f14043ee7a23&algo_exp_id=7ab00a15-5272-44ed-9f15-f14043ee7a23-0&pdp_npi=4%40dis%21EUR%2110.68%215.39%21%21%2180.60%2140.64%21%40211b80d117292393287587740eaf73%2112000040522651613%21sea%21NL%21703758525%21X&curPageLogUid=xK8Gl0sQeU7j&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by JohanBendz** [comment]
Hi @OMGatito, interesting find.. it's using Sonoff modelId and Tuya manufacturerName... well well.. added to next update.

**Comment by OMGatito** [comment]
Thanks Johan!I will let you know if it doesn’t work. Thanks again.Enviado do meu iPhoneNo dia 23/10/2024, às 22:15, Johan Bendz ***@***.***> escreveu:﻿
Hi @OMGatito, interesting find.. it's using Sonoff modelId and Tuya manufacturerName... well well.. added to next update.

**Comment by OMGatito** [comment]
Hi Johan,
Unfortunately, it still doesn't work. It's recognized as an unknown device.

**Comment by Siske7** [comment]
doesn't work here either
